import test from 'node:test';import assert from 'node:assert/strict';import {assertJungleReleaseTarget} from '../../backend/catalog/jungle_edition_catalog_release_v3.mjs';
import {assertJungleReleaseDatabaseTarget,assertJungleReleaseExecutionAuthority,assertJungleReleaseRollbackReceipt} from '../../backend/catalog/jungle_edition_catalog_release_guard_v3.mjs';
import {printingManifestHash as hash} from '../../backend/catalog/printing_completeness_gate_v1.mjs';
const now=Date.now(),project='ycdxbpibncqcchqiihfz',code='b'.repeat(64),plan={target:'production',fingerprint:'a'.repeat(64),rows:{raw_imports:[{}],card_prints:Array(128).fill({})},boundaries:{updates:0,deletes:0,ownedCopyWrites:0,sourceMappingWrites:0,pricingWrites:0,activeLinks:0}};
const counts={raw_imports:1,card_prints:128};
const authority=()=>{const a={version:'JUNGLE_CATALOG_RELEASE_AUTHORITY_V3',status:'explicit_founder_approval',project_ref:project,execution_version:'JUNGLE_EDITION_CATALOG_RELEASE_EXECUTION_V3',plan_fingerprint:plan.fingerprint,code_fingerprint:code,counts,boundaries:plan.boundaries,modes:['rollback','apply'],approval_record_ref:'synthetic-test-only',approval_text:'Synthetic test '+plan.fingerprint+' '+code,approved_at:new Date(now-1000).toISOString(),expires_at:new Date(now+60000).toISOString()};return {...a,fingerprint:hash(a)};};
const options={plan,codeFingerprint:code,mode:'apply',now};
test('exact bounded authority accepted by guard only',()=>assertJungleReleaseExecutionAuthority(authority(),options));
for(const [n,edit]of [
 ['wrong target',a=>a.project_ref='other'],['wrong plan',a=>a.plan_fingerprint='c'.repeat(64)],['wrong producer',a=>a.code_fingerprint='c'.repeat(64)],['broader count',a=>a.counts={...counts,card_prints:129}],['delete boundary',a=>a.boundaries={...plan.boundaries,deletes:1}],['expired',a=>a.expires_at=new Date(now-1).toISOString()],['future approval',a=>a.approved_at=new Date(now+1000).toISOString()],['missing exact text',a=>a.approval_text='Do it'],['missing record',a=>a.approval_record_ref=''],['unapproved mode',a=>a.modes=['rollback']],['unknown mode',a=>a.modes.push('activate')],['not approval',a=>a.status='prepared_for_review']
])test('reject '+n+' even with recalculated hash',()=>{const a=authority();edit(a);delete a.fingerprint;a.fingerprint=hash(a);assert.throws(()=>assertJungleReleaseExecutionAuthority(a,options));});
test('local rehearsal cannot authorize production',()=>assert.throws(()=>assertJungleReleaseExecutionAuthority(authority(),{...options,plan:{...plan,target:'local_rehearsal'}})));
const receipt=()=>({mode:'rollback',fingerprint:plan.fingerprint,code:{fingerprint:code},project_ref:project,target:'production',rollbackProven:true,after:'exact',activation:false,dependenciesPreserved:true,committed:false,commitUncertain:false,rollbackUncertain:false,writes:counts,finished_at:new Date(now).toISOString()});
test('fresh production rollback accepted',()=>assertJungleReleaseRollbackReceipt(receipt(),options));
for(const [n,edit]of [['local proof',r=>r.target='local_rehearsal'],['stale proof',r=>r.finished_at=new Date(now-3600001).toISOString()],['uncertain rollback',r=>r.rollbackUncertain=true],['missing inserts',r=>r.writes={...counts,card_prints:0}],['different producer',r=>r.code.fingerprint='c'.repeat(64)],['committed',r=>r.committed=true]])test('reject rollback '+n,()=>{const r=receipt();edit(r);assert.throws(()=>assertJungleReleaseRollbackReceipt(r,options));});
for(const url of ['postgresql://postgres:unused@127.0.0.1:65520/postgres','postgresql://postgres.other:unused@aws-1-us-east-2.pooler.supabase.com:5432/postgres','postgresql://postgres.'+project+':unused@aws-1-us-east-2.pooler.supabase.com:5432/postgres?options=-c%20search_path%3Devil'])test('reject wrong production URL '+url.split('@').at(-1),()=>assert.throws(()=>assertJungleReleaseDatabaseTarget(url)));
for(const [name,parameters,authorized]of [['wrong host',{host:'other'},true],['wrong project',{user:'postgres.other'},true],['TLS disabled',{ssl:{rejectUnauthorized:false}},true],['unverified TLS',{},false]])test('reject '+name+' before SQL',async()=>{let calls=0;const client={connectionParameters:{host:'aws-1-us-east-2.pooler.supabase.com',port:5432,database:'postgres',user:'postgres.'+project,ssl:{rejectUnauthorized:true},...parameters},connection:{stream:{authorized}},query:async()=>{calls++;}};await assert.rejects(assertJungleReleaseTarget(client,'production'));assert.equal(calls,0);});
test('production415 cannot enter423 engine',async()=>{const client={connectionParameters:{host:'aws-1-us-east-2.pooler.supabase.com',port:5432,database:'postgres',user:'postgres.'+project,ssl:{rejectUnauthorized:true}},connection:{stream:{authorized:true}},query:async()=>({rows:[{migrations:415}]})};await assert.rejects(assertJungleReleaseTarget(client,'production'),/qualified_423_schema_required/);});
import {spawnSync} from 'node:child_process';
for(const [name,args,pattern]of [
 ['unknown mode',['--mode=activate'],/AssertionError/],
 ['duplicate mode',['--mode=apply','--mode=apply'],/Unknown\/duplicate argument/],
 ['missing bounded inputs',['--mode=apply'],/Missing out-dir/],
 ['wrong producer before reading environment',['--mode=apply',...['out-dir','database-env-path','deps-root','manifest','artifact-map','execution-refresh','review-package'].map(k=>'--'+k+'=must-not-be-read'),'--code-fingerprint='+'0'.repeat(64)],/Wrong producer/]
])test('CLI rejects '+name,()=>{const r=spawnSync(process.execPath,['scripts/audits/jungle_edition_catalog_release_v3.mjs',...args],{encoding:'utf8',timeout:5000,windowsHide:true});assert.equal(r.status,1);assert.match(r.stderr,pattern);});

for(const [port,address,allowed]of [[53600,'10.248.23.7',true],[53400,'10.248.21.7',false],[53600,'10.248.21.7',false],[53400,'10.248.16.7',false],[53400,'10.248.21.7.attacker',false],[53401,'10.248.21.7',false]])test('fixed local port/subnet '+port+' '+address,async()=>{const c={connectionParameters:{host:'127.0.0.1',port,user:'postgres',database:'postgres'},query:async()=>({rows:[{address,workers:'0',migrations:423}]})};if(allowed)await assertJungleReleaseTarget(c,'local_rehearsal');else await assert.rejects(assertJungleReleaseTarget(c,'local_rehearsal'));});
