import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { DECKS, sha256 } from '../../backend/catalog/pokemon_classic_identity_evidence_v1.mjs';
import { VERSION, parseClassicPriceDex, qualifyClassicFinishes } from '../../backend/catalog/pokemon_classic_finish_evidence_v1.mjs';
import { classifyEvidence } from '../../scripts/audits/verified_master_set_index_v1/agreement_engine/classifier.mjs';

const root = new URL('../../docs/audits/english_master_index_completion_v1/classic_finish_20261002/', import.meta.url);
const identity = JSON.parse(fs.readFileSync(new URL('../classic_identity_20261002/identity-package.json', root)));
const acquisitions = JSON.parse(fs.readFileSync(new URL('checklist-acquisition.json', root)));
const observed = JSON.parse(fs.readFileSync(new URL('automated-visual-review.json', root)));
function input() {
  const review = structuredClone(observed);
  // Synthetic media bytes exercise binding only. This unit test never asserts
  // that generated bytes contain a physical card or issues a real review artifact.
  const photographs = review.rows.map(r => {
    const bytes = Buffer.from(`synthetic unit-test media ${r.deck_code}-${r.number}`);
    r.image_sha256 = sha256(bytes);
    return { deck_code: r.deck_code, number: r.number, bytes, sha256: sha256(bytes), status: 200, verified_tls: true,
      url: r.image_url, final_url: r.image_url, retrieved_at: '2026-10-02T19:00:00Z' };
  });
  return { identity: structuredClone(identity), review, reviewBytes: Buffer.from(JSON.stringify(review)), photographs,
    checklists: acquisitions.map(s => ({ ...s, bytes: gunzipSync(fs.readFileSync(new URL(s.file, root))) })) };
}
const bindReview = x => { x.reviewBytes = Buffer.from(JSON.stringify(x.review)); };
function changeSource(x, mutate) {
  const s = x.checklists[0]; s.bytes = Buffer.from(mutate(s.bytes.toString('utf8'))); s.sha256 = sha256(s.bytes);
}

test('all three original visible variant tables replay; Jumbo remains explicitly outside standard scope', () => {
  const x = input();
  for (const d of DECKS) {
    const parsed = parseClassicPriceDex(x.checklists.find(s => s.key === 'pricedex-' + d.printed_code.toLowerCase()), d);
    assert.equal(parsed.standard.length, 34); assert.ok(parsed.standard.every(r => r.raw_variant === 'Holo'));
    assert.equal(parsed.outside.length, d.printed_code === 'CLV' ? 1 : 0);
  }
});
test('whole102 candidate has two independent evidence families and exact standard deck profiles', () => {
  const x = input(), result = qualifyClassicFinishes(x);
  assert.deepEqual(qualifyClassicFinishes(x), result);
  assert.equal(result.records.length, 204); assert.equal(result.printings.length, 102);
  assert.ok(result.printings.every(p => p.source_count === 2 && p.finish_key === 'holo'));
  assert.equal(result.outside_scope_reviews.length, 1); assert.equal(result.outside_scope_reviews[0].resolved, false);
  assert.equal(result.whole_product_complete, false); assert.equal(result.human_signature, null);
  assert.equal(result.active_master_changed, false); assert.equal(result.write_ready, false); assert.equal(result.production_writes, 0);
  for (const p of result.profiles) {
    assert.equal(p.parents, 34); assert.equal(p.printings, 34); assert.deepEqual(p.finish_counts, { holo: 34 });
    assert.equal(p.exact_facts_sha256, sha256(JSON.stringify(p.exact_facts))); assert.deepEqual(p.protected_facts, p.exact_facts);
  }
});
test('one checklist alone remains single-source even when catalog prices or links agree', () => {
  const result = qualifyClassicFinishes(input());
  const onlyChecklist = result.records.filter(r => r.source_key === 'thepricedex_price_list');
  assert.ok(classifyEvidence(onlyChecklist).printings.every(p => p.status === 'human_source_verified' && p.source_count === 1));
});
test('prices may change without creating or changing any printing fact', () => {
  const x = input(), before = qualifyClassicFinishes(x);
  changeSource(x, s => s.replace(/\$17\.02/g, '$9999.99'));
  const after = qualifyClassicFinishes(x);
  assert.deepEqual(after.profiles.map(p => [p.exact_facts_sha256, p.finish_counts]), before.profiles.map(p => [p.exact_facts_sha256, p.finish_counts]));
  assert.notEqual(after.outside_scope_reviews[0].source_sha256, before.outside_scope_reviews[0].source_sha256);
  assert.deepEqual(after.printings.map(p => [p.set_key, p.card_number, p.card_name, p.finish_key]), before.printings.map(p => [p.set_key, p.card_number, p.card_name, p.finish_key]));
});
for (const [name, mutate, expected] of [
  ['tampered checklist bytes', x => { x.checklists[0].bytes = Buffer.from('changed'); }, /source_bytes_hash/],
  ['failed checklist', x => { x.checklists[0].status = 403; }, /successful_acquisition/],
  ['nonverified TLS', x => { x.photographs[0].verified_tls = false; }, /verified_tls/],
  ['mirror passed as physical source', x => { x.photographs[0].url = 'https://www.thepricedex.com/photo'; }, /source_host/],
  ['failed physical source', x => { x.photographs[0].status = 404; }, /successful_acquisition/],
  ['missing physical source', x => { x.photographs.pop(); }, /102/],
  ['missing review row', x => { x.review.rows.pop(); bindReview(x); }, /whole102/],
  ['wrong deck coordinate', x => { x.review.rows[0].deck_code = 'CLB'; bindReview(x); }, /whole102/],
  ['wrong denominator', x => { x.review.rows[0].printed_total = '032'; bindReview(x); }, /034/],
  ['Japanese physical image', x => { x.review.rows[0].language = 'ja'; bindReview(x); }, /en/],
  ['prerelease image', x => { x.review.rows[0].media_kind = 'prerelease_render'; bindReview(x); }, /final_physical/],
  ['obscured coordinate', x => { x.review.rows[0].identity_visible = false; bindReview(x); }, /true/],
  ['unreviewed foil', x => { x.review.rows[0].holographic_surface_visible = false; bindReview(x); }, /true/],
  ['invented specialty finish', x => { x.review.rows[0].finish_key = 'cosmos'; bindReview(x); }, /holo/],
  ['source conflict', x => { x.review.rows[0].conflicts = ['different card']; bindReview(x); }, /different card/],
  ['claimed human signature', x => { x.review.human_signature = 'human approved'; bindReview(x); }, /null/],
  ['claimed human actor', x => { x.review.actor_type = 'human'; bindReview(x); }, /automated_agent/],
  ['review before image acquisition', x => { x.review.reviewed_at = '2020-01-01T00:00:00Z'; bindReview(x); }, /predates/],
  ['review byte drift', x => { x.reviewBytes = Buffer.from('{}'); }, /review_canonical/],
  ['image changed after review', x => { x.photographs[0].bytes = Buffer.from('new'); x.photographs[0].sha256 = sha256(x.photographs[0].bytes); }, /review_image_binding/],
  ['reused image for another identity', x => { const p = x.photographs[0], q = x.photographs[1]; q.bytes = p.bytes; q.sha256 = p.sha256; x.review.rows[1].image_sha256 = p.sha256; bindReview(x); }, /reused_photo/],
  ['photo name variant', x => { x.review.rows[0].printed_name += ' STAFF'; bindReview(x); }, /photo_identity/],
  ['identity hash tamper', x => { x.identity.joins[0].card_name = 'other'; }, /identity_package_hash/],
  ['wrong checklist language', x => changeSource(x, s => s.replace('"language":"English"', '"language":"Japanese"')), /English/],
  ['rarity replacing Variant header', x => changeSource(x, s => s.replace('>Variant</th>', '>Rarity</th>')), /exact_variant_column/],
  ['missing explicit Holo cell', x => changeSource(x, s => s.replace('>Holo</p>', '>Unknown</p>')), /variant_disagreement/],
  ['unknown variant even if visible and metadata agree', x => changeSource(x, s => s.replaceAll('Jumbo', 'Cosmos').replaceAll('"jumbo"', '"cosmos"')), /variant_disagreement|unreviewed_extra/],
]) test(`${name} blocks the whole102 candidate`, () => {
  const x = input(); mutate(x); assert.throws(() => qualifyClassicFinishes(x), expected);
});
test('new physical treatment observations are preserved rather than mapped to Cosmos or erased', () => {
  const result = qualifyClassicFinishes(input());
  const photos = result.records.filter(r => r.source_key !== 'thepricedex_price_list');
  assert.equal(photos.filter(r => r.finish_key_raw === 'diagonal_rainbow_foil').length, 3);
  assert.equal(photos.filter(r => r.finish_key_raw === 'patterned_reflective_foil').length, 99);
  assert.ok(photos.every(r => r.finish_key === 'holo'));
  assert.equal(result.version, VERSION);
});
