import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {mappingFixture} from '../fixtures/reviewed_gamestop_mapping_v1.mjs';import {seal} from '../fixtures/warehouse_printing_authority_v1.mjs';
import {printingManifestHash as hash} from '../../backend/catalog/printing_completeness_gate_v1.mjs';
import {assertReviewedGameStopMapping} from '../../backend/warehouse/reviewed_gamestop_mapping_v1.mjs';
import {assertMappingPricingAdjudication,assertMappingPricingGuards} from '../../backend/warehouse/reviewed_mapping_pricing_adjudication_v1.mjs';
function fixture(){const b=mappingFixture();b.dependencies.footprints=[{relation:'market_price_publication_snapshots',field:'source_mapping_id',type:'int8',count:2,digest:'synthetic-ledger'},...['card_print_id','card_printing_id'].map(field=>({relation:'market_price_publication_snapshots',field,type:'uuid',count:2,digest:'synthetic-ledger'}))];const review={version:'REVIEWED_MAPPING_PRICING_ADJUDICATION_V1',status:'verified_scope',card_print_id:b.target.card_print_id,dependencies_sha256:hash(b.dependencies),immutable_history_retained:true,expected_outcome:'unavailable_rejected_price_and_history',migration_version:'20261001190000',reader_hashes:Object.fromEntries(['get_market_pricing_read_model_v1','v_market_price_current_v1','v_market_price_history_v1'].map(n=>[n,'a'.repeat(64)])),publication_pointer_sha256:'b'.repeat(64),evidence_sha256:'c'.repeat(64),reviewer:'synthetic',reviewed_at:'2026-10-01T00:00:00Z',mapping_ids:[9],retained_mapping_references:structuredClone(b.dependencies.footprints.filter(f=>f.type!=='uuid'))};return {b,review};}
function bind(b,r){const bytes=Buffer.from(JSON.stringify(r));b.manifest.pricing_dependency_adjudication={ref:'pricing-review',sha256:createHash('sha256').update(bytes).digest('hex')};return new Map([['pricing-review',bytes]]);}
test('separate pricing review admits only exact immutable mapping-reference scope',()=>{const {b,review}=fixture();assert.equal(assertMappingPricingAdjudication(b,bind(b,review)).mapping_ids[0],9);});
for(const defect of ['different_mapping','other_dependency','omitted_references','changed_dependencies','missing_guard','mutable_history','mixed_history'])test('pricing adjudication rejects '+defect,()=>{const {b,review}=fixture();if(defect==='different_mapping')review.mapping_ids=[10];if(defect==='other_dependency'){b.dependencies.footprints[0].relation='collector_private_rows';review.dependencies_sha256=hash(b.dependencies);review.retained_mapping_references=b.dependencies.footprints;}if(defect==='omitted_references')review.retained_mapping_references=[];if(defect==='changed_dependencies')b.dependencies.footprints[0].count=3;if(defect==='missing_guard')delete review.reader_hashes.v_market_price_history_v1;if(defect==='mutable_history')review.immutable_history_retained=false;if(defect==='mixed_history'){b.dependencies.footprints[1].digest='other-parent-rows';review.dependencies_sha256=hash(b.dependencies);}assert.throws(()=>assertMappingPricingAdjudication(b,bind(b,review)));});
test('rehashing an envelope cannot add pricing authority to an old Master review',()=>{const {b,review}=fixture();bind(b,review);b.manifest=seal(b.manifest);assert.throws(()=>assertReviewedGameStopMapping(seal(b)),/review_projection_mismatch/);});
test('uninstalled pricing migration is denied before reader queries',async()=>{let calls=0;await assert.rejects(assertMappingPricingGuards({async query(){calls++;return {rows:[{n:0}]};}},fixture().review),/pricing_guard_migration_not_installed/);assert.equal(calls,1);});
