import test from 'node:test';import assert from 'node:assert/strict';
import {createVendorOrderHandlers} from '../../apps/web/src/lib/payments/vendorOrderHttp.ts';
import {readOrderRuntimeConfig} from '../../apps/web/src/lib/payments/vendorOrderRuntimePolicy.ts';
import {CheckoutEvidenceError} from '../../apps/web/src/lib/payments/vendorCheckoutEvidence.ts';
import {VendorOrderError} from '../../apps/web/src/lib/payments/vendorOrderService.ts';
import {createOrderHttpRuntime} from '../../apps/web/src/lib/payments/vendorOrderRuntimeService.ts';
import {checkoutFixture} from '../helpers/vendorCheckoutFixture.mjs';
const buyer='11111111-1111-4111-8111-111111111111',orderId='22222222-2222-4222-8222-222222222222',origin='http://127.0.0.1:20040',token='ab'.repeat(32);
function fixture(){
 const f={buyer,token,calls:[],runtimeCalls:[],result:{orderId,state:'open',url:'https://checkout.stripe.com/c/pay/cs_test_fixture#fragment'},page:{succeeded:[orderId],failed:[],next:null,complete:true,budgetExhausted:false}};
 f.runtime={checkout:async(...args)=>{f.calls.push(['checkout',...args]);return f.result;},signal:async(...args)=>{f.calls.push(['signal',...args]);return {orderId:'PRIVATE'};},reconcile:async(...args)=>{f.calls.push(['reconcile',...args]);return f.page;},retry:async(...args)=>{f.calls.push(['retry',...args]);return {PRIVATE:true};}};
 f.handlers=createVendorOrderHandlers({authenticate:async()=>f.buyer,origin:()=>origin,runtime:lane=>{f.runtimeCalls.push(lane);return f.runtime;},reconcileToken:()=>f.token});return f;
}
const request=(lane,body,headers={})=>new Request(origin+'/api/vendor-orders/'+lane,{method:'POST',headers,body:typeof body==='string'?body:JSON.stringify(body)});
const checkout=(f,body={orderId},headers={origin})=>f.handlers.checkout(request('checkout',body,headers));
const reconcile=(f,body={},headers={authorization:`Bearer ${token}`})=>f.handlers.reconcile(request('reconcile',body,headers));
test('checkout takes server Auth buyer and immutable order ID only; private result',async()=>{const f=fixture(),r=await checkout(f);assert.equal(r.status,200);assert.deepEqual(f.calls,[['checkout',orderId,buyer]]);assert.deepEqual(await r.json(),f.result);assert.equal(r.headers.get('cache-control'),'private, no-store');assert.equal(r.headers.get('referrer-policy'),'no-referrer');});
for(const headers of [{},{origin:'https://evil.invalid'},{origin:origin+'.evil'},{authorization:'Bearer forged'}])test(`checkout CSRF ${JSON.stringify(headers)}`,async()=>{const f=fixture();assert.equal((await checkout(f,{orderId},headers)).status,403);assert.equal(f.runtimeCalls.length,0);});
test('anonymous checkout does not instantiate privileged runtime',async()=>{const f=fixture();f.buyer=null;assert.equal((await checkout(f)).status,401);assert.equal(f.runtimeCalls.length,0);});
for(const body of [{orderId,buyerId:buyer},{orderId,amount:1},{orderId,paid:true},{orderId,returnUrl:'https://evil.invalid'},{orderId,sellerId:buyer},{orderId,quoteReference:buyer},[],null,{},'{bad',{orderId:'invalid'}])test(`checkout rejects forged body ${JSON.stringify(body)}`,async()=>{const f=fixture();assert.equal((await checkout(f,body)).status,400);assert.equal(f.runtimeCalls.length,0);});
test('body bound is enforced on actual streamed bytes',async()=>{const f=fixture();const stream=new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('x'.repeat(513)));c.close();}});const r=await f.handlers.checkout(new Request(origin+'/api/vendor-orders/checkout',{method:'POST',headers:{origin},body:stream,duplex:'half'}));assert.equal(r.status,413);assert.equal(f.calls.length,0);});
test('disabled runtime rejects without work',async()=>{const f=fixture();f.runtime=null;assert.equal((await checkout(f)).status,503);assert.equal(f.calls.length,0);});
test('opaque errors and foreign-order failures do not expose bindings',async()=>{const f=fixture();f.runtime.checkout=async()=>{throw new Error('PRIVATE OWNER SECRET');};const r=await checkout(f);assert.equal(r.status,503);assert.doesNotMatch(await r.text(),/PRIVATE|SECRET/);});
test('lease contention has a retryable conflict',async()=>{const f=fixture();f.runtime.checkout=async()=>{throw new VendorOrderError('order_claim_busy');};assert.equal((await checkout(f)).status,409);});
for(const url of ['http://checkout.stripe.com/c/pay/cs_test_x','https://evil.invalid/c/pay/cs_test_x','https://checkout.stripe.com.evil.invalid/c/pay/cs_test_x','https://x@checkout.stripe.com/c/pay/cs_test_x','https://checkout.stripe.com/c/pay/cs_test_x?q=1','https://checkout.stripe.com/other'])test(`unsafe checkout result ${url}`,async()=>{const f=fixture();f.result.url=url;assert.equal((await checkout(f)).status,503);});
test('terminal response and extra fields are narrowed',async()=>{const f=fixture();f.result={orderId,state:'reconciled',PRIVATE:true};const r=await checkout(f);assert.deepEqual(await r.json(),{orderId,state:'reconciled'});});
test('webhook sends exact raw content and header to retention, returns no order binding',async()=>{const f=fixture(),raw=' { "value": "☃" }\n',r=await f.handlers.webhook(request('webhook',raw,{'stripe-signature':'signed'}));assert.equal(r.status,200);assert.deepEqual(f.calls,[['signal',raw,'signed']]);assert.deepEqual(await r.json(),{received:true});});
test('invalid signature is 400; storage failure is retryable 503',async()=>{const f=fixture();f.runtime.signal=async()=>{throw new CheckoutEvidenceError('checkout_signature_invalid');};assert.equal((await f.handlers.webhook(request('webhook','x'))).status,400);f.runtime.signal=async()=>{throw new Error('PRIVATE');};const r=await f.handlers.webhook(request('webhook','x'));assert.equal(r.status,503);assert.doesNotMatch(await r.text(),/PRIVATE/);});
test('oversized webhook is rejected before ledger work',async()=>{const f=fixture();assert.equal((await f.handlers.webhook(request('webhook','x',{'content-length':String(256*1024+1)}))).status,413);assert.equal(f.calls.length,0);});
for(const headers of [{},{cookie:'signed-user'},{authorization:'Bearer forged'},{authorization:`Bearer ${'cd'.repeat(32)}`},{'stripe-signature':token},{authorization:token}])test(`operator auth denied ${JSON.stringify(headers)}`,async()=>{const f=fixture();assert.equal((await reconcile(f,{},headers)).status,401);assert.equal(f.runtimeCalls.length,0);});
test('unset/malformed operator credential always fails closed',async()=>{for(const value of [null,'','short','A'.repeat(64)]){const f=fixture();f.token=value;assert.equal((await reconcile(f)).status,401);}});
for(const body of [{limit:0},{limit:26},{limit:1.5},{after:'invalid'},{orderId,limit:1},{ownerId:buyer},{force:true},[],null])test(`reconcile rejects ${JSON.stringify(body)}`,async()=>{const f=fixture();assert.equal((await reconcile(f,body)).status,400);assert.equal(f.calls.length,0);});
test('bounded operator page and targeted retry have distinct narrow responses',async()=>{const f=fixture();assert.equal((await reconcile(f,{after:orderId,limit:3})).status,200);assert.deepEqual(f.calls[0],['reconcile',{after:orderId,limit:3}]);assert.deepEqual(await (await reconcile(f,{orderId})).json(),{reconciled:true,orderId});});
test('failed IDs and interrupted page remain retryable with exact continuation',async()=>{const f=fixture();f.page={succeeded:[],failed:[orderId],next:orderId,complete:false,budgetExhausted:false};const r=await reconcile(f);assert.equal(r.status,503);assert.deepEqual(await r.json(),f.page);f.page.failed=[];f.page.budgetExhausted=true;assert.equal((await reconcile(f)).status,503);});
test('GET cannot mutate any lane',async()=>{const f=fixture();for(const lane of ['checkout','webhook','reconcile'])assert.equal((await f.handlers[lane](new Request(origin))).status,405);assert.equal(f.calls.length,0);});
function env(){return {GROOKAI_VENDOR_ORDER_CHECKOUT_ENABLED:'true',GROOKAI_VENDOR_ORDER_EVENTS_ENABLED:'true',GROOKAI_VENDOR_ORDER_RECONCILIATION_ENABLED:'true',STRIPE_PAYMENTS_MODE:'test',STRIPE_ACCOUNT_ID:'acct_platform',STRIPE_SECRET_KEY:['sk','test','syntheticOnly'].join('_'),STRIPE_ORDER_WEBHOOK_SECRET:['whsec','orderSyntheticSecretOnly'].join('_'),STRIPE_CONNECT_WEBHOOK_SECRET:['whsec','sellerSeparateSecretOnly'].join('_'),GROOKAI_VENDOR_ORDER_QUOTE_POLICY:'local-synthetic-pickup-v1',NEXT_PUBLIC_STOREFRONT_LOCAL_TEST:'true',NEXT_PUBLIC_COLLECTOR_STAGING:'true',GROOKAI_DISABLE_TELEMETRY:'1',SUPABASE_URL:'http://127.0.0.1:15439'};}
test('all lanes default off and subscriptions/onboarding cannot enable them',()=>{for(const lane of ['checkout','events','reconcile'])assert.equal(readOrderRuntimeConfig({GROOKAI_VENDOR_CHECKOUT_ENABLED:'true',GROOKAI_VENDOR_PAYMENTS_ENABLED:'true',GROOKAI_VENDOR_ONBOARDING_ENABLED:'true'},lane,origin),null);});
test('retained obligation lanes do not require acquisition or package gates; secret is endpoint-specific',()=>{const e=env();e.GROOKAI_VENDOR_ORDER_CHECKOUT_ENABLED='false';e.GROOKAI_VENDOR_PAYMENTS_ENABLED='false';for(const lane of ['events','reconcile'])assert.equal(readOrderRuntimeConfig(e,lane,'https://grookaivault.com').webhookSecret,e.STRIPE_ORDER_WEBHOOK_SECRET);delete e.STRIPE_ORDER_WEBHOOK_SECRET;assert.throws(()=>readOrderRuntimeConfig(e,'events',origin));});
test('only synthetic local checkout config is accepted',()=>assert.equal(readOrderRuntimeConfig(env(),'checkout',origin).scope.livemode,false));
for(const [key,value] of [['GROOKAI_VENDOR_ORDER_QUOTE_POLICY','production'],['NEXT_PUBLIC_STOREFRONT_LOCAL_TEST','false'],['NEXT_PUBLIC_COLLECTOR_STAGING','false'],['GROOKAI_DISABLE_TELEMETRY','0'],['SUPABASE_URL','https://private.supabase.co'],['VERCEL','1'],['VERCEL_ENV','preview'],['NEXT_PUBLIC_COLLECTOR_HOSTED_STAGING','true']])test(`checkout policy denies ${key}`,()=>assert.throws(()=>readOrderRuntimeConfig({...env(),[key]:value},'checkout',origin)));
test('live/hosted checkout is blocked even with forged quote policy flags',()=>{const e={...env(),STRIPE_PAYMENTS_MODE:'live',STRIPE_SECRET_KEY:['sk','live','syntheticOnly'].join('_')};assert.throws(()=>readOrderRuntimeConfig(e,'checkout',origin));assert.throws(()=>readOrderRuntimeConfig(env(),'checkout','https://grookaivault.com'));});
test('runtime signal uses real Stripe verifier and ignores forged order metadata; no provider HTTP work',async()=>{
 const f=checkoutFixture();f.now=Math.floor(Date.now()/1000);const calls=[],admin={rpc:async(name,args)=>{calls.push([name,args]);return {data:orderId,error:null};}};
 const runtime=createOrderHttpRuntime(admin,f.stripe,f.config),h=createVendorOrderHandlers({authenticate:async()=>null,origin:()=>origin,runtime:()=>runtime,reconcileToken:()=>null});
 const event=f.event();event.created=f.now;event.data.object.metadata={grookai_order_id:'FORGED'};const payload=JSON.stringify(event),signature=f.stripe.webhooks.generateTestHeaderString({payload,secret:f.config.webhookSecret,timestamp:f.now});
 assert.equal((await h.webhook(request('webhook',payload,{'stripe-signature':signature}))).status,200);assert.equal(calls[0][0],'vendor_order_signal_v1');assert.equal(calls[0][1].p_resource,f.session.id);assert.doesNotMatch(JSON.stringify(calls),/FORGED/);assert.equal(f.calls.length,0);
 assert.equal((await h.webhook(request('webhook',payload+' ',{'stripe-signature':signature}))).status,400);assert.equal(calls.length,1);
});
