import test from 'node:test';import assert from 'node:assert/strict';
import {acquisitionIds,createAcquisitionService,AcquisitionError} from '../../apps/web/src/lib/orders/orderAcquisitionService.ts';
import {readAcquisitionConfig} from '../../apps/web/src/lib/orders/orderAcquisitionPolicy.ts';
import {createAcquisitionHandlers} from '../../apps/web/src/lib/orders/orderAcquisitionHttp.ts';
const buyer='11111111-1111-4111-8111-111111111111',owner='22222222-2222-4222-8222-222222222222',item='33333333-3333-4333-8333-333333333333',store='44444444-4444-4444-8444-444444444444',seller='55555555-5555-4555-8555-555555555555',request='66666666-6666-4666-8666-666666666666',origin='http://127.0.0.1:20040';
const selection={requestId:request,storeId:store,itemId:item,kind:'custom',quantity:2};
const config={secret:'ab'.repeat(32),platformAccountId:'acct_testPlatform'};
function fixture(){
 const ids=acquisitionIds(buyer,request),f={now:1800000000000,calls:[],saved:null,failCreate:false};
 f.row={id:ids.reservation,buyer_id:buyer,owner_id:owner,store_id:store,seller_id:seller,instance_id:null,product_id:item,quantity:2,offer:{schema:'VENDOR_STOCK_OFFER_V1',kind:'custom',product_id:item,title:'Recorded title',version:1,currency:'USD',unit_amount:12.34},state:'held',created_at:new Date(f.now).toISOString(),expires_at:new Date(f.now+120000).toISOString()};
 f.seller={id:seller,owner_id:owner,store_id:store,stripe_account_id:config.platformAccountId,livemode:false,state:'bound',closeout_id:null,controller:{feesPayer:'account',paymentLosses:'stripe',requirementCollection:'stripe',dashboard:'full'}};
 f.repo={reserve:async()=>{f.calls.push('reserve');return structuredClone(f.row);},reservation:async(id,user)=>{f.calls.push('reservation');return id===f.row.id&&user===buyer?structuredClone(f.row):null;},existing:async()=>f.saved,seller:async()=>f.seller,create:async(r,ids)=>{f.calls.push('create');f.row.state='payment_pending';f.saved={id:ids.order,buyer_id:buyer,reservation_id:r.id,quote_reference:ids.quote,fulfillment:'pickup',unit_amount_minor:1234,quantity:2,shipping_amount_minor:0,tax_amount_minor:0,currency:'usd'};if(f.failCreate)throw Error('lost response');return f.saved;},release:async()=>{f.calls.push('release');if(f.row.state==='payment_pending')throw new AcquisitionError('stock_payment_resolution_required');f.row.state='released';}};
 f.service=createAcquisitionService(f.repo,config,()=>f.now);f.quote=()=>f.service.quote(buyer,selection);return f;
}
test('server snapshot computes exact minor totals and narrow signed quote',async()=>{const f=fixture(),q=await f.quote();assert.equal(q.totalAmountMinor,2468);assert.equal(q.title,'Recorded title');assert.equal(q.expiresAt,f.now+120000);assert.doesNotMatch(JSON.stringify(q),/owner_id|seller_id|acct_|buyer_id/);assert.equal(f.calls.includes('create'),false);});
test('repeated quote cannot extend its original deadline or change anchor',async()=>{const f=fixture(),q=await f.quote();f.now+=60000;const second=await f.quote();assert.deepEqual(second,q);});
test('confirm creates one deterministic order and retry survives expiry/seller downgrade',async()=>{const f=fixture(),q=await f.quote(),created=await f.service.confirm(buyer,q.token);f.now+=130000;f.seller.state='closing';assert.deepEqual(await f.service.confirm(buyer,q.token),created);assert.equal(f.calls.filter(c=>c==='create').length,1);assert.deepEqual(await f.quote(),created);});
test('lost confirmation response recovers existing order and never creates replacement',async()=>{const f=fixture(),q=await f.quote();f.failCreate=true;await assert.rejects(f.service.confirm(buyer,q.token));f.failCreate=false;const r=await f.service.confirm(buyer,q.token);assert.equal(r.orderId,acquisitionIds(buyer,request).order);assert.equal(f.calls.filter(c=>c==='create').length,1);});
test('expired unconfirmed quote cannot create an order',async()=>{const f=fixture(),q=await f.quote();f.now+=120000;await assert.rejects(f.service.confirm(buyer,q.token),/quote_expired/);assert.equal(f.calls.includes('create'),false);});
test('cancel releases held quote; repeat confirms cannot resurrect it',async()=>{const f=fixture(),q=await f.quote();assert.deepEqual(await f.service.cancel(buyer,q.token),{state:'released'});await assert.rejects(f.service.confirm(buyer,q.token),/quote_expired/);});
test('cancel after confirmation recovers order without release',async()=>{const f=fixture(),q=await f.quote();const o=await f.service.confirm(buyer,q.token);assert.deepEqual(await f.service.cancel(buyer,q.token),o);assert.equal(f.calls.includes('release'),false);});
test('quote token belongs only to authenticated buyer, prior to any database read',async()=>{const f=fixture(),q=await f.quote();const before=f.calls.length;await assert.rejects(f.service.confirm(owner,q.token),/quote_invalid/);assert.equal(f.calls.length,before);});
for(const mutate of [t=>t+'x',t=>t.replace(/^./,t[0]==='a'?'b':'a'),t=>t.split('.')[0]+'.'+'x'.repeat(43),()=>'',()=> 'x'.repeat(3000)])test('tampered/malformed token fails before repository access',async()=>{const f=fixture(),q=await f.quote(),n=f.calls.length;await assert.rejects(f.service.confirm(buyer,mutate(q.token)));assert.equal(f.calls.length,n);});
test('immutable snapshot hash mismatch rejects confirmation',async()=>{const f=fixture(),q=await f.quote();f.row.offer.unit_amount=1;await assert.rejects(f.service.confirm(buyer,q.token),/quote_invalid/);});
for(const price of [-1,0,0.001,12.345,NaN,Infinity,1000000,'12.34'])test(`invalid snapshot amount ${price}`,async()=>{const f=fixture();f.row.offer.unit_amount=price;await assert.rejects(f.quote());});
test('decimal cents avoid floating-point multiplication rounding',async()=>{const f=fixture();f.row.offer.unit_amount=0.07;assert.equal((await f.quote()).totalAmountMinor,14);});
for(const [key,value] of [['livemode',true],['stripe_account_id','acct_other'],['owner_id',buyer],['state','closing'],['closeout_id',store],['controller',{}]])test(`seller snapshot rejects ${key}`,async()=>{const f=fixture();f.seller[key]=value;await assert.rejects(f.quote());assert.equal(f.calls.includes('create'),false);});
test('signing-secret rotation does not change stable order IDs or held quote recovery',async()=>{const f=fixture(),q=await f.quote();f.service=createAcquisitionService(f.repo,{...config,secret:'cd'.repeat(32)},()=>f.now);await assert.rejects(f.service.confirm(buyer,q.token),/quote_invalid/);const fresh=await f.quote();const o=await f.service.confirm(buyer,fresh.token);assert.equal(o.orderId,acquisitionIds(buyer,request).order);});
test('copy quantities and wrong item snapshots fail closed',async()=>{const f=fixture();await assert.rejects(f.service.quote(buyer,{...selection,kind:'copy'}));f.row.offer.product_id=owner;await assert.rejects(f.quote());});
function handlerFixture(){const f=fixture();f.user=buyer;f.runtimeCalls=0;f.handler=createAcquisitionHandlers({authenticate:async()=>f.user,origin:()=>origin,service:()=>{f.runtimeCalls++;return f.service;}});return f;}
const post=(f,body,headers={origin})=>f.handler(new Request(origin+'/api/vendor-orders/acquire',{method:'POST',headers,body:JSON.stringify(body)}));
test('real handler exposes quote then confirmation with private responses',async()=>{const f=handlerFixture(),r=await post(f,{action:'quote',...selection});assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'private, no-store');const q=await r.json();assert.equal((await post(f,{action:'confirm',token:q.token})).status,200);});
for(const body of [{action:'quote',...selection,amount:1},{action:'quote',...selection,buyerId:buyer},{action:'quote',...selection,shipping:0},{action:'quote',...selection,quantity:101},{action:'confirm',token:'x',paid:true},{action:'cancel',token:'x',orderId:request},null,[]])test(`forged acquisition input ${JSON.stringify(body)}`,async()=>{const f=handlerFixture();assert.equal((await post(f,body)).status,400);assert.equal(f.runtimeCalls,0);});
test('same-origin Auth precedes privileged work',async()=>{const f=handlerFixture();assert.equal((await post(f,{},{})).status,403);f.user=null;assert.equal((await post(f,{})).status,401);assert.equal(f.runtimeCalls,0);});
test('disabled acquisition has no side effects',async()=>{const f=handlerFixture();f.service=null;assert.equal((await post(f,{action:'quote',...selection})).status,503);assert.equal(f.calls.length,0);});
test('expired errors are retryable without leaking raw storage errors',async()=>{const f=handlerFixture(),q=await f.quote();f.now+=120000;assert.equal((await post(f,{action:'confirm',token:q.token})).status,409);f.repo.reserve=async()=>{throw Error('PRIVATE SECRET');};const r=await post(f,{action:'quote',...selection});assert.equal(r.status,503);assert.doesNotMatch(await r.text(),/PRIVATE|SECRET/);});
function env(){return {GROOKAI_VENDOR_ORDER_ACQUISITION_ENABLED:'true',GROOKAI_VENDOR_ORDER_QUOTE_POLICY:'local-synthetic-pickup-v1',STRIPE_PAYMENTS_MODE:'test',STRIPE_ACCOUNT_ID:config.platformAccountId,GROOKAI_VENDOR_ORDER_QUOTE_SECRET:config.secret,NEXT_PUBLIC_STOREFRONT_LOCAL_TEST:'true',NEXT_PUBLIC_COLLECTOR_STAGING:'true',GROOKAI_DISABLE_TELEMETRY:'1',SUPABASE_URL:'http://127.0.0.1:15439'};}
test('acquisition requires its own flag; valid fixture needs no provider key',()=>{assert.equal(readAcquisitionConfig({},origin),null);assert.deepEqual(readAcquisitionConfig(env(),origin),config);});
for(const [key,value] of [['GROOKAI_VENDOR_ORDER_QUOTE_POLICY','live'],['STRIPE_PAYMENTS_MODE','live'],['NEXT_PUBLIC_STOREFRONT_LOCAL_TEST','false'],['NEXT_PUBLIC_COLLECTOR_STAGING','false'],['GROOKAI_DISABLE_TELEMETRY','0'],['SUPABASE_URL','https://prod.invalid'],['VERCEL','1'],['VERCEL_ENV','preview'],['GROOKAI_VENDOR_ORDER_QUOTE_SECRET','short'],['STRIPE_ACCOUNT_ID','wrong']])test(`production/invalid quote policy refuses ${key}`,()=>assert.throws(()=>readAcquisitionConfig({...env(),[key]:value},origin)));
test('hosted origin rejected even with local flags',()=>assert.throws(()=>readAcquisitionConfig(env(),'https://grookaivault.com')));
for(const kind of [['custom'],{kind:'custom'},null])test(`kind must be a literal string: ${JSON.stringify(kind)}`,async()=>{const f=handlerFixture();assert.equal((await post(f,{action:'quote',...selection,kind})).status,400);assert.equal(f.runtimeCalls,0);});
test('oversize body and query overrides fail before privileged runtime',async()=>{const f=handlerFixture();assert.equal((await post(f,{action:'confirm',token:'x'.repeat(4000)})).status,413);assert.equal((await f.handler(new Request(origin+'/api/vendor-orders/acquire?buyer=forged',{method:'POST',headers:{origin},body:JSON.stringify({action:'quote',...selection})}))).status,400);assert.equal(f.runtimeCalls,0);});
test('GET cannot reserve and malformed JSON is rejected',async()=>{const f=handlerFixture();assert.equal((await f.handler(new Request(origin+'/api/vendor-orders/acquire'))).status,405);assert.equal((await f.handler(new Request(origin+'/api/vendor-orders/acquire',{method:'POST',headers:{origin},body:'{'}))).status,400);assert.equal(f.runtimeCalls,0);});
