import test from 'node:test';import assert from 'node:assert/strict';
import {fulfillmentStatus,fulfillmentCommand,fulfillmentActions,fulfillmentEnabled,fulfillmentService,fulfillmentHandler} from '../../apps/web/src/lib/orders/orderFulfillment.ts';
const order='11111111-1111-4111-8111-111111111111',owner='22222222-2222-4222-8222-222222222222',requestId='33333333-3333-4333-8333-333333333333';
const command=()=>({orderId:order,requestId,expectedSequence:0,action:'ship',carrier:'ups',tracking:'1Z SYNTHETIC 001'});
const receipt=()=>({orderId:order,requestId,sequence:1,action:'ship',state:'shipped',carrier:'ups',tracking:'1Z SYNTHETIC 001',recordedAt:'2026-09-20T08:00:00Z'});
const status=()=>({schema:'VENDOR_ORDER_FULFILLMENT_V1',orderId:order,mode:'shipping',role:'seller',canManage:true,paymentReady:true,sequence:1,state:'shipped',carrier:'ups',tracking:'1Z SYNTHETIC 001',updatedAt:receipt().recordedAt,events:[receipt()]});
test('participant DTO strips unknown data and offers only applicable actions',()=>{const value=fulfillmentStatus({...status(),secret:'PRIVATE'});assert.doesNotMatch(JSON.stringify(value),/PRIVATE|orderId.*orderId/);assert.deepEqual(fulfillmentActions(value),['update_tracking','deliver']);assert.deepEqual(fulfillmentActions({...value,canManage:false,role:'buyer'}),[]);assert.equal(fulfillmentStatus(null),null);});
for(const [key,value]of [['schema','unknown'],['role','admin'],['sequence',-1],['sequence',2],['state','collected'],['carrier','evil'],['tracking','https://evil.invalid'],['updatedAt',null],['paymentReady',false],['events',[]]])test(`malformed ${key} fails closed`,()=>assert.throws(()=>fulfillmentStatus({...status(),[key]:value})));
test('unfulfilled and pickup states have no carrier/tracking',()=>{const s={...status(),mode:'pickup',sequence:0,state:'unfulfilled',carrier:null,tracking:null,updatedAt:null,events:[]};assert.deepEqual(fulfillmentActions(fulfillmentStatus(s)),['ready_pickup']);assert.throws(()=>fulfillmentStatus({...s,tracking:'secret'}));});
for(const extra of [{ownerId:owner},{paid:true},{force:true},{mode:'shipping'},{expectedSequence:-1},{expectedSequence:1.5},{requestId:'bad'},{action:'refund'},{carrier:'__proto__'},{tracking:'<script>'},{tracking:' x '}])test(`command rejects ${JSON.stringify(extra)}`,()=>assert.throws(()=>fulfillmentCommand({...command(),...extra})));
test('non-shipping actions reject hidden tracking inputs',()=>{assert.throws(()=>fulfillmentCommand({...command(),action:'deliver'}));assert.equal(fulfillmentCommand({...command(),action:'deliver',carrier:null,tracking:null}).action,'deliver');});
test('service derives actor from trusted Auth argument, uses governed RPC and returns a narrow receipt',async()=>{let call;const service=fulfillmentService({rpc:async(name,args)=>{call=[name,args];return {data:{...receipt(),secret:'PRIVATE'},error:null};}});const result=await service(command(),owner);assert.equal(call[0],'vendor_order_fulfillment_record_v1');assert.equal(call[1].p_actor_id,owner);assert.equal(call[1].p_expected_sequence,0);assert.doesNotMatch(JSON.stringify(result),/PRIVATE|secret/);});
test('service rejects wrong receipt identity and redacts raw database failures',async()=>{await assert.rejects(fulfillmentService({rpc:async()=>({data:{...receipt(),requestId:owner},error:null})})(command(),owner));await assert.rejects(fulfillmentService({rpc:async()=>({error:{message:'PRIVATE DATABASE ERROR'}})})(command(),owner),/order_fulfillment_unavailable/);});
function http(){const f={calls:[],actor:owner,enabled:true};f.handler=fulfillmentHandler({origin:()=> 'http://127.0.0.1:22440',authenticate:async()=>f.actor,service:()=>{f.calls.push('service');return f.enabled?async(c,actor)=>{f.calls.push([c,actor]);return receipt();}:null;}});f.post=(body=command(),origin='http://127.0.0.1:22440',suffix='')=>f.handler(new Request('http://127.0.0.1:22440/api/vendor-orders/fulfillment'+suffix,{method:'POST',headers:{origin},body:typeof body==='string'?body:JSON.stringify(body)}));return f;}
test('HTTP rejects foreign origin, unauthenticated identity, forged fields and oversized bodies before privileged construction',async()=>{const f=http();assert.equal((await f.post(command(),'https://evil.invalid')).status,403);f.actor=null;assert.equal((await f.post()).status,401);f.actor=owner;assert.equal((await f.post({...command(),actorId:owner})).status,400);assert.equal((await f.post('x'.repeat(2049))).status,413);assert.equal((await f.post(command(),undefined,'?force=true')).status,400);assert.deepEqual(f.calls,[]);});
test('HTTP successful update is private/no-store and carries authenticated actor',async()=>{const f=http(),r=await f.post();assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'private, no-store');assert.equal(f.calls[1][1],owner);});
test('HTTP maps conflicting updates to reload guidance and other failures to safe retry',async()=>{for(const code of ['order_fulfillment_conflict','PRIVATE PROVIDER ERROR']){const h=fulfillmentHandler({origin:()=> 'http://local',authenticate:async()=>owner,service:()=>async()=>{throw Error(code);}});const r=await h(new Request('http://local/api',{method:'POST',headers:{origin:'http://local'},body:JSON.stringify(command())}));assert.equal(r.status,code==='order_fulfillment_conflict'?409:503);assert.doesNotMatch(await r.text(),/PRIVATE|PROVIDER/);}});
test('default-off configuration cannot activate hosted fulfillment through a client flag',()=>{assert.equal(fulfillmentEnabled({},'http://127.0.0.1:22440'),false);const env={GROOKAI_VENDOR_ORDER_FULFILLMENT_ENABLED:'true',NEXT_PUBLIC_STOREFRONT_LOCAL_TEST:'true',NEXT_PUBLIC_COLLECTOR_STAGING:'true',GROOKAI_DISABLE_TELEMETRY:'1',SUPABASE_URL:'http://127.0.0.1:15439'};assert.equal(fulfillmentEnabled(env,'http://127.0.0.1:22440'),true);assert.throws(()=>fulfillmentEnabled({...env,VERCEL:'1'},'http://127.0.0.1:22440'));assert.throws(()=>fulfillmentEnabled(env,'https://grookaivault.com'));});
