import test from 'node:test';import assert from 'node:assert/strict';
import {buildVendorRecoveryPlan,applyVendorRecoveryPlan} from '../../apps/web/src/lib/billing/vendorBillingRecovery.ts';
import {readVendorCheckoutEvidence} from '../../apps/web/src/lib/billing/vendorStripeEnrollment.ts';
import {readBillingOperatorOptions,readRecoveryRequest} from '../../backend/billing/vendor_billing_closeout_config_v1.mjs';
const owner='a7000000-0000-4000-8000-000000000001',attempt='b7000000-0000-4000-8000-000000000001';
function setup(kind='customer'){
 const now=Math.floor(Date.now()/1000),created=now-172800,calls=[];
 const config={scope:{accountId:'acct_fixture',livemode:false},catalog:{store_app:'price_app',store_web:'price_web'}};
 const context={ownerId:owner,ticketHash:'a'.repeat(64),environment:'http://127.0.0.1:17621',implementationHash:'b'.repeat(64),createdAt:now,kind,resourceId:kind==='customer'?'cus_fixture':'cs_test_fixture'};
 const account={owner_id:owner,stripe_account_id:'acct_fixture',livemode:false,customer_id:kind==='customer'?null:'cus_fixture',customer_attempt_id:attempt,
  customer_attempt_created_at:new Date(created*1000).toISOString(),customer_creation_started_at:new Date(created*1000).toISOString(),closeout_id:owner,closeout_requested_at:new Date(now*1000).toISOString(),current_subscription_id:null};
 const checkout=kind==='checkout'?{id:attempt,owner_id:owner,customer_id:'cus_fixture',requested_plan:'store_web',created_at:new Date(created*1000).toISOString(),session_id:null,subscription_id:null,state:'recovery'}:null;
 const customer={id:'cus_fixture',object:'customer',livemode:false,created:created+30,metadata:{grookai_billing_version:'vendor-billing-v1',grookai_billing_customer_attempt:attempt}};
 const session={id:'cs_test_fixture',object:'checkout.session',created:created+30,mode:'subscription',livemode:false,customer:'cus_fixture',client_reference_id:attempt,recovered_from:null,status:'open',subscription:null,url:'https://checkout.stripe.com/c/pay/fixture'};
 const price={id:'price_web',livemode:false,currency:'usd',unit_amount:5000,type:'recurring',recurring:{interval:'month',interval_count:1,usage_type:'licensed'}};
 let claimHook=()=>{};
 const stripe={accounts:{async retrieve(){calls.push('provider_account_read');return {id:'acct_fixture'};}},customers:{async retrieve(){calls.push('provider_customer_read');return structuredClone(customer);}},checkout:{sessions:{async retrieve(){calls.push('provider_checkout_read');return structuredClone(session);},async listLineItems(){return {has_more:false,data:[{quantity:1,price}]};}}}};
 const admin={auth:{admin:{async getUserById(){return {data:{user:{id:owner}},error:null};}}},from(table){const query={select(){return query;},eq(){return query;},in(){return query;},async maybeSingle(){return {data:structuredClone(table==='vendor_billing_accounts'?account:checkout),error:null};},async single(){return query.maybeSingle();}};return query;},
  async rpc(name,p){calls.push(name);switch(name){case 'vendor_billing_claim_v1':claimHook();return {data:{...account,lease_token:p.p_claim_token,lease_fence:1},error:null};
   case 'vendor_billing_release_v1':return {data:null,error:null};case 'vendor_billing_bind_customer_v1':account.customer_id=p.p_customer_id;return {data:structuredClone(account),error:null};
   case 'vendor_billing_bind_checkout_v1':Object.assign(checkout,{session_id:p.p_session_id,state:p.p_state,subscription_id:p.p_subscription_id});return {data:structuredClone(checkout),error:null};default:throw new Error('Unexpected mutation '+name);}}};
 const build=()=>buildVendorRecoveryPlan(admin,stripe,config,context);
 const apply=p=>applyVendorRecoveryPlan(admin,stripe,config,context,p,p.planSha256,p.planSha256);
 return {now,created,context,config,account,checkout,customer,session,price,calls,admin,stripe,build,apply,onClaim:fn=>{claimHook=fn;}};
}
test('customer recovery after idempotency retention binds original resource without clearing closure',async()=>{const x=setup(),p=await x.build();assert.equal(p.decision,'bind_customer');assert.equal(x.account.customer_id,null);assert.ok(!JSON.stringify(p).includes('cus_fixture'));assert.ok(!JSON.stringify(p).includes(owner));const r=await x.apply(p);assert.equal(r.state,'bound');assert.equal(r.grantsAccess,false);assert.equal(r.changesProvider,false);assert.equal(x.account.customer_id,'cus_fixture');assert.equal(x.account.closeout_id,owner);assert.deepEqual(x.calls.filter(x=>x.startsWith('vendor_')),['vendor_billing_claim_v1','vendor_billing_bind_customer_v1','vendor_billing_release_v1']);});
test('newly reviewed already-bound recovery performs no write',async()=>{const x=setup();await x.apply(await x.build());x.calls.length=0;const p=await x.build();assert.equal(p.decision,'already_bound');assert.equal((await x.apply(p)).state,'already_bound');assert.ok(!x.calls.some(c=>c.startsWith('vendor_')));});
test('stale pre-bind plan cannot replay as a different decision',async()=>{const x=setup(),p=await x.build();await x.apply(p);await assert.rejects(x.apply(p),e=>e.code==='billing_recovery_plan_changed');});
for(const [name,change,code] of [
 ['scope',x=>{x.account.livemode=true;},'billing_recovery_scope_mismatch'],
 ['different existing customer',x=>{x.account.customer_id='cus_other';},'billing_customer_already_bound'],
 ['no creation intent',x=>{x.account.customer_creation_started_at=null;},'billing_recovery_attempt_unverified'],
 ['missing marker',x=>{delete x.customer.metadata.grookai_billing_customer_attempt;},'billing_customer_recovery_unverified'],
 ['wrong marker',x=>{x.customer.metadata.grookai_billing_customer_attempt=owner;},'billing_customer_recovery_unverified'],
 ['too-late provider creation',x=>{x.customer.created=x.now;},'billing_customer_recovery_unverified'],
])test(`customer recovery rejects ${name}`,async()=>{const x=setup();change(x);await assert.rejects(x.build(),e=>e.code===code);assert.ok(!x.calls.some(c=>c.startsWith('vendor_')));});
test('state change while acquiring lease prevents binding and releases',async()=>{const x=setup(),p=await x.build();x.onClaim(()=>{x.account.closeout_id=null;});await assert.rejects(x.apply(p),e=>e.code==='billing_recovery_plan_changed');assert.equal(x.account.customer_id,null);assert.equal(x.calls.at(-1),'vendor_billing_release_v1');});
for(const status of ['open','expired','complete'])test(`checkout recovery binds ${status} without paid projection`,async()=>{const x=setup('checkout');x.session.status=status;x.session.subscription=status==='complete'?'sub_fixture':null;if(status!=='open')x.session.url=null;const p=await x.build();assert.equal(p.checkoutState,status);const r=await x.apply(p);assert.equal(r.grantsAccess,false);assert.equal(x.checkout.session_id,'cs_test_fixture');assert.equal(x.checkout.state,status==='complete'?'completed':status);assert.equal(x.account.current_subscription_id,null);assert.ok(!x.calls.includes('vendor_billing_commit_projection_v1'));});
for(const [name,change] of [
 ['wrong attempt',x=>{x.session.client_reference_id=owner;}],['wrong package',x=>{x.price.unit_amount=3000;}],
 ['wrong customer',x=>{x.session.customer='cus_other';}],['changed session',x=>{x.checkout.session_id='cs_test_other';}],
 ['created too early',x=>{x.session.created=x.created-1;}],['created too late',x=>{x.session.created=x.created+86400;}],
 ['missing creation evidence',x=>{delete x.session.created;}],
])test(`checkout recovery rejects ${name}`,async()=>{const x=setup('checkout');change(x);await assert.rejects(x.build());assert.ok(!x.calls.some(c=>c.startsWith('vendor_')));});
test('checkout completion between review and apply requires a new plan',async()=>{const x=setup('checkout'),p=await x.build();x.session.status='complete';x.session.subscription='sub_fixture';await assert.rejects(x.apply(p),e=>e.code==='billing_recovery_plan_changed');assert.equal(x.checkout.session_id,null);});
test('ordinary enrollment behavior does not require recovery-only timestamp',async()=>{const x=setup('checkout');delete x.session.created;const e=await readVendorCheckoutEvidence(x.stripe,x.config,{attemptId:attempt,customerId:'cus_fixture',sessionId:'cs_test_fixture',plan:'store_web'});assert.equal(e.state,'open');});
test('tampered recovery plan and missing acknowledgement do no reads',async()=>{const x=setup(),p=await x.build();x.calls.length=0;await assert.rejects(applyVendorRecoveryPlan(x.admin,x.stripe,x.config,x.context,p,p.planSha256,''),e=>e.code==='billing_recovery_ack_required');p.grantsAccess=true;await assert.rejects(x.apply(p),e=>e.code==='billing_recovery_ack_required');assert.deepEqual(x.calls,[]);});
test('recovery expires after 15 minutes and rejects wrong environment',async()=>{const x=setup();x.context.createdAt-=900;await assert.rejects(x.build(),e=>e.code==='billing_recovery_plan_invalid');x.context.createdAt=x.now;x.context.environment='https://other.invalid';await assert.rejects(x.build(),e=>e.code==='billing_recovery_environment_mismatch');});
test('private recovery request allows exact known resource only',()=>{for(const kind of ['customer','checkout'])assert.equal(readRecoveryRequest({ownerId:owner,requestTicket:'private-ticket',kind,resourceId:kind==='customer'?'cus_fixture':'cs_test_fixture'}).kind,kind);for(const value of [{ownerId:owner,requestTicket:'ticket',kind:'customer',resourceId:'cs_test_wrong'},{ownerId:owner,requestTicket:'ticket',kind:'customer',resourceId:'cus_fixture',force:true}])assert.throws(()=>readRecoveryRequest(value));});
test('recovery requires its own enablement and matching acknowledgement',()=>{const hash='a'.repeat(64),env={SUPABASE_URL:'http://127.0.0.1:17621',SUPABASE_SECRET_KEY:'synthetic',STRIPE_ACCOUNT_ID:'acct_fixture',STRIPE_BILLING_MODE:'test'},args=['--request-file=private.json','--out-dir=private'];assert.equal(readBillingOperatorOptions(env,args,'RECOVERY').apply,false);const apply=[...args,'--apply','--plan-file=plan.json','--expected-plan-sha256='+hash];assert.throws(()=>readBillingOperatorOptions({...env,GROOKAI_VENDOR_BILLING_ENABLED:'true',GROOKAI_VENDOR_BILLING_CLOSEOUT_ENABLED:'true',GROOKAI_VENDOR_BILLING_CLOSEOUT_ACK:hash},apply,'RECOVERY'));assert.equal(readBillingOperatorOptions({...env,GROOKAI_VENDOR_BILLING_ENABLED:'true',GROOKAI_VENDOR_BILLING_RECOVERY_ENABLED:'true',GROOKAI_VENDOR_BILLING_RECOVERY_ACK:hash},apply,'RECOVERY').apply,true);});
