import test from 'node:test';import assert from 'node:assert/strict';
import {financialFixture,paths} from '../helpers/vendorSellerFinancialFixture.mjs';
import {readSellerFinancialReview,sellerReviewHash} from '../../apps/web/src/lib/payments/vendorSellerFinancialReview.ts';
const run=f=>readSellerFinancialReview(f.stripe,f.config,f.binding,f.binding.ownerId,()=>f.now);
test('empty complete scoped inventory is never financial deletion clearance',async()=>{const f=financialFixture(),r=await run(f);assert.equal(r.deletionPermitted,false);assert.equal(r.completeLists,true);assert.equal(r.nonzeroBalance,false);assert.deepEqual(r.reviewReasons,['future_claims_require_retention','retained_order_ledger_required']);assert.equal(f.calls.length,11);assert.ok(f.calls.filter(c=>Object.values(paths).includes(c.path)).every(c=>c.scope===f.binding.connectedAccountId));});
for(const [name,edit] of [
 ['stored mode',f=>f.binding.livemode=true],['platform identity',f=>f.platform.id='acct_wrong'],['platform mode',f=>f.platformBalance.livemode=true],
 ['seller identity',f=>f.account.id='acct_wrong'],['controller',f=>f.account.controller.losses.payments='application'],
 ['seller mode',f=>f.balance.livemode=true],['missing available',f=>delete f.balance.available],['missing pending',f=>delete f.balance.pending],
 ['bad money',f=>f.balance.available[0].amount=NaN],['fractional money',f=>f.balance.available[0].amount=0.1],
 ['invalid currency',f=>f.balance.available[0].currency='US'],['duplicate currency',f=>f.balance.available.push({...f.balance.available[0]})],
 ['bad source balance',f=>f.balance.available[0].source_types.card='0'],['missing nested issuing',f=>f.balance.issuing={}],
 ['missing prefunding',f=>f.balance.refund_and_dispute_prefunding={}],
])test(`financial read rejects ${name}`,async()=>{const f=financialFixture();edit(f);await assert.rejects(run(f));});
for(const [name,edit] of [
 ['positive',f=>f.balance.available[0].amount=1],['negative',f=>f.balance.available[0].amount=-1],
 ['pending',f=>f.balance.pending=[{currency:'eur',amount:5}]],['reserve',f=>f.balance.connect_reserved=[{currency:'usd',amount:1}]],
 ['source offset',f=>f.balance.available[0].source_types={card:10,bank_account:-10}],
 ['issuing',f=>f.balance.issuing={available:[{currency:'usd',amount:1}]}],
 ['prefunding',f=>f.balance.refund_and_dispute_prefunding={available:[],pending:[{currency:'usd',amount:1}]}],
 ['instant',f=>f.balance.instant_available=[{currency:'usd',amount:1}]],
])test(`review retains ${name} exposure`,async()=>{const f=financialFixture();edit(f);const r=await run(f);assert.equal(r.nonzeroBalance,true);assert.ok(r.reviewReasons.includes('nonzero_balance'));assert.equal(r.deletionPermitted,false);});
for(const [kind,status] of [['paymentIntents','processing'],['paymentIntents','requires_capture'],['paymentIntents','requires_payment_method'],['refunds','pending'],['refunds','requires_action'],['refunds','failed'],['disputes','needs_response'],['disputes','warning_under_review'],['payouts','in_transit'],['payouts','pending'],['payouts','failed'],['checkouts','open'],['charges','pending']])test(`${kind} ${status} needs review`,async()=>{const f=financialFixture();f.pages[kind][0].data=[f.row(kind,{status})];const r=await run(f);assert.equal(r.counts[kind].needsReview,1);});
test('completed unpaid checkout and uncaptured or disputed charges remain obligations',async()=>{const f=financialFixture();f.pages.checkouts[0].data=[f.row('checkouts',{payment_status:'unpaid'})];f.pages.charges[0].data=[f.row('charges',{captured:false}),f.row('charges',{id:'ch_other',disputed:true})];const r=await run(f);assert.equal(r.counts.checkouts.needsReview,1);assert.equal(r.counts.charges.needsReview,2);});
for(const kind of Object.keys(paths))for(const [name,edit] of [
 ['wrong object',r=>r.object='customer'],['unknown status',r=>r.status='new_status'],['future creation',r=>r.created++],['missing time',r=>delete r.created],['invalid id',r=>r.id='other'],
])test(`${kind} rejects ${name}`,async()=>{const f=financialFixture(),r=f.row(kind);edit(r);f.pages[kind][0].data=[r];await assert.rejects(run(f));});
for(const kind of Object.keys(paths).filter(k=>k!=='refunds'))test(`${kind} rejects wrong live mode`,async()=>{const f=financialFixture();f.pages[kind][0].data=[f.row(kind,{livemode:true})];await assert.rejects(run(f));});
test('refund has no invented livemode requirement and needs a charge/payment reference',async()=>{const f=financialFixture(),r=f.row('refunds');delete r.livemode;f.pages.refunds[0].data=[r];assert.equal((await run(f)).counts.refunds.observed,1);r.charge=null;r.payment_intent=null;await assert.rejects(run(f));});
test('actual SDK follows bounded cursor pagination',async()=>{const f=financialFixture();f.pages.refunds=[{object:'list',data:[f.row('refunds',{id:'re_first'})],has_more:true},{object:'list',data:[f.row('refunds',{id:'re_second',status:'pending'})],has_more:false}];const r=await run(f);assert.deepEqual(r.counts.refunds,{observed:2,needsReview:1,complete:true});assert.equal(f.calls.find(c=>c.query.starting_after)?.query.starting_after,'re_first');});
test('fifth page with more rows is explicit incompleteness',async()=>{const f=financialFixture();f.pages.payouts=Array.from({length:5},(_,i)=>({object:'list',data:[f.row('payouts',{id:'po_page'+i})],has_more:true}));const r=await run(f);assert.equal(r.completeLists,false);assert.equal(r.counts.payouts.observed,5);assert.ok(r.reviewReasons.includes('payouts_inventory_incomplete'));assert.equal(f.calls.filter(c=>c.path===paths.payouts).length,5);});
for(const [name,page] of [['missing more',{object:'list',data:[]}],['empty has_more',{object:'list',data:[],has_more:true}],['wrong object',{object:'account',data:[],has_more:false}],['oversized',{object:'list',data:Array(101).fill({}),has_more:false}]])test(`malformed list ${name}`,async()=>{const f=financialFixture();f.pages.charges=[page];await assert.rejects(run(f));});
test('duplicate resource across pages is not a complete inventory',async()=>{const f=financialFixture(),row=f.row('refunds');f.pages.refunds=[{object:'list',data:[row],has_more:true},{object:'list',data:[row],has_more:false}];await assert.rejects(run(f));});
test('balance change during review is retained as a review reason',async()=>{const f=financialFixture();f.balances=[f.balance,{...f.balance,available:[{currency:'usd',amount:1}]}];const r=await run(f);assert.ok(r.reviewReasons.includes('balance_changed_during_review'));});
for(const elapsed of [-1,60,61])test(`review deadline ${elapsed} rejects stale evidence`,async()=>{const f=financialFixture();let calls=0;await assert.rejects(readSellerFinancialReview(f.stripe,f.config,f.binding,f.binding.ownerId,()=>f.now+(calls++?elapsed:0)));});
test('provider error is sanitized and no partial success leaks',async()=>{const f=financialFixture();f.fail=paths.refunds;await assert.rejects(run(f),e=>e.code==='seller_financial_provider_unavailable'&&!e.cause);});
test('raw provider PII and financial objects never appear in summary',async()=>{const f=financialFixture();f.pages.refunds[0].data=[f.row('refunds',{description:'PRIVATE BUYER',instructions_email:'private@example.invalid',metadata:{private:'secret'}})];const r=await run(f),text=JSON.stringify(r);for(const s of ['PRIVATE','example.invalid','re_fixture','acct_','11111111','secret'])assert.equal(text.includes(s),false);assert.match(r.evidenceHash,/^[0-9a-f]{64}$/);});
test('evidence hash binds financial changes but ignores provider PII and key ordering',async()=>{const f=financialFixture();f.pages.charges[0].data=[f.row('charges')];const first=(await run(f)).evidenceHash;f.pages.charges[0].data[0].description='PRIVATE';assert.equal((await run(f)).evidenceHash,first);f.pages.charges[0].data[0].amount_refunded=1;assert.notEqual((await run(f)).evidenceHash,first);assert.equal(sellerReviewHash({a:1,b:2}),sellerReviewHash({b:2,a:1}));});
test('capturable and received money bind the financial hash independently of status',async()=>{const f=financialFixture(),row=f.row('paymentIntents');f.pages.paymentIntents[0].data=[row];const first=(await run(f)).evidenceHash;row.amount_received=90;assert.notEqual((await run(f)).evidenceHash,first);row.amount_capturable=10;assert.equal((await run(f)).counts.paymentIntents.needsReview,1);delete row.amount_received;await assert.rejects(run(f));});
test('checkout amount changes require a different plan; missing payment totals need review',async()=>{const f=financialFixture(),row=f.row('checkouts');f.pages.checkouts[0].data=[row];const first=(await run(f)).evidenceHash;row.amount_total=200;assert.notEqual((await run(f)).evidenceHash,first);row.amount_total=null;assert.equal((await run(f)).counts.checkouts.needsReview,1);row.mode='setup';row.currency=null;assert.equal((await run(f)).counts.checkouts.needsReview,0);});
