import test from 'node:test';import assert from 'node:assert/strict';
import {createOrderQueueService,createOrderQueueRepository,projectOrderQueueStatus,orderQueueAlerts} from '../../apps/web/src/lib/payments/vendorOrderQueue.ts';
import {createVendorOrderHandlers} from '../../apps/web/src/lib/payments/vendorOrderHttp.ts';
import {readOrderRuntimeConfig} from '../../apps/web/src/lib/payments/vendorOrderRuntimePolicy.ts';
const id='11111111-1111-4111-8111-111111111111',token='22222222-2222-4222-8222-222222222222',now=Date.parse('2026-09-20T06:00:00Z');
const iso=delta=>new Date(now+delta).toISOString();
function fixture(){const f={calls:[],claim:{orderId:id,token,fence:1,lane:'bound',leaseExpiresAt:iso(180000)},scan:{scanned:1,complete:true,completedSweeps:1},result:{needsReview:false},discovery:{orderId:id,state:'reconciled'}};
 f.repo={seed:async()=>{f.calls.push('seed');return f.scan;},claim:async t=>{assert.equal(t,token);f.calls.push('claim');return f.claim;},finish:async(c,result)=>{f.calls.push(['finish',c,result]);return {orderId:id,fence:1,result,nextRunAt:iso(60000)};},status:async()=>status()};
 f.service=()=>createOrderQueueService({repo:f.repo,enabled:true,token:()=>token,now:()=>now,reconcile:async x=>{f.calls.push(['reconcile',x]);if(f.error)throw Error('PRIVATE PROVIDER ERROR');return f.result;},discover:async x=>{f.calls.push(['discover',x]);if(f.error)throw Error('PRIVATE PROVIDER ERROR');return f.discovery;}});return f;}
function status(){return {enabled:true,checkedAt:iso(0),lastScanAt:iso(-1000),lastCompletedSweepAt:iso(-1000),lastClaimedAt:iso(-1000),lastFinishedAt:iso(-1000),completedSweeps:1,total:1,due:0,leased:0,expiredLeases:0,unresolved:0,abandonedClaims:0,oldestDueAt:null,attention:[]};}
test('queue defaults off without storage or provider work',async()=>{const f=fixture();await assert.rejects(createOrderQueueService({repo:f.repo}).tick(),/order_queue_disabled/);assert.deepEqual(f.calls,[]);});
test('persisted scan precedes one claim, provider verification and durable completion',async()=>{const f=fixture(),r=await f.service().tick();assert.equal(r.processed,1);assert.deepEqual(f.calls.slice(0,3),['seed','claim',['reconcile',id]]);assert.equal(f.calls[3][2],'verified');});
test('an incomplete scan still services due work without resetting or taking a caller cursor',async()=>{const f=fixture();f.scan.complete=false;const r=await f.service().tick();assert.equal(r.scan.complete,false);assert.equal(r.processed,1);});
test('no due job makes no provider request',async()=>{const f=fixture();f.claim=null;assert.equal((await f.service().tick()).processed,0);assert.deepEqual(f.calls,['seed','claim']);});
test('failed seed does not advance to claim',async()=>{const f=fixture();f.repo.seed=async()=>{throw Error('storage');};await assert.rejects(f.service().tick());assert.deepEqual(f.calls,[]);});
for(const [name,change] of [['foreign token',c=>c.token=id],['invalid order',c=>c.orderId='foreign'],['stale deadline',c=>c.leaseExpiresAt=iso(-1)],['bad fence',c=>c.fence=0],['wrong lane',c=>c.lane='checkout']])test(`invalid lease ${name} never invokes provider or acknowledges work`,async()=>{const f=fixture();change(f.claim);await assert.rejects(f.service().tick());assert.deepEqual(f.calls,['seed','claim']);});
for(const lane of ['bound','discovery'])test(`${lane} provider failure persists only a fixed retry outcome`,async()=>{const f=fixture();f.claim.lane=lane;f.error=true;const r=await f.service().tick();assert.equal(r.receipt.result,'retry');assert.doesNotMatch(JSON.stringify(r),/PRIVATE/);});
test('review-needed evidence is retained as attention, not marked healthy',async()=>{const f=fixture();f.result.needsReview=true;assert.equal((await f.service().tick()).receipt.result,'needs_review');});
for(const reason of ['not_found','conflicting_sessions','scan_limit'])test(`discovery ${reason} persists an unresolved retry`,async()=>{const f=fixture();f.claim.lane='discovery';f.discovery={orderId:id,state:'unresolved',reason};assert.equal((await f.service().tick()).receipt.result,reason);assert.equal(f.calls.some(c=>Array.isArray(c)&&c[0]==='reconcile'),false);});
test('foreign discovery identity cannot acknowledge verification',async()=>{const f=fixture();f.claim.lane='discovery';f.discovery.orderId=token;assert.equal((await f.service().tick()).receipt.result,'retry');});
test('failed finish stays failed even after successful verification',async()=>{const f=fixture();f.repo.finish=async()=>{throw Error('receipt_lost');};await assert.rejects(f.service().tick(),/receipt_lost/);});
test('stale or wrong receipt is never returned as success',async()=>{const f=fixture();f.repo.finish=async()=>({orderId:token,fence:1,result:'verified',nextRunAt:iso(1)});await assert.rejects(f.service().tick(),/order_queue_invalid/);});
test('repository uses only scoped governed RPCs and omits provider/account data from client input',async()=>{const calls=[],repo=createOrderQueueRepository({rpc:async(name,args)=>{calls.push([name,args]);return {data:null,error:null};}},{scope:{accountId:'acct_platform',livemode:false}});await repo.seed();await repo.claim(token);await repo.finish({orderId:id,token,fence:4},'retry');await repo.status();assert.deepEqual(calls.map(c=>c[0]),['vendor_order_reconcile_seed_v1','vendor_order_reconcile_claim_v1','vendor_order_reconcile_finish_v1','vendor_order_reconcile_status_v1']);for(const [,args]of calls){assert.equal(args.p_platform,'acct_platform');assert.equal(args.p_live,false);}assert.equal(calls[0][1].p_limit,100);assert.equal(calls[2][1].p_fence,4);});
test('repository redacts storage errors',async()=>{const repo=createOrderQueueRepository({rpc:async()=>({error:{message:'PRIVATE SQL'}})},{scope:{accountId:'acct_platform',livemode:false}});await assert.rejects(repo.status(),/order_queue_storage_unavailable/);});
test('monitoring is available without enabling work',async()=>{const f=fixture();assert.deepEqual(await createOrderQueueService({repo:f.repo}).status(),status());});
test('healthy telemetry has no alerts; stopped/overdue/expired/unresolved work is visible',()=>{assert.deepEqual(orderQueueAlerts(status()),[]);const s={...status(),enabled:false,lastScanAt:null,lastCompletedSweepAt:null,oldestDueAt:iso(-16*60000),expiredLeases:1,unresolved:1};assert.deepEqual(orderQueueAlerts(s),['disabled','not_started','sweep_stale','work_overdue','expired_leases','orders_need_attention']);assert.deepEqual(orderQueueAlerts({...status(),lastScanAt:iso(-16*60000)}),['scan_stale']);});
test('health DTO strips unknown fields and caps attention details',()=>{const s=status();s.PRIVATE='secret';s.unresolved=1;s.attention=[{orderId:id,result:'retry',failures:1,nextRunAt:iso(100),leaseExpiresAt:null,PRIVATE:'secret'}];assert.doesNotMatch(JSON.stringify(projectOrderQueueStatus(s)),/PRIVATE|secret/);assert.throws(()=>projectOrderQueueStatus({...s,attention:Array(26).fill(s.attention[0])}));assert.throws(()=>projectOrderQueueStatus({...s,total:-1}));});
const operator='ab'.repeat(32);
function http(){const f={calls:[],status:status(),tick:{processed:1,scan:{scanned:1,complete:true,completedSweeps:1},receipt:{orderId:id,fence:1,result:'verified',nextRunAt:iso(10)}}};f.handlers=createVendorOrderHandlers({authenticate:async()=>id,origin:()=> 'http://127.0.0.1:22040',reconcileToken:()=>operator,runtime:lane=>{f.calls.push(lane);return {queueTick:async()=>f.tick,queueStatus:async()=>f.status};}});f.request=(body,headers={authorization:`Bearer ${operator}`},suffix='')=>f.handlers.queue(new Request('http://127.0.0.1:22040/api/vendor-orders/queue'+suffix,{method:'POST',headers,body:typeof body==='string'?body:JSON.stringify(body)}));return f;}
for(const headers of [{},{cookie:'signed-buyer'},{authorization:'Bearer forged'},{'stripe-signature':operator}])test(`queue denies non-operator ${JSON.stringify(headers)}`,async()=>{const f=http();assert.equal((await f.request({action:'tick'},headers)).status,401);assert.deepEqual(f.calls,[]);});
for(const body of [{action:'tick',orderId:id},{action:'tick',limit:999},{action:'tick',after:id},{action:'release'},{action:'status',account:'acct_foreign'},[],null,'{bad'])test(`queue body rejects ${JSON.stringify(body)}`,async()=>{const f=http();assert.equal((await f.request(body)).status,400);assert.deepEqual(f.calls,[]);});
test('queue tick and monitoring use separate flags and narrow private output',async()=>{const f=http();f.tick.PRIVATE='secret';f.tick.receipt.PRIVATE='secret';let r=await f.request({action:'tick'});assert.equal(r.status,200);assert.doesNotMatch(await r.text(),/PRIVATE|secret/);assert.equal(r.headers.get('cache-control'),'private, no-store');f.status.enabled=false;r=await f.request({action:'status'});assert.equal(r.status,503);assert.deepEqual((await r.json()).alerts,['disabled']);assert.deepEqual(f.calls,['queue','reconcile']);});
test('persisted unresolved result returns retryable status',async()=>{const f=http();f.tick.receipt.result='not_found';const r=await f.request({action:'tick'});assert.equal(r.status,503);assert.equal((await r.json()).receipt.result,'not_found');});
test('GET, URL parameters and oversized body cannot start work',async()=>{const f=http();assert.equal((await f.handlers.queue(new Request('http://127.0.0.1:22040/api/vendor-orders/queue'))).status,405);assert.equal((await f.request({action:'tick'},{authorization:`Bearer ${operator}`},'?token=x')).status,400);assert.equal((await f.request('x'.repeat(513))).status,413);assert.deepEqual(f.calls,[]);});
test('queue enablement is independent and defaults off',()=>{assert.equal(readOrderRuntimeConfig({GROOKAI_VENDOR_ORDER_RECONCILIATION_ENABLED:'true'},'queue','http://127.0.0.1:22040'),null);assert.throws(()=>readOrderRuntimeConfig({GROOKAI_VENDOR_ORDER_QUEUE_ENABLED:'true'},'queue','http://127.0.0.1:22040'));});
