import test from 'node:test';import assert from 'node:assert/strict';
import {cancellationEnabled,cancellationStatus,cancellationService,cancellationHandler} from '../../apps/web/src/lib/orders/orderCancellation.ts';
const orderId='11111111-1111-4111-8111-111111111111',buyer='22222222-2222-4222-8222-222222222222',origin='http://127.0.0.1:21240',at='2026-09-20T03:00:00.000Z';
const env=()=>({GROOKAI_VENDOR_ORDER_CANCELLATION_ENABLED:'true',NEXT_PUBLIC_STOREFRONT_LOCAL_TEST:'true',NEXT_PUBLIC_COLLECTOR_STAGING:'true',GROOKAI_DISABLE_TELEMETRY:'1',SUPABASE_URL:'http://127.0.0.1:15439'});
test('cancellation is independently disabled; retained cancellation needs no package or provider config',()=>{assert.equal(cancellationEnabled({},origin),false);assert.equal(cancellationEnabled(env(),origin),true);assert.equal(cancellationEnabled({...env(),GROOKAI_VENDOR_ORDER_CHECKOUT_ENABLED:'false',GROOKAI_VENDOR_ORDER_ACQUISITION_ENABLED:'false'},origin),true);});
for(const [k,v] of [['NEXT_PUBLIC_STOREFRONT_LOCAL_TEST','false'],['NEXT_PUBLIC_COLLECTOR_STAGING','false'],['GROOKAI_DISABLE_TELEMETRY','0'],['SUPABASE_URL','https://remote.invalid'],['VERCEL','1'],['VERCEL_ENV','preview'],['NEXT_PUBLIC_COLLECTOR_HOSTED_STAGING','true']])test('local policy rejects '+k,()=>assert.throws(()=>cancellationEnabled({...env(),[k]:v},origin)));
test('hosted and arbitrary loopback origins cannot enable cancellation',()=>{for(const u of ['https://grookaivault.com','http://127.0.0.1:20040','http://localhost:21240'])assert.throws(()=>cancellationEnabled(env(),u));});
test('participant status is narrowed and contradictory/malformed states fail closed',()=>{assert.equal(cancellationStatus(null),null);assert.deepEqual(cancellationStatus({canCancel:false,canceledAt:at,private:'SECRET'}),{canCancel:false,canceledAt:at});for(const v of [{canCancel:true,canceledAt:at},{canCancel:'true',canceledAt:null},{canCancel:false,canceledAt:'bad'},{}])assert.throws(()=>cancellationStatus(v));});
function fixture(){const f={user:buyer,calls:[],runtimeCalls:0,data:{orderId,state:'canceled',canceledAt:at},error:null,disabled:false};const admin={rpc:async(name,args)=>{f.calls.push([name,args]);return {data:f.data,error:f.error};}};f.handler=cancellationHandler({origin:()=>origin,authenticate:async()=>f.user,service:()=>{f.runtimeCalls++;return f.disabled?null:cancellationService(admin);}});return f;}
const post=(f,body={orderId},headers={origin},query='')=>f.handler(new Request(origin+'/api/vendor-orders/cancel'+query,{method:'POST',headers,body:JSON.stringify(body)}));
test('HTTP derives buyer from Auth, calls one governed RPC, narrows private result',async()=>{const f=fixture();f.data.private='SECRET';const r=await post(f);assert.equal(r.status,200);assert.deepEqual(f.calls,[['vendor_order_cancel_unstarted_v1',{p_order_id:orderId,p_buyer_id:buyer}]]);assert.deepEqual(await r.json(),{orderId,state:'canceled',canceledAt:at});assert.equal(r.headers.get('cache-control'),'private, no-store');assert.equal(r.headers.get('referrer-policy'),'no-referrer');});
for(const body of [null,[],{},'wrong',{orderId,buyerId:buyer},{orderId,paid:false},{orderId,force:true},{orderId,sessionId:'cs_test_x'},{orderId,refund:true},{orderId:'bad'}])test('rejects forged cancellation '+JSON.stringify(body),async()=>{const f=fixture();assert.equal((await post(f,body)).status,400);assert.equal(f.runtimeCalls,0);});
test('Auth, CSRF, query/body bounds and GET fail before privileged work',async()=>{const f=fixture();assert.equal((await post(f,{},{})).status,403);f.user=null;assert.equal((await post(f)).status,401);f.user=buyer;assert.equal((await post(f,{orderId},{origin},'?force=true')).status,400);assert.equal((await post(f,{orderId,large:'x'.repeat(600)})).status,413);assert.equal((await f.handler(new Request(origin))).status,405);assert.equal(f.runtimeCalls,0);});
test('off flag causes no database work',async()=>{const f=fixture();f.disabled=true;assert.equal((await post(f)).status,503);assert.equal(f.calls.length,0);});
test('started/ambiguous attempt keeps stock and returns a conflict, no fallback release',async()=>{const f=fixture();f.error={message:'order_checkout_started'};const r=await post(f);assert.equal(r.status,409);assert.match((await r.json()).error,/inventory remains held/);assert.equal(f.calls.length,1);});
test('storage details are redacted and malformed success cannot claim canceled',async()=>{const f=fixture();f.error={message:'PRIVATE_OWNER_SECRET'};const r=await post(f);assert.equal(r.status,503);assert.doesNotMatch(await r.text(),/PRIVATE_OWNER/);f.error=null;for(const data of [null,{orderId:buyer,state:'canceled',canceledAt:at},{orderId,state:'canceled',canceledAt:'bad'},{orderId,state:'paid',canceledAt:at}]){f.data=data;assert.equal((await post(f)).status,503);}});
test('response loss retries exactly the same order/buyer; never allocates a replacement',async()=>{const f=fixture();assert.equal((await post(f)).status,200);assert.equal((await post(f)).status,200);assert.deepEqual(f.calls[0],f.calls[1]);});
