import test from 'node:test';import assert from 'node:assert/strict';
import {financialFixture,paths} from '../helpers/vendorSellerFinancialFixture.mjs';
import {buildSellerCloseoutPlan,applySellerCloseoutPlan} from '../../apps/web/src/lib/payments/vendorSellerCloseout.ts';
import {sellerReviewHash} from '../../apps/web/src/lib/payments/vendorSellerFinancialReview.ts';
import {SellerError} from '../../apps/web/src/lib/payments/vendorSellerRepository.ts';
function fixture(){
 const f=financialFixture(),b=f.binding,c={ownerId:b.ownerId,closeoutId:'44444444-4444-4444-8444-444444444444',ticketHash:'a'.repeat(64),environment:'http://127.0.0.1:18821',implementationHash:'b'.repeat(64),createdAt:f.now};
 let row={id:b.id,owner_id:b.ownerId,store_id:b.storeId,stripe_account_id:b.platformAccountId,livemode:b.livemode,controller:b.controller,connected_account_id:b.connectedAccountId,
  creation_attempt_id:'55555555-5555-4555-8555-555555555555',creation_started_at:new Date(f.now*1000).toISOString(),state:'bound',closeout_id:null,lease_token:null,lease_fence:0};
 const operations=[],holds=[];const locked=l=>{if(!row||row.id!==l.id||row.lease_token!==l.token||row.lease_fence!==l.fence)throw new SellerError('seller_lease_lost');return structuredClone(row);};
 const repo={account:async()=>structuredClone(row),holds:async()=>structuredClone(holds),
  claim:async(id,token)=>{operations.push('claim');if(row.lease_token)return null;row.lease_token=token;row.lease_fence++;return structuredClone(row);},
  locked:async l=>locked(l),freeze:async(l,id)=>{locked(l);operations.push('freeze');row.state='closing';row.closeout_id=id;row.lease_fence++;row.lease_token=null;return structuredClone(row);},
  release:async l=>{locked(l);operations.push('release');row.lease_token=null;}};
 return {...f,provider:f,c,repo,operations,holds,get row(){return row;},set row(value){row=value;},plan:()=>buildSellerCloseoutPlan(repo,f.stripe,f.config,c,()=>f.now),apply:p=>applySellerCloseoutPlan(repo,f.stripe,f.config,c,p,p.planSha256,()=>f.now)};
}
test('planning is read only; reviewed apply freezes and retains every obligation',async()=>{const f=fixture();f.holds.push({id:'hold',reason:'open dispute',reference_id:'private'});const p=await f.plan();assert.equal(p.deletionPermitted,false);assert.deepEqual(p.providerActions,[]);assert.deepEqual(f.operations,[]);assert.ok(p.reviewReasons.includes('financial_hold'));assert.equal(p.decision,'freeze_and_retain');assert.deepEqual(await f.apply(p),{state:'frozen_retained',deletionPermitted:false});assert.equal(f.row.state,'closing');assert.equal(f.row.closeout_id,f.c.closeoutId);assert.equal(f.holds.length,1);assert.deepEqual(f.operations,['claim','freeze']);});
test('lost freeze response recovers by the same immutable request without provider calls',async()=>{const f=fixture(),p=await f.plan(),freeze=f.repo.freeze;f.repo.freeze=async(...a)=>{await freeze(...a);throw new Error('response lost');};await assert.rejects(f.apply(p));const before=f.calls.length;assert.equal((await f.apply(p)).state,'frozen_retained');assert.equal(f.calls.length,before);assert.equal(f.operations.filter(x=>x==='freeze').length,1);});
test('freeze is allowed with nonzero exposure but never clears balances or authorizes removal',async()=>{const f=fixture();f.provider.balance.available[0].amount=-500;const p=await f.plan();assert.ok(p.reviewReasons.includes('nonzero_balance'));assert.equal((await f.apply(p)).deletionPermitted,false);assert.equal(f.provider.balance.available[0].amount,-500);});
test('ambiguous creation freezes pending recovery without creating or searching provider accounts',async()=>{const f=fixture();f.row.connected_account_id=null;f.row.state='creating';const p=await f.plan();assert.ok(p.reviewReasons.includes('ambiguous_creation_requires_recovery'));await f.apply(p);assert.equal(f.calls.length,0);assert.equal(f.row.creation_attempt_id,'55555555-5555-4555-8555-555555555555');});
test('deauthorized account retains unavailable-provider evidence and can be locally frozen',async()=>{const f=fixture();f.row.state='deauthorized';const p=await f.plan();assert.ok(p.reviewReasons.includes('provider_access_revoked'));assert.equal(p.financial,null);await f.apply(p);assert.equal(f.calls.length,0);});
test('absent seller binding never means account deletion permission',async()=>{const f=fixture();f.row=null;const p=await f.plan();assert.equal(p.decision,'no_seller');assert.deepEqual(await f.apply(p),{state:'no_seller',deletionPermitted:false});assert.equal(f.calls.length,0);assert.deepEqual(f.operations,[]);});
for(const [name,edit] of [['wrong owner',f=>f.c.ownerId=f.binding.storeId],['wrong mode',f=>f.row.livemode=true],['wrong platform',f=>f.row.stripe_account_id='acct_other'],['wrong request',f=>{f.row.state='closing';f.row.closeout_id=f.binding.storeId;}],['expired request',f=>f.c.createdAt-=900],['future request',f=>f.c.createdAt++],['wrong environment',f=>f.c.environment='https://production.invalid'],['wrong ticket',f=>f.c.ticketHash='x'],['wrong source hash',f=>f.c.implementationHash='x']])test(`plan refuses ${name} before provider`,async()=>{const f=fixture();edit(f);await assert.rejects(f.plan());assert.equal(f.calls.length,0);});
for(const [field,value] of [['decision','no_seller'],['deletionPermitted',true],['environment','http://127.0.0.1:18421'],['implementationHash','c'.repeat(64)],['createdAt',0],['targetFingerprint','a'.repeat(64)]])test(`tampered plan ${field} cannot freeze`,async()=>{const f=fixture(),p=await f.plan();p[field]=value;await assert.rejects(f.apply(p));assert.deepEqual(f.operations,[]);});
test('even self-consistent plan hash cannot change owner/ticket/source context',async()=>{const f=fixture(),p=await f.plan();p.targetFingerprint='c'.repeat(64);const {planSha256,...payload}=p;p.planSha256=sellerReviewHash(payload);await assert.rejects(f.apply(p));assert.deepEqual(f.operations,[]);});
test('wrong expected digest cannot freeze',async()=>{const f=fixture(),p=await f.plan();await assert.rejects(applySellerCloseoutPlan(f.repo,f.stripe,f.config,f.c,p,'c'.repeat(64),()=>f.now));assert.deepEqual(f.operations,[]);});
test('financial changes after review require another plan',async()=>{const f=fixture(),p=await f.plan();f.provider.pages.refunds[0].data=[f.row?f.provider.row('refunds',{status:'pending'}):null];await assert.rejects(f.apply(p),/seller_closeout_plan_changed/);assert.deepEqual(f.operations,[]);});
test('new hold after review invalidates plan',async()=>{const f=fixture(),p=await f.plan();f.holds.push({id:'h',reason:'review',reference_id:null});await assert.rejects(f.apply(p),/seller_closeout_plan_changed/);assert.deepEqual(f.operations,[]);});
test('provider failure cannot produce a closeout result',async()=>{const f=fixture();f.provider.fail=paths.payouts;await assert.rejects(f.plan(),/seller_financial_provider_unavailable/);assert.deepEqual(f.operations,[]);});
test('incomplete pagination explicitly requires review and is never waived by freeze',async()=>{const f=fixture();f.provider.pages.payouts=Array.from({length:5},(_,i)=>({object:'list',data:[f.provider.row('payouts',{id:'po_page'+i})],has_more:true}));const p=await f.plan();assert.equal(p.financial.completeLists,false);assert.equal((await f.apply(p)).deletionPermitted,false);});
test('concurrent lease holder prevents freeze',async()=>{const f=fixture(),p=await f.plan();f.row.lease_token=f.binding.storeId;await assert.rejects(f.apply(p),/seller_busy/);assert.equal(f.row.state,'bound');});
test('provider change after claim is rechecked under lease',async()=>{const f=fixture(),p=await f.plan(),claim=f.repo.claim;f.repo.claim=async(...a)=>{const r=await claim(...a);f.provider.balance.available[0].amount=1;return r;};await assert.rejects(f.apply(p),/seller_closeout_plan_changed/);assert.deepEqual(f.operations,['claim','release']);assert.equal(f.row.state,'bound');});
test('deauthorization during scan prevents stale freeze and cannot release successor',async()=>{const f=fixture(),p=await f.plan();f.provider.onCall=()=>{if(f.row.lease_token){f.row.state='deauthorized';f.row.lease_token=f.binding.storeId;f.row.lease_fence++;}};await assert.rejects(f.apply(p));assert.equal(f.row.lease_token,f.binding.storeId);assert.equal(f.operations.includes('freeze'),false);});
test('hold added while freeze commits stays retained',async()=>{const f=fixture(),p=await f.plan(),freeze=f.repo.freeze;f.repo.freeze=async(...a)=>{f.holds.push({id:'late',reason:'dispute',reference_id:null});return freeze(...a);};await f.apply(p);assert.equal(f.holds.length,1);assert.equal(f.row.state,'closing');});
test('plan artifacts omit raw owner, seller, event and hold data',async()=>{const f=fixture();f.holds.push({id:'PRIVATE HOLD',reason:'PRIVATE REASON',reference_id:'private@example.invalid'});const text=JSON.stringify(await f.plan());for(const secret of [f.binding.ownerId,f.binding.connectedAccountId,f.c.closeoutId,'PRIVATE','example.invalid'])assert.equal(text.includes(secret),false);});
