import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../../apps/web/package.json',import.meta.url)),ts=require('typescript');
const owner='10000000-0000-4000-8000-000000000001',request='20000000-0000-4000-8000-000000000001',card='30000000-0000-4000-8000-000000000001';
const row=()=>({status:'matched',match:{card_id:card,gv_id:'GV-PK-TEST-1'},row:{quantity:3,condition:'LP',cost:4.25,notes:'fixture'}});
function fixture({user=owner,rpcError=false,reply,cacheFailure=false,eventFailure=false}={}){
 const calls=[],cache=[];let payload;const client={auth:{getUser:async()=>({data:{user:user?{id:user}:null},error:null})},rpc:async(name,args)=>{calls.push({name,args});if(name==='card_events_emit_vault_import_summary_v1'){if(eventFailure)throw Error('event down');return {data:null,error:null};}payload=args;return rpcError?{data:null,error:{code:'FETCH_ERROR'}}:{data:reply??{success:true,requestId:args.p_request_id,importedCards:3,importedEntries:1,targets:[{cardPrintId:card,expectedCount:3}]},error:null};}};
 const modules=new Map();function load(name){if(name==='server-only')return{};if(name==='next/cache')return{revalidatePath:p=>{cache.push(p);if(cacheFailure)throw Error('cache down');}};if(name==='@/lib/supabase/admin')return{createServerAdminClient:()=>client};if(name==='@/lib/supabase/server')return{createServerComponentClient:async()=>client};if(name.startsWith('node:'))return require(name);if(modules.has(name))return modules.get(name).exports;assert.ok(name.startsWith('@/'));const module={exports:{}};modules.set(name,module);const source=fs.readFileSync(new URL('../../apps/web/src/'+name.slice(2)+'.ts',import.meta.url),'utf8');const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(compiled,{module,exports:module.exports,require:load,console,TextEncoder,Map,Set});return module.exports;}
 return{load,client,calls,cache,payload:()=>payload,run:(rows=[row()],attempt={ownerId:owner,requestId:request})=>load('@/lib/import/importVaultItems').importVaultItems(rows,attempt)};
}
test('one atomic receipt-backed write retains original desired total and metadata',async()=>{const f=fixture();const r=await f.run([{...row(),importMeta:{desiredQuantity:3},row:{...row().row,quantity:2}}]);assert.equal(r.ok,true);assert.equal(r.importedCards,3);const writes=f.calls.filter(c=>c.name==='admin_import_vault_receipted_v1');assert.equal(writes.length,1);assert.equal(writes[0].args.p_user_id,owner);assert.equal(writes[0].args.p_request_id,request);assert.equal(writes[0].args.p_rows[0].desiredQuantity,3);assert.equal(writes[0].args.p_rows[0].acquisitionCost,4.25);assert.equal(writes[0].args.p_rows[0].condition,'LP');});
for(const user of [null,'different-owner'])test('reject unauthenticated or switched owner '+user,async()=>{const f=fixture({user});assert.equal((await f.run()).errorCode,'account_changed');assert.equal(f.calls.length,0);});
test('lower-level caller also requires the actual authenticated owner',async()=>{const f=fixture({user:'different'});await assert.rejects(f.load('@/lib/import/importVaultItems').importVaultItemsForUser({client:f.client,userId:owner,rows:[row()],requestId:request}),/current authenticated owner/);assert.equal(f.calls.length,0);});
test('transport failure stays uncertain and retries retain the attempt identity',async()=>{const f=fixture({rpcError:true});for(let i=0;i<2;i++)assert.equal((await f.run()).errorCode,'unconfirmed');assert.equal(new Set(f.calls.map(c=>c.args.p_request_id)).size,1);});
test('confirmed rollback is distinguishable from an uncertain response',async()=>{const f=fixture({reply:{success:false,requestId:request,error:'import_outcome_unconfirmed'}});assert.equal((await f.run()).errorCode,'failed');});
test('changed payload receipt conflict cannot become a new automatic write',async()=>{const f=fixture({reply:{success:false,requestId:request,error:'import_request_conflict'}});assert.equal((await f.run()).errorCode,'conflict');assert.equal(f.calls.length,1);});
test('saved outcome survives ancillary cache and event outages',async()=>{const f=fixture({cacheFailure:true,eventFailure:true});assert.equal((await f.run()).ok,true);});
test('same receipt and stable event identity are returned on retry',async()=>{const f=fixture();assert.deepEqual(await f.run(),await f.run());const events=f.calls.filter(c=>c.name==='card_events_emit_vault_import_summary_v1');assert.equal(events[0].args.p_import_run_id,events[1].args.p_import_run_id);});
for(const change of [r=>r.row.quantity=0,r=>r.row.quantity=1.5,r=>r.row.quantity=50001,r=>r.row.condition='BAD',r=>r.row.cost=-1,r=>r.row.cost=Infinity,r=>r.row.added='bad-date',r=>r.row.notes='x'.repeat(4001),r=>r.match.card_id='not-a-uuid',r=>r.match.gv_id=''])test('reject malformed matched input '+change.toString(),async()=>{const f=fixture(),r=row();change(r);assert.equal((await f.run([r])).errorCode,'invalid');assert.equal(f.calls.length,0);});
for(const reply of [{success:true,requestId:'wrong'}, {success:true,requestId:request,importedCards:4,importedEntries:1,targets:[{cardPrintId:card,expectedCount:3}]},{success:true,requestId:request,importedCards:3,importedEntries:1,targets:[{cardPrintId:'foreign',expectedCount:3}]},{success:true,requestId:request,importedCards:3,importedEntries:1,targets:[]}])test('malformed/mismatched receipt never reports success '+JSON.stringify(reply),async()=>{const f=fixture({reply});assert.equal((await f.run()).errorCode,'unconfirmed');});
test('saved draft cannot cross accounts or bypass validation',()=>{const f=fixture(),parse=f.load('@/lib/import/importAttempt').parseStoredImportAttempt;const draft=JSON.stringify({version:1,ownerId:owner,requestId:request,rows:[row()],fileName:'fixture.csv'});assert.ok(parse(draft,owner));assert.equal(parse(draft,'other'),null);assert.equal(parse('{bad',owner),null);});
test('an explicit modern attempt cannot silently generate a missing request identity',async()=>{const f=fixture();assert.equal((await f.run([row()],{ownerId:owner})).errorCode,'invalid');assert.equal(f.calls.length,0);});
test('cached legacy clients still receive a thrown sign-in failure',async()=>{const f=fixture({user:null});await assert.rejects(f.load('@/lib/import/importVaultItems').importVaultItems([row()]),/Sign in required/);assert.equal(f.calls.length,0);});
