// Offline exact review package. No migration/catalog apply or activation operation.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
import {assertJungleExecutionRefreshV2} from '../../backend/catalog/jungle_edition_execution_refresh_v2.mjs';import {buildJungleExecutionRows} from '../../backend/catalog/jungle_edition_catalog_execution_v1.mjs';
const base='C:/grookai_vault_operator_artifacts/jungle_edition_pricing_20261001',read=p=>JSON.parse(fs.readFileSync(p)),sha=b=>createHash('sha256').update(b).digest('hex'),git=(...a)=>execFileSync('git',a,{encoding:'utf8',windowsHide:true}).trim();assert.equal(process.argv.length,2);assert.equal(fs.realpathSync('.').replaceAll('\\','/').toLowerCase(),'c:/gv_jungle_edition_20261001');assert.equal(git('status','--porcelain'),'');git('merge-base','--is-ancestor','origin/main','HEAD');
const gate=read(base+'/Release-v32-PrePush.json'),dry=read(base+'/dry-run-v32-latest.json'),hook=read(base+'/release-checks-v32/normal-hook-latest.json'),qualification=read(base+'/catalog-release-v3/qualification-v32.json');
for(const p of [gate,dry,hook,qualification])assert.equal(p.status,'passed');assert.equal(gate.commit,git('rev-parse','HEAD'));assert.equal(dry.commit,gate.commit);assert.equal(hook.finalHead,gate.commit);assert.equal(dry.gateSha256,sha(JSON.stringify(gate)));assert.equal(gate.sourceTree,git('rev-parse','HEAD^{tree}'));assert.equal(gate.pending.length,8);assert.equal(gate.migrations,415);assert.equal(gate.candidateMigrations,423);
for(const at of [gate.at,dry.at])assert.ok(Date.now()-Date.parse(at)>=0&&Date.now()-Date.parse(at)<3600000);for(const [n,h]of Object.entries(gate.sourceHashes))assert.equal(sha(fs.readFileSync('supabase/migrations/'+n)),h,n);for(const [p,h]of Object.entries(qualification.sourceHashes))assert.equal(sha(fs.readFileSync(p)),h,p);
const evidence=base+'/current-source-v32',manifestPath='docs/catalog/master_printing_authority_v1/jungle_editions/manifest.json',manifest=read(manifestPath),ar=base+'/catalog-authority-v2',artifacts=new Map(read(ar+'/artifact-map.portable.json').map(r=>[r.ref,fs.readFileSync(path.resolve(ar,r.path))])),refresh=read(evidence+'/refresh/execution-refresh.json');
const refreshProof=assertJungleExecutionRefreshV2(manifest,artifacts,refresh),review=read(evidence+'/refresh/pricing-review.json');assert.equal(review.snapshot_sha256,sha(fs.readFileSync(evidence+'/production-snapshot.json')));assert.equal(review.summary.compatible,128);assert.equal(review.summary.held,0);
const catalog=buildJungleExecutionRows(manifest,artifacts,{asOf:refreshProof.historicalAuthorityAsOf,gameId:refresh.snapshot.cards[0].game_id});catalog.raw_imports[0].notes='Reviewed Jungle base editions; bounded catalog staging only; no activation, publication or copy reassignment.';assert.equal(Object.values(catalog).reduce((n,r)=>n+r.length,0),639);assert.ok(catalog.jungle_edition_identity_links_v1.every(r=>r.state==='staged'));
const out=base+'/release-review-v4-'+Date.now();fs.mkdirSync(out);fs.mkdirSync(out+'/pending-migrations');const save=(n,v)=>fs.writeFileSync(out+'/'+n,JSON.stringify(v,null,2),{flag:'wx'});
const pending=Object.keys(gate.sourceHashes).filter(n=>gate.pending.includes(n.split('_')[0])).map(name=>({name,sha256:gate.sourceHashes[name]}));assert.equal(pending.length,8);assert.deepEqual(pending.map(p=>p.name),dry.pending);
for(const {name}of pending)fs.copyFileSync('supabase/migrations/'+name,out+'/pending-migrations/'+name,fs.constants.COPYFILE_EXCL);
save('catalog-preview.json',catalog);save('reviewed-price-bindings.json',review.rows);save('execution-refresh.json',refresh);save('source-files.json',git('diff','--name-only','origin/main','HEAD').split('\n').filter(Boolean).map(p=>({path:p,sha256:sha(fs.readFileSync(p))})));save('prepush.json',gate);save('dry-run.json',dry);save('qualification.json',qualification);
const historical=read(base+'/full-source-durable-v30/shadow-receipt.json');assert.equal(historical.status,'passed');
const result={at:new Date().toISOString(),version:'JUNGLE_RELEASE_REVIEW_PACKAGE_V4',status:'prepared_for_review',project:'ycdxbpibncqcchqiihfz',commit:gate.commit,sourceTree:gate.sourceTree,productionMigrations:415,candidateMigrations:423,pending,manifestFingerprint:manifest.fingerprint,manifestSha256:sha(fs.readFileSync(manifestPath)),catalogPreviewSha256:sha(fs.readFileSync(out+'/catalog-preview.json')),reviewedBindingsSha256:sha(fs.readFileSync(out+'/reviewed-price-bindings.json')),sourceFilesSha256:sha(fs.readFileSync(out+'/source-files.json')),previewInserts:639,reviewedBindings:128,refreshProof,pricingSourceRun:refresh.snapshot.sourceRun.id,historicalDurableWorker:{sourceRun:historical.sourceRun,decisions:208279,snapshots:164804,newJungle:128,unchangedWorkerAndPolicy:true},schemaPrePushPassed:true,actualLinkedCliDryRunPassed:true,releaseReady:false,executionAuthorized:false,deployable:false,productionWrites:0,pricesPublished:0,slabEnabled:false,remaining:['Publish/review source and execute exact eight-migration schema release','Fresh actual423 production catalog plan, exact bounded authority and production rollback','Bound source-binding activation, governed pricing publication and deployed client readback'],out};save('package.json',result);fs.writeFileSync(base+'/release-review-v4-latest.json',JSON.stringify(result,null,2));console.log(JSON.stringify({status:result.status,pending:8,previewInserts:639,reviewedBindings:128,productionWrites:0,out}));
