import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

import {
  CONTRACT_KEY,
  OUTPUT_DIR,
} from './base_set_print_run_lanes_contract_v1.mjs';

export const PACKAGE_ID = 'BASE-SET-PRINT-RUN-LANES-REAL-APPLY-GATE-V1';
export const DRY_RUN_JSON = path.join(OUTPUT_DIR, 'base_set_print_run_lanes_guarded_dry_run_v1.json');
export const DRY_RUN_SQL = 'docs/sql/base_set_print_run_lanes_guarded_dry_run_v1.sql';
export const REAL_APPLY_SQL = 'docs/sql/base_set_print_run_lanes_real_apply_v1.sql';
export const REPORT_JSON = path.join(OUTPUT_DIR, 'base_set_print_run_lanes_real_apply_gate_v1.json');
export const REPORT_MD = path.join(OUTPUT_DIR, 'base_set_print_run_lanes_real_apply_gate_v1.md');

function stableJson(value) {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(',')}]`;
  if (value && typeof value === 'object') {
    return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`).join(',')}}`;
  }
  return JSON.stringify(value);
}

function sha256(value) {
  return crypto.createHash('sha256').update(value).digest('hex');
}

async function readText(filePath) {
  return fs.readFile(filePath, 'utf8');
}

async function readJson(filePath) {
  return JSON.parse(await readText(filePath));
}

async function writeJson(filePath, value) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

async function writeText(filePath, value) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, value);
}

function stripSqlComments(sql) {
  return sql.replace(/--.*$/gm, '');
}

export function buildRealApplySqlFromDryRunSql(sql) {
  const withoutFinalRollback = sql.replace(/(^|\n)\s*rollback\s*;\s*$/i, '\ncommit;\n');
  if (withoutFinalRollback === sql) {
    throw new Error('DRY_RUN_SQL_MISSING_FINAL_ROLLBACK');
  }
  return withoutFinalRollback.replace(
    /-- This artifact must not be used as a real apply without a separate approval gate\./,
    '-- Real apply artifact generated by BASE-SET-PRINT-RUN-LANES-REAL-APPLY-GATE-V1. Execute only after exact approval text is recorded.',
  );
}

function validateDryRunReport(dryRun) {
  const findings = [];
  const proof = dryRun.proof_row ?? null;
  const beforeHash = dryRun.execution?.before_snapshot?.hash_sha256 ?? null;
  const afterHash = dryRun.execution?.after_snapshot?.hash_sha256 ?? null;

  if (dryRun.package_id !== 'BASE-SET-PRINT-RUN-LANES-GUARDED-DRY-RUN-V1') findings.push('dry_run_package_id_mismatch');
  if (dryRun.contract_key !== CONTRACT_KEY) findings.push('dry_run_contract_key_mismatch');
  if (dryRun.write_ready_now !== true) findings.push('dry_run_not_write_ready');
  if (dryRun.durable_db_writes_performed !== false) findings.push('dry_run_reports_durable_write');
  if (dryRun.migrations_created !== false) findings.push('dry_run_reports_migration');
  if (dryRun.real_apply_authorized !== false) findings.push('dry_run_reports_real_apply_authorized');
  if ((dryRun.stop_findings ?? []).length !== 0) findings.push('dry_run_stop_findings_present');
  if (dryRun.execution?.execution_status !== 'guarded_dry_run_transaction_completed_and_rolled_back') findings.push('dry_run_execution_status_not_passed');
  if (!beforeHash || !afterHash || beforeHash !== afterHash) findings.push('dry_run_rollback_hash_mismatch');
  if (!proof) findings.push('dry_run_proof_missing');

  if (proof) {
    if (Number(proof.inserted_set_rows) !== 3) findings.push('proof_inserted_set_rows_not_three');
    if (Number(proof.inserted_card_print_rows) !== 304) findings.push('proof_inserted_card_print_rows_not_304');
    if (Number(proof.forbidden_rows) !== 0) findings.push('proof_forbidden_rows_present');
    const laneProof = Array.isArray(proof.lane_slot_proof) ? proof.lane_slot_proof : [];
    for (const laneCode of ['base1-shadowless', 'base1-first-edition', 'base1-1999-2000']) {
      const row = laneProof.find((entry) => entry.lane_code === laneCode);
      if (!row) findings.push(`proof_missing_${laneCode}`);
      if (row && Number(row.covered_slots_after_plan) !== 102) findings.push(`proof_not_102_${laneCode}`);
    }
  }

  if (!dryRun.required_real_apply_approval_text) findings.push('required_approval_text_missing');
  return findings;
}

function validateSqlPair({ dryRunSql, realApplySql, dryRun }) {
  const findings = [];
  const dryRunStripped = stripSqlComments(dryRunSql);
  const realStripped = stripSqlComments(realApplySql);
  const realSqlHash = sha256(realApplySql);

  if (sha256(dryRunSql) !== dryRun.sql_hash_sha256) findings.push('dry_run_sql_hash_mismatch');
  if (!/(^|\n)\s*rollback\s*;\s*$/i.test(dryRunStripped)) findings.push('dry_run_sql_missing_final_rollback');
  if (/(^|\n)\s*commit\s*;/i.test(dryRunStripped)) findings.push('dry_run_sql_contains_commit');
  if (!/(^|\n)\s*commit\s*;\s*$/i.test(realStripped)) findings.push('real_apply_sql_missing_final_commit');
  if (/(^|\n)\s*rollback\s*;/i.test(realStripped)) findings.push('real_apply_sql_contains_rollback');
  if (/\bdelete\s+from\b/i.test(realStripped)) findings.push('real_apply_sql_contains_delete');
  if (/\bupdate\s+public\./i.test(realStripped)) findings.push('real_apply_sql_contains_update_public');
  if (!/\binsert\s+into\s+public\.sets\b/i.test(realStripped)) findings.push('real_apply_sql_missing_sets_insert');
  if (!/\binsert\s+into\s+public\.card_prints\b/i.test(realStripped)) findings.push('real_apply_sql_missing_card_prints_insert');
  if (/\binsert\s+into\s+public\.card_printings\b/i.test(realStripped)) findings.push('real_apply_sql_contains_child_insert');
  if (/\binsert\s+into\s+public\.external_/i.test(realStripped)) findings.push('real_apply_sql_contains_external_insert');
  if (/missing_variant_visual/i.test(realStripped)) findings.push('real_apply_sql_contains_disallowed_image_status');
  if (/then\s+'GV-PK-BASE1-58-SHADOWLESS'/i.test(realStripped)) findings.push('real_apply_sql_contains_generic_shadowless_pikachu');
  if (/then\s+'GV-PK-BASE1-58-FIRST-EDITION'/i.test(realStripped)) findings.push('real_apply_sql_contains_generic_first_edition_pikachu');

  return { findings, realSqlHash };
}

function buildMarkdown(report) {
  return `# Base Set Print Run Lanes Real Apply Gate V1

Generated: ${report.generated_at}

Package: ${report.package_id}

Contract: ${report.contract_key}

## Gate Status

- approval_gate_only: ${report.approval_gate_only}
- apply_executed: ${report.apply_executed}
- durable_db_writes_performed: ${report.durable_db_writes_performed}
- apply_allowed_by_gate: ${report.apply_allowed_by_gate}
- stop_findings: ${report.stop_findings.length}

## Required Approval

\`${report.required_real_apply_approval_text}\`

## Scope

- derived set inserts: 3
- card_print lane identity inserts: 304
- Shadowless covered slots after plan: 102
- 1st Edition covered slots after plan: 102
- 1999-2000 covered slots after plan: 102
- generic Pikachu #58 Shadowless/1st Edition rows: blocked
- Ghost Stamp ordinary lane coverage: blocked
- exact image claims: blocked

## Artifacts

- rollback dry-run SQL: \`${report.dry_run_sql_path}\`
- real apply SQL: \`${report.real_apply_sql_path}\`
- dry-run SQL hash: \`${report.dry_run_sql_hash_sha256}\`
- real apply SQL hash: \`${report.real_apply_sql_hash_sha256}\`
`;
}

export async function runBaseSetPrintRunLanesRealApplyGateV1() {
  const dryRun = await readJson(DRY_RUN_JSON);
  const dryRunSql = await readText(DRY_RUN_SQL);
  const realApplySql = buildRealApplySqlFromDryRunSql(dryRunSql);
  await writeText(REAL_APPLY_SQL, realApplySql);

  const dryRunFindings = validateDryRunReport(dryRun);
  const { findings: sqlFindings, realSqlHash } = validateSqlPair({ dryRunSql, realApplySql, dryRun });
  const stopFindings = [...dryRunFindings, ...sqlFindings];
  const approvalText = dryRun.required_real_apply_approval_text ?? null;

  const report = {
    package_id: PACKAGE_ID,
    contract_key: CONTRACT_KEY,
    generated_at: new Date().toISOString(),
    approval_gate_only: true,
    apply_executed: false,
    durable_db_writes_performed: false,
    migrations_created: false,
    cleanup_performed: false,
    apply_allowed_by_gate: stopFindings.length === 0,
    required_real_apply_approval_text: approvalText,
    dry_run_sql_path: DRY_RUN_SQL,
    real_apply_sql_path: REAL_APPLY_SQL,
    dry_run_sql_hash_sha256: dryRun.sql_hash_sha256,
    real_apply_sql_hash_sha256: realSqlHash,
    dry_run_proof_digest_sha256: sha256(stableJson({
      before: dryRun.execution?.before_snapshot?.hash_sha256,
      after: dryRun.execution?.after_snapshot?.hash_sha256,
      proof: dryRun.proof_row,
    })),
    stop_findings: stopFindings,
  };

  await writeJson(REPORT_JSON, report);
  await writeText(REPORT_MD, buildMarkdown(report));
  return report;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  runBaseSetPrintRunLanesRealApplyGateV1()
    .then((report) => {
      console.log(JSON.stringify({
        package_id: report.package_id,
        approval_gate_only: report.approval_gate_only,
        apply_executed: report.apply_executed,
        durable_db_writes_performed: report.durable_db_writes_performed,
        apply_allowed_by_gate: report.apply_allowed_by_gate,
        stop_findings: report.stop_findings,
        real_apply_sql_path: report.real_apply_sql_path,
      }, null, 2));
    })
    .catch((error) => {
      console.error(error);
      process.exitCode = 1;
    });
}
