import fs from 'node:fs';
import path from 'node:path';

const repoRoot = process.cwd();
const inputPath = path.join(
  repoRoot,
  'apps/web/src/lib/cards/variantOriginPublicCopy.generated.json',
);
const outputPath = path.join(
  repoRoot,
  'lib/services/identity/variant_origin_public_copy_generated.dart',
);

function dartString(value) {
  return JSON.stringify(String(value))
    .replace(/\$/g, '\\$');
}

function chunkString(value, size = 1200) {
  const chunks = [];
  for (let index = 0; index < value.length; index += size) {
    chunks.push(value.slice(index, index + size));
  }
  return chunks;
}

const source = JSON.parse(fs.readFileSync(inputPath, 'utf8'));
const payload = {
  families: source.families ?? {},
  by_gv_id: source.by_gv_id ?? {},
  by_card_print_id: source.by_card_print_id ?? {},
};
const payloadJson = JSON.stringify(payload);
const chunks = chunkString(payloadJson)
  .map((chunk) => `  ${dartString(chunk)},`)
  .join('\n');

const output = `// GENERATED CODE - DO NOT EDIT BY HAND.
// Generated by scripts/audits/export_variant_origin_mobile_data_v1.mjs.

const String variantOriginGeneratedAt = ${dartString(source.generated_at ?? '')};
const String variantOriginSourceFingerprintSha256 = ${dartString(source.source_fingerprint_sha256 ?? '')};
const String variantOriginSourceVersion = ${dartString(source.source_version ?? '')};

const List<String> variantOriginPublicCopyJsonChunks = <String>[
${chunks}
];

String get variantOriginPublicCopyJson => variantOriginPublicCopyJsonChunks.join();
`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output);

console.log(
  JSON.stringify(
    {
      output: path.relative(repoRoot, outputPath),
      families: Object.keys(source.families ?? {}).length,
      by_gv_id: Object.keys(source.by_gv_id ?? {}).length,
      by_card_print_id: Object.keys(source.by_card_print_id ?? {}).length,
      source_fingerprint_sha256: source.source_fingerprint_sha256 ?? null,
    },
    null,
    2,
  ),
);
