import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import pg from 'pg';import {createHash} from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..').replaceAll('\\','/'),out=process.env.GV_MAPPING_PROOF_OUT,database=process.env.GV_MAPPING_PROOF_DATABASE;
assert.ok(out&&path.isAbsolute(out));assert.match(database??'',/^grookai_gamestop_mapping_20261001_v[0-9]+$/);assert.ok(fs.existsSync(out));
for(const k of Object.keys(process.env))if(/SUPABASE|DATABASE|^PG|TOKEN|SECRET|API_KEY/.test(k))delete process.env[k];process.env.DOTENV_CONFIG_PATH=out+'/no-environment-file';
const info=JSON.parse(execFileSync('docker',['inspect','supabase_db_ycdxbpibncqcchqiihfz'],{encoding:'utf8'}))[0];assert.equal(info.NetworkSettings.Ports['5432/tcp'][0].HostPort,'54330');const password=info.Config.Env.find(s=>s.startsWith('POSTGRES_PASSWORD=')).slice('POSTGRES_PASSWORD='.length);
const connect=name=>new pg.Client({host:'127.0.0.1',port:54330,user:'postgres',password,database:name,ssl:false});
const admin=connect('postgres');await admin.connect();assert.equal((await admin.query('select count(*)::int n from pg_database where datname=$1',[database])).rows[0].n,0,'Preserve existing local proof database');await admin.query('create database '+database);await admin.end();
const db=connect(database);await db.connect();
const {mappingFixture}=await import('file:///'+root+'/tests/fixtures/reviewed_gamestop_mapping_v1.mjs');
const {seal}=await import('file:///'+root+'/tests/fixtures/warehouse_printing_authority_v1.mjs');
const {printingManifestHash:hash}=await import('file:///'+root+'/backend/catalog/printing_completeness_gate_v1.mjs');
const {readGameStopMappingDependencies,assertReviewedGameStopMapping,executeReviewedGameStopMapping,assertGameStopMappingReadback,readGameStopMappingState}=await import('file:///'+root+'/backend/warehouse/reviewed_gamestop_mapping_v1.mjs');
const sha=b=>createHash('sha256').update(b).digest('hex');
const report={at:new Date().toISOString(),synthetic_only:true,production_access:false,database,steps:[]};
try{
 await db.query(`create table card_prints(id uuid primary key,set_id uuid,gv_id text,name text,number text,identity_domain text,variant_key text,printed_identity_modifier text,tcgplayer_id text,external_ids jsonb default '{}');
 create table card_printings(id uuid primary key,card_print_id uuid references card_prints,finish_key text,printing_gv_id text,is_provisional boolean);
 create table card_printing_truth_reviews(id uuid primary key,card_printing_id uuid references card_printings,review_status text);
 create table tcgcsv_source_products(product_id bigint primary key,category_id integer,name text,payload_hash text);
 create table raw_imports(id bigint primary key,payload jsonb);
 create table external_discovery_candidates(id uuid primary key,tcgplayer_id text,raw_import_id bigint);
 create table external_mappings(id bigserial primary key,card_print_id uuid references card_prints,source text,external_id text,active boolean,meta jsonb,unique(source,external_id));
 create table canon_warehouse_candidates(id uuid primary key,state text,tcgplayer_id text,founder_approved_by_user_id uuid,founder_approved_at timestamptz,reference_hints_payload jsonb,claimed_identity_payload jsonb,current_staging_id uuid,current_review_hold_reason text,archived_by_user_id uuid,archived_at timestamptz,archive_notes text);
 create table canon_warehouse_candidate_events(id bigserial primary key,candidate_id uuid,event_type text,action text,previous_state text,next_state text,actor_type text,metadata jsonb);
 create table vault_item_instances(id uuid primary key,card_print_id uuid references card_prints,card_printing_id uuid references card_printings,note text);
 create table market_price_publication_snapshots(id uuid primary key,source_mapping_id bigint references external_mappings,card_print_id uuid references card_prints);
 create table contract_violations(id bigserial primary key,contract_name text,violation_type text,severity text,execution_name text,actor_type text,actor_id text,source_worker text,source_api text,source_payload_hash text,payload_snapshot jsonb,reason text);`);
 let b=mappingFixture();b.before.parent.external_ids={};
 const insert=async(table,row)=>{const cols=Object.keys(row);await db.query(`insert into ${table}(${cols.join(',')}) values(${cols.map((_,i)=>'$'+(i+1)).join(',')})`,Object.values(row));};
 await insert('card_prints',b.before.parent);await insert('card_printings',b.before.children[0]);await insert('tcgcsv_source_products',b.before.source);await insert('raw_imports',b.before.raw);await insert('external_discovery_candidates',b.before.discovery);await insert('external_mappings',b.before.mappings[0]);
 await db.query("select setval(pg_get_serial_sequence('external_mappings','id'),9,true)");
 await insert('vault_item_instances',{id:'88888888-8888-4888-8888-888888888888',card_print_id:b.target.card_print_id,card_printing_id:b.before.children[0].id,note:'Synthetic collector copy must remain untouched'});
 b.dependencies=await readGameStopMappingDependencies(db,b);const a=b.manifest.external_mapping_assertions[0];a.parent_snapshot_sha256=hash(b.before.parent);a.dependencies_sha256=hash(b.dependencies);
 const projection=structuredClone(b.manifest);delete projection.fingerprint;delete projection.authority.review;
 const reviewIndex=b.artifacts.findIndex(a=>a.ref==='review'),review=JSON.parse(Buffer.from(b.artifacts[reviewIndex].base64,'base64'));review.projection_sha256=hash(projection);const bytes=Buffer.from(JSON.stringify(review));b.artifacts[reviewIndex].base64=bytes.toString('base64');b.manifest.authority.review.sha256=sha(bytes);b.manifest=seal(b.manifest);b=seal(b);assertReviewedGameStopMapping(b);
 await insert('canon_warehouse_candidates',{id:b.target.candidate_id,state:'APPROVED_BY_FOUNDER',tcgplayer_id:b.target.external_id,founder_approved_by_user_id:'77777777-7777-4777-8777-777777777777',founder_approved_at:new Date(),reference_hints_payload:{authority_fingerprint:b.fingerprint},claimed_identity_payload:{source_raw_import_id:b.before.raw.id,source_discovery_candidate_id:b.before.discovery.id}});
 const authorization={approved:true,authority_fingerprint:b.fingerprint,operator:'synthetic test',request:'local proof only'};
 const snapshot=async()=>(await db.query("select md5(string_agg(v,'|' order by v)) digest from (select to_jsonb(t)::text v from external_mappings t union all select to_jsonb(t)::text from canon_warehouse_candidates t union all select to_jsonb(t)::text from canon_warehouse_candidate_events t union all select to_jsonb(t)::text from vault_item_instances t) x")).rows[0].digest;
 const before=await snapshot();
 await db.query('begin isolation level serializable');let inserted=false;
 const proxy={async query(sql,args){const r=await db.query(sql,args);if(sql.startsWith('insert into public.external_mappings'))inserted=true;if(inserted&&sql.startsWith('select to_jsonb(p) row from public.card_prints'))return {rows:r.rows.map(r=>({row:{...r.row,name:'Injected postwrite drift'}}))};return r;}};
 await assert.rejects(executeReviewedGameStopMapping(proxy,b,{authorization}),/mapping_preservation:parent/);assert.ok(inserted);await db.query('rollback');assert.equal(await snapshot(),before);report.steps.push('actual mapping insert and invalidation rolled back after forced readback failure');
 await db.query('begin isolation level serializable');const applied=await executeReviewedGameStopMapping(db,b,{authorization});assert.equal(applied.status,'applied');await db.query('commit');assertGameStopMappingReadback(b,await readGameStopMappingState(db,b));report.steps.push('real committed mapping and preserved invalid mapping history independently read back');
 const after=await snapshot();await db.query('begin isolation level serializable');assert.equal((await executeReviewedGameStopMapping(db,b,{authorization})).status,'already_succeeded');await db.query('commit');assert.equal(await snapshot(),after);report.steps.push('repeat makes zero writes');report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;await db.query('rollback').catch(()=>{});throw e;}finally{await db.end();fs.writeFileSync(out+'/local-proof-v1.json',JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(report);}
