import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {assertJungleEditionMasterV1} from '../../backend/catalog/jungle_edition_master_authority_v1.mjs';
import {printingManifestHash as hash} from '../../backend/catalog/printing_completeness_gate_v1.mjs';
import {reviewJungleEditionSourcesV1} from '../../backend/pricing/jungle_edition_source_review_v1.mjs';
const args=new Map();for(const arg of process.argv.slice(2)){const m=/^--(artifact-map|snapshot|out)=(.+)$/.exec(arg);assert.ok(m&&!args.has(m[1]));args.set(m[1],path.resolve(m[2]));}assert.equal(args.size,3);
const read=p=>JSON.parse(fs.readFileSync(p)),sha=b=>createHash('sha256').update(b).digest('hex');
const manifest=read(new URL('../../docs/catalog/master_printing_authority_v1/jungle_editions/manifest.json',import.meta.url));
const map=args.get('artifact-map'),artifacts=new Map(read(map).map(r=>[r.ref,fs.readFileSync(path.resolve(path.dirname(map),r.path))]));
const asOf=new Date().toISOString();assertJungleEditionMasterV1(manifest,artifacts,{asOf});
const sourceBytes=fs.readFileSync(args.get('snapshot')),snapshot=JSON.parse(sourceBytes),prior=JSON.parse(String(artifacts.get('jungle:production-snapshot')));
assert.deepEqual(snapshot.collisions,{parents:[],children:[]});assert.equal(snapshot.allocationSha256,prior.allocationSha256);
const stableSections=['cards','printings','species','schema'];const comparisons=Object.fromEntries(stableSections.map(k=>[k,{unchanged:hash(snapshot[k])===hash(prior[k]),before:hash(prior[k]),after:hash(snapshot[k])}]));
const dependencies=snapshot.dependencies.map(d=>{const old=prior.dependencies.find(p=>p.schema_name===d.schema_name&&p.table_name===d.table_name&&p.column_name===d.column_name&&p.conname===d.conname);return {schema:d.schema_name,table:d.table_name,column:d.column_name,beforeCount:old?.count??null,afterCount:d.count,unchanged:!!old&&old.count===d.count&&old.rowsSha256===d.rowsSha256,beforeSha256:old?.rowsSha256??null,afterSha256:d.rowsSha256};});
const removedDependencies=prior.dependencies.filter(p=>!snapshot.dependencies.some(d=>d.schema_name===p.schema_name&&d.table_name===p.table_name&&d.column_name===p.column_name&&d.conname===p.conname));
const artifactBytes=new Map(snapshot.capturedArtifacts.map(a=>{assert.equal(path.basename(a.file),a.file);const b=fs.readFileSync(path.join(path.dirname(args.get('snapshot')),a.file));assert.equal(sha(b),a.sha256);return[a.id,b];}));
const review=reviewJungleEditionSourcesV1({manifest,snapshot,artifactBytes,asOf});
const result={...review,snapshot_sha256:sha(sourceBytes),reconciliation:{comparisons,dependencies,removedDependencies,changedDependencies:dependencies.filter(d=>!d.unchanged).length,scope:'Direct single-column FK footprints; indirect/application dependencies still require release reconciliation.'}};
fs.writeFileSync(args.get('out'),JSON.stringify(result,null,2),{flag:'wx'});
console.log(JSON.stringify({summary:result.summary,comparisons:Object.fromEntries(Object.entries(comparisons).map(([k,v])=>[k,v.unchanged])),changedDependencies:result.reconciliation.changedDependencies,removedDependencies:removedDependencies.length,held:result.rows.filter(r=>!r.compatible).map(r=>({number:r.number,name:r.name,edition:r.edition,reasons:r.reasons})),write_ready:false}));
