import { emptyBook, createReceipt, saveSale, parseBackup, customerInput, receiptText, receiptHtml, deliveryLink, money, paymentMethods, escapeHtml as h } from './receiptBook.mjs';

export function mountReceiptDesk(root,options={}) {
  options={...options};
  const key='grookai.receipt-book.v1.'+(options.accountKey||'offline'),storage=options.cloud?null:(options.storage||localStorage);
  let book,savedRaw=null,selected=null,draftId=crypto.randomUUID(),customerId=crypto.randomUUID(),disposed=false,busy=false,draftCreatedAt=null;
  const setBusy=value=>{busy=value;root.setAttribute('aria-busy',String(value));for(const field of root.querySelectorAll('input,button,select,textarea'))field.disabled=value;};
  const status=(message,error=false)=>{const el=root.querySelector('[data-status]');if(el){el.textContent=message;el.setAttribute('role',error?'alert':'status');}};
  const persist=async next=>{if(options.cloud){await options.cloud.save(next);book=next;return;}if(storage.getItem(key)!==savedRaw)throw Error('Records changed in another tab. Reload before saving; your existing records were not overwritten.');const raw=JSON.stringify(next);storage.setItem(key,raw);savedRaw=raw;book=next;};
  try { if(options.cloud)book=parseBackup(JSON.stringify(options.cloud.book));else{const raw=storage.getItem(key);book=raw?parseBackup(raw):emptyBook();savedRaw=raw;} }
  catch { root.innerHTML='<p role="alert">Saved receipt data could not be opened. Do not clear this browser’s storage. Export or recover your existing data before creating more receipts.</p>';return ()=>{}; }
  const input=(name,label,value='',extra='')=>`<label>${label}<input name="${name}" value="${h(value)}" ${extra}></label>`;
  function itemRow(description='',price='',quantity=1){return `<div class="rd-item">${input('description','Item / card',description,'required maxlength="200" placeholder="Card name, condition, or item"')}${input('quantity','Qty',quantity,'required type="number" min="1" max="999" step="1"')}${input('price','Unit price (USD)',price,'required inputmode="decimal" placeholder="0.00"')}<button type="button" data-remove aria-label="Remove item">×</button></div>`;}
  const downloads=(content,name,type)=>{const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);};
  function layout(){
    root.innerHTML=`<div class="rd"><header class="rd-header"><div><span class="rd-eyebrow">GROOKAI · VENDOR TOOLS</span><h1>${options.cloud?'Account receipt desk':'Receipt desk'}</h1><p>In-person sales. A receipt and a customer to remember.</p></div><div class="rd-toolbar"><button data-new>New sale</button><button data-backup>Back up records</button><label class="rd-file">${options.cloud?'Import device backup':'Restore backup'}<input data-import type="file" accept="application/json,.json" aria-label="Restore receipt backup"></label></div></header>
      <div class="rd-notice">${options.cloud?'<strong>Saved to your account.</strong> Open this account receipt desk on another device to access saved records. Reload to see changes from other devices. Device-only receipts stay separate; import their backup into an empty account book to move a copy here.':'<strong>Saved on this device only.</strong> Back up your records after selling. These records do not sync to other devices or update Vault inventory.'} Email and text buttons open drafts; you send them from your own app. These receipts do not update inventory.</div>
      <p data-status role="status" class="rd-status" aria-live="polite"></p><div class="rd-grid"><section class="rd-editor"></section><aside class="rd-side"><h2>Sales & customers</h2><label>Find a receipt or customer<input data-search placeholder="Name, phone, email, card, receipt #"></label><div data-history></div></aside></div></div>`;
    form();history();bind();
  }
  function form(){
    selected=null;const p=options.prefill||{};const existing=p.sourceDispositionId&&book.receipts.find(r=>r.receipt.sourceDispositionId===p.sourceDispositionId);
    if(existing){show(existing.receipt.id);return;}
    root.querySelector('.rd-editor').innerHTML=`<form data-sale><div class="rd-section"><h2>Sale details</h2>${input('storeName','Store / seller name',book.storeName||options.storeName||'','required maxlength="120" autocomplete="organization"')}
      <div data-items>${itemRow(p.description||'',p.price||'')}</div><button type="button" data-add>+ Add item</button><div class="rd-columns">${input('discount','Discount (USD)','0','inputmode="decimal"')}${input('tax','Tax collected (USD)','0','inputmode="decimal"')}</div><label>Payment received via<select name="method">${paymentMethods.map(m=>`<option>${h(m)}</option>`).join('')}</select></label><p class="rd-small">Enter any tax you collected. This tool does not calculate tax or determine what you owe.</p></div>
      <div class="rd-section"><h2>Customer <span class="rd-muted">optional</span></h2><label>Existing customer<select data-customer><option value="">New customer / walk-up</option>${book.customers.map(c=>`<option value="${h(c.id)}">${h(c.name||c.email||c.phone||'Unnamed customer')}</option>`).join('')}</select></label>
      ${input('name','Name',p.customerName||'','maxlength="120" autocomplete="name"')}<div class="rd-columns">${input('email','Email','','type="email" maxlength="254" autocomplete="email"')}${input('phone','Phone','','type="tel" maxlength="40" autocomplete="tel"')}</div><label>What are they looking for?<textarea name="wants" rows="2" maxlength="1000" placeholder="Cards, sets, condition, budget…"></textarea></label><label>Private customer notes<textarea name="notes" rows="2" maxlength="2000"></textarea></label><p class="rd-small">Notes and buying interests stay off the receipt. Contact details do not enroll anyone in marketing.</p></div>
      <div class="rd-section"><label>Receipt note / return policy<textarea name="note" rows="2" maxlength="500" placeholder="Optional message shown on the receipt"></textarea></label><label class="rd-check"><input type="checkbox" name="confirmed" required> I received this payment and the sale is complete.</label><p class="rd-small">The receipt records your in-person payment. Grookai does not process or verify it.</p><p class="rd-total" data-total-preview>Total: add item prices</p><button class="rd-primary" type="submit">Save sale & create receipt</button></div></form>`;
  }
  function history(query=''){
    const q=query.toLowerCase().trim(),customersById=new Map(book.customers.map(c=>[c.id,c]));const rows=book.receipts.filter(row=>{const c=customersById.get(row.customerId);return JSON.stringify([row.receipt.number,row.receipt.customerName,row.receipt.items,c]).toLowerCase().includes(q);});
    root.querySelector('[data-history]').innerHTML=`<p class="rd-small">${rows.length} receipt${rows.length===1?'':'s'} · ${book.customers.length} customer${book.customers.length===1?'':'s'}</p>${rows.slice(0,100).map(({receipt:r})=>`<button class="rd-history" data-open="${h(r.id)}"><span><strong>${h(r.customerName||'Walk-up customer')}</strong><small>${h(r.number)} · ${h(new Date(r.createdAt).toLocaleDateString())}</small></span><strong>${h(money(r.totalMinor))}</strong></button>`).join('')||'<p class="rd-empty">Your saved sales will appear here.</p>'}${rows.length>100?'<p>Narrow your search to see more receipts.</p>':''}`;
  }
  function show(id){
    const row=book.receipts.find(x=>x.receipt.id===id);if(!row)return;selected=id;const r=row.receipt,c=book.customers.find(x=>x.id===row.customerId);
    root.querySelector('.rd-editor').innerHTML=`<div class="rd-section"><div class="rd-success">${options.cloud?'Sale saved to your account':'Sale saved on this device'}</div><h2>${h(r.storeName)}</h2><p class="rd-small">${h(r.number)} · ${h(new Date(r.createdAt).toLocaleString())}</p>${r.customerName?`<p>Customer: ${h(r.customerName)}</p>`:''}<table class="rd-table"><thead><tr><th>Item</th><th>Qty</th><th>Amount</th></tr></thead><tbody>${r.items.map(i=>`<tr><td>${h(i.description)}<small>${h(money(i.unitMinor))} each</small></td><td>${i.quantity}</td><td>${h(money(i.lineMinor))}</td></tr>`).join('')}</tbody></table><dl class="rd-totals"><dt>Subtotal</dt><dd>${money(r.subtotalMinor)}</dd><dt>Discount</dt><dd>−${money(r.discountMinor)}</dd><dt>Tax collected</dt><dd>${money(r.taxMinor)}</dd><dt class="rd-total">Total received</dt><dd class="rd-total">${money(r.totalMinor)}</dd></dl><p>${h(r.method)} · Recorded by vendor</p>${r.note?`<p class="rd-wrap">${h(r.note)}</p>`:''}<div class="rd-actions"><button data-print class="rd-primary">Print / save PDF</button><button data-download>Download receipt</button><button data-share>Share receipt</button><button data-copy>Copy receipt text</button></div></div>
      <div class="rd-section"><h2>Send a receipt</h2><p class="rd-small">Check the destination, then send the draft from your email or messaging app. Grookai cannot confirm delivery.</p>${input('sendEmail','Email',c?.email||'','type="email" maxlength="254"')}${input('sendPhone','Phone',c?.phone||'','type="tel" maxlength="40"')}<div class="rd-actions"><button data-email>Open email draft</button><button data-sms>Open text draft</button></div><p class="rd-small">No email or messaging app? Use Share, or copy the receipt text.</p></div>
      ${c?`<div class="rd-section"><h2>Private customer record</h2><p>${h(c.name||'Unnamed customer')}</p><p>${h(c.email)} ${h(c.phone)}</p><p class="rd-wrap"><strong>Looking for:</strong> ${h(c.wants||'Not recorded')}</p><p class="rd-wrap"><strong>Notes:</strong> ${h(c.notes||'None')}</p><p class="rd-small">${book.receipts.filter(x=>x.customerId===c.id).length} saved purchase(s). Choose this customer on a new sale to update their contact details and notes.</p></div>`:''}`;
  }
  async function click(event){
    const button=event.target.closest('button');if(!button||busy)return;
    try{
      if(button.hasAttribute('data-new')){options.prefill=null;draftCreatedAt=null;draftId=crypto.randomUUID();customerId=crypto.randomUUID();form();status('Ready for the next sale.');}
      if(button.hasAttribute('data-add')){const items=root.querySelector('[data-items]');if(items.children.length>=50)throw Error('Maximum 50 items per receipt.');items.insertAdjacentHTML('beforeend',itemRow());}
      if(button.hasAttribute('data-remove')){if(root.querySelector('[data-items]').children.length===1)throw Error('A receipt needs at least one item.');button.closest('.rd-item').remove();}
      if(button.dataset.open)show(button.dataset.open);
      if(button.hasAttribute('data-backup')){downloads(JSON.stringify(book),'grookai-receipts-'+new Date().toISOString().slice(0,10)+'.json','application/json');status('Backup downloaded. It contains private customer details; keep it somewhere safe.');}
      if(button.hasAttribute('data-add')||button.hasAttribute('data-remove'))search(event);
      const r=book.receipts.find(x=>x.receipt.id===selected)?.receipt;if(!r)return;
      if(button.hasAttribute('data-download')){downloads(receiptHtml(r),r.number+'.html','text/html');status('Receipt downloaded. Open it to print or save as PDF.');}
      if(button.hasAttribute('data-print')){const popup=window.open('','_blank');if(!popup)throw Error('Your browser blocked the print window. Download the receipt and open it instead.');popup.opener=null;popup.document.write(receiptHtml(r));popup.document.close();popup.focus();popup.print();}
      if(button.hasAttribute('data-copy')){await navigator.clipboard.writeText(receiptText(r));status('Receipt text copied. Paste it into your message.');}
      if(button.hasAttribute('data-share')){const file=new File([receiptText(r)],r.number+'.txt',{type:'text/plain'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:r.number});else if(navigator.share)await navigator.share({title:r.number,text:receiptText(r)});else{downloads(receiptText(r),r.number+'.txt','text/plain');status('Text receipt downloaded. Attach it to your message.');}}
      for(const [attr,channel,field]of [['data-email','email','sendEmail'],['data-sms','sms','sendPhone']])if(button.hasAttribute(attr)){const link=deliveryLink(channel,root.querySelector(`[name="${field}"]`).value,r);window.location.href=link;status('Draft requested. Review and send it in your own app; delivery is not tracked here.');}
    }catch(e){if(e.name!=='AbortError')status(e.message||'That action could not be completed.',true);}
  }
  async function submit(event){
    if(!event.target.matches('[data-sale]'))return;event.preventDefault();if(busy)return;
    try{const f=new FormData(event.target),get=n=>String(f.get(n)||''),customer=customerInput({name:get('name'),email:get('email'),phone:get('phone'),wants:get('wants'),notes:get('notes')});
      const items=[...root.querySelectorAll('.rd-item')].map(row=>({description:row.querySelector('[name=description]').value,quantity:row.querySelector('[name=quantity]').value,price:row.querySelector('[name=price]').value}));
      const receipt=createReceipt({storeName:get('storeName'),customer,items,discount:get('discount'),tax:get('tax'),method:get('method'),confirmed:f.get('confirmed')==='on',note:get('note'),sourceDispositionId:options.prefill?.sourceDispositionId},draftId,draftCreatedAt??=new Date().toISOString());
      const next=saveSale(book,receipt,customer,customerId);setBusy(true);status('Saving receipt…');await persist(next);if(disposed)return;show(receipt.id);history();status(options.cloud?'Sale and receipt saved to your account.':'Sale and receipt saved. Back up your records before leaving this device.');
    }catch(e){if(!disposed)status(e.message?.includes('quota')?'Device storage is full. The sale was not saved. Back up existing records first.':e.message,true);}finally{setBusy(false);}
  }
  async function change(event){
    if(busy)return;
    if(event.target.matches('[data-customer]')){const c=book.customers.find(x=>x.id===event.target.value);customerId=c?.id||crypto.randomUUID();for(const name of ['name','email','phone','wants','notes'])root.querySelector(`[name="${name}"]`).value=c?.[name]||'';}
    if(event.target.matches('[data-import]'))try{const file=event.target.files?.[0];if(!file)return;if(file.size>10000000)throw Error('Backup is too large.');const restored=parseBackup(await file.text());if(book.receipts.length||book.customers.length)throw Error('Restore is available only in an empty receipt book. Use a separate browser profile to inspect another backup. Your existing records were not changed.');setBusy(true);await persist(restored);if(disposed)return;form();history();status(options.cloud?'Backup saved to your account. Your original device copy is unchanged.':'Backup restored on this device.');}catch(e){status(e.message,true);}finally{setBusy(false);event.target.value='';}
  }
  const search=e=>{if(e.target.matches('[data-search]'))history(e.target.value);const f=root.querySelector('[data-sale]'),preview=root.querySelector('[data-total-preview]');if(!f||!preview)return;try{const values=new FormData(f),get=n=>String(values.get(n)||'');const r=createReceipt({storeName:get('storeName')||'Seller',customer:{name:'',email:'',phone:'',wants:'',notes:''},confirmed:true,method:get('method'),note:'',discount:get('discount'),tax:get('tax'),items:[...root.querySelectorAll('.rd-item')].map(row=>({description:row.querySelector('[name=description]').value||'Item',quantity:row.querySelector('[name=quantity]').value,price:row.querySelector('[name=price]').value}))},draftId,new Date().toISOString());preview.textContent='Total: '+money(r.totalMinor);}catch{preview.textContent='Total: check item prices, quantities and discount';}};
  function bind(){root.addEventListener('click',click);root.addEventListener('submit',submit);root.addEventListener('change',change);root.addEventListener('input',search);}
  layout();return()=>{if(disposed)return;disposed=true;root.removeEventListener('click',click);root.removeEventListener('submit',submit);root.removeEventListener('change',change);root.removeEventListener('input',search);root.replaceChildren();};
}
