"use client";
/* eslint-disable @next/next/no-img-element -- Private draft images must go directly through the authenticated no-store endpoint. */
import Link from "next/link";
import { useEffect, useState } from "react";
import { productChange, storeRequest, uploadStoreImage, type OwnerModel, type OwnerProduct, type ProductList } from "./storeManagerClient";
import type { StoreTask } from "./StoreManager";
import s from "./StoreManager.module.css";

type Props = { owner: OwnerModel; canEdit: boolean; busy: boolean; task: StoreTask; setDirty: (dirty: boolean) => void };
const textFields = [
  ["category", "Category", 80], ["franchise", "Franchise", 80], ["manufacturer", "Manufacturer", 120],
  ["release_region", "Release region", 80], ["language", "Language", 80], ["private_sku", "Private SKU", 80],
  ["condition_description", "Condition description", 500], ["packaging_description", "Packaging description", 500],
] as const;
type Draft = { title: string; description: string; asking_price_amount: string; available_quantity: string } & Record<(typeof textFields)[number][0], string>;
function draftFor(p: OwnerProduct | null): Draft {
  return { title: p?.title ?? "", description: p?.description ?? "", asking_price_amount: p?.asking_price_amount?.toString() ?? "", available_quantity: String(p?.available_quantity ?? 0), category: p?.category ?? "", franchise: p?.franchise ?? "", manufacturer: p?.manufacturer ?? "", release_region: p?.release_region ?? "", language: p?.language ?? "", private_sku: p?.private_sku ?? "", condition_description: p?.condition_description ?? "", packaging_description: p?.packaging_description ?? "" };
}

export default function StoreProductManager(props: Props) {
  const [list, setList] = useState<ProductList | null>(null);
  const [selected, setSelected] = useState<OwnerProduct | null | undefined>(undefined);
  const [error, setError] = useState("");
  const load = async (offset = list?.offset ?? 0) => { setList(await storeRequest<ProductList>(`/api/stores/owner/products?offset=${offset}`)); setError(""); };
  useEffect(() => { let active = true; storeRequest<ProductList>("/api/stores/owner/products").then(data => { if (active) setList(data); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, []);
  if (selected !== undefined) return <ProductEditor key={selected?.id ?? "new"} {...props} initial={selected} close={async () => { setSelected(undefined); props.setDirty(false); await load(); }} />;
  return <section className={s.panel}><div className={s.row}><div><h2>Custom collectibles</h2><p className={s.muted}>Your own listings, prices and vendor-reported quantities. Drafts stay private.</p></div><button className={s.primary} disabled={props.busy || !props.canEdit} onClick={() => setSelected(null)}>Add collectible</button></div>
    {!props.canEdit && <p className={s.muted}>New custom listings are currently unavailable. Retained listings can still be inspected, unpublished or archived.</p>}
    {error && <p role="alert">{error}</p>}
    <div className={s.actions}><button disabled={props.busy} onClick={() => props.task(() => load(), "Collectibles refreshed.")}>Refresh collectibles</button><span className={s.muted}>{list?.total ?? 0} listings, including drafts and archived records</span></div>
    {list?.products.length ? <div className={s.tableWrap}><table className={s.table}><thead><tr><th>Collectible</th><th>Price</th><th>Quantity</th><th>Status</th><th /></tr></thead><tbody>{list.products.map(p => <tr key={p.id}><td><strong>{p.title || "Untitled draft"}</strong><small>{p.private_sku ? `SKU: ${p.private_sku}` : p.category || "Custom collectible"}</small></td><td>{p.asking_price_amount === null ? "Not set" : `${p.asking_price_currency} ${p.asking_price_amount.toFixed(2)}`}</td><td>{p.available_quantity}</td><td><span className={s.badge}>{p.archived_at ? "Archived" : p.published ? "Published" : "Draft"}</span>{p.ineligible_reason && <small>{p.ineligible_reason}</small>}</td><td><button disabled={props.busy} onClick={() => setSelected(p)}>Edit {p.title || "draft"}</button></td></tr>)}</tbody></table></div> : <div className={s.empty}><h3>{list ? "Your first collectible starts here" : "Loading collectibles…"}</h3><p className={s.muted}>Create a draft, add photos and details, then explicitly publish when ready.</p></div>}
    <div className={s.actions}><button disabled={props.busy || !list || list.offset === 0} onClick={() => props.task(() => load(Math.max(0, (list?.offset ?? 0) - 40)), "")}>Previous collectibles</button><button disabled={props.busy || !list || list.offset + list.limit >= list.total} onClick={() => props.task(() => load((list?.offset ?? 0) + 40), "")}>Next collectibles</button></div>
  </section>;
}

function ProductEditor({ initial, close, owner, canEdit, busy, task, setDirty }: Props & { initial: OwnerProduct | null; close: () => Promise<void> }) {
  const [product, setProduct] = useState(initial), [draft, setDraft] = useState(() => draftFor(initial));
  const [dirty, markDirty] = useState(false);
  const dirtyState = (value: boolean) => { markDirty(value); setDirty(value); };
  const field = (name: keyof Draft, value: string) => { setDraft({ ...draft, [name]: value }); dirtyState(true); };
  const editable = canEdit && !product?.archived_at;
  const locked = busy || dirty || !editable;
  const mutate = async (action: string, data: Record<string, unknown> = {}) => { const p = await productChange(product, action, data); setProduct(p); return p; };
  return <>
    <div className={s.row}><button disabled={busy} onClick={() => { if (dirty && !window.confirm("Discard unsaved collectible changes?")) return; void task(close, ""); }}>← All collectibles</button><div className={s.actions}>{product && <span className={s.badge}>{product.archived_at ? "Archived" : product.published ? "Published" : "Draft"}</span>}{product && <Link className={s.linkButton} href={`/store/${owner.store!.slug}/products/${product.id}?preview=1`} target="_blank">Preview collectible ↗</Link>}</div></div>
    <section className={s.panel}><h2>{product ? "Edit collectible" : "New collectible"}</h2><p className={s.muted}>Seller-provided details. Saving never turns publication on. Changes to an already published listing update its public details.</p>
      {product?.ineligible_reason && <div className={s.notice}>Before publishing: {product.ineligible_reason}</div>}
      <form onSubmit={e => { e.preventDefault(); if (product?.published && !window.confirm("Save changes to this published listing?")) return; void task(async () => { const p = await mutate("save", { ...draft, asking_price_amount: draft.asking_price_amount === "" ? null : Number(draft.asking_price_amount), available_quantity: Number(draft.available_quantity) }); setDraft(draftFor(p)); dirtyState(false); }, "Collectible saved. Publication status shown below."); }}>
        <fieldset disabled={busy || !editable} className={s.stack}><label>Title<input maxLength={120} value={draft.title} onChange={e => field("title", e.target.value)} /></label><label>Description<textarea maxLength={4000} value={draft.description} onChange={e => field("description", e.target.value)} /></label><div className={s.grid}><label>Asking price (USD)<input type="number" min={0} max={99999999.99} step="0.01" value={draft.asking_price_amount} onChange={e => field("asking_price_amount", e.target.value)} /></label><label>Available quantity<input aria-label="Available quantity" required type="number" min={0} max={1000000} step={1} value={draft.available_quantity} onChange={e => field("available_quantity", e.target.value)} /><span className={s.muted}>Vendor-reported. Zero stock unpublishes; restocking requires republishing.</span></label></div><div className={s.grid}>{textFields.map(([key,label,max]) => <label key={key}>{label}<input aria-label={label} maxLength={max} value={draft[key]} onChange={e => field(key, e.target.value)} />{key === "private_sku" && <span className={s.muted}>Visible only to you.</span>}</label>)}</div><div><button className={s.primary} type="submit">{product ? "Save collectible changes" : "Save collectible draft"}</button></div></fieldset>
      </form>
      {product && <div className={s.actions}><button disabled={busy} onClick={() => { if (dirty && !window.confirm("Discard unsaved edits and reload the latest version?")) return; void task(async () => { const data = await storeRequest<ProductList>(`/api/stores/owner/products?id=${product.id}`); if (!data.products[0]) throw new Error("Product unavailable"); setProduct(data.products[0]); setDraft(draftFor(data.products[0])); dirtyState(false); }, "Latest version loaded."); }}>Reload latest version</button><span className={s.muted}>{dirty ? "Unsaved changes — save before changing photos, sections or publication." : "Changes are saved."}</span></div>}
    </section>
    {!product ? <section className={s.empty}><h3>Photos come next</h3><p className={s.muted}>Save this draft first to upload up to eight photos, assign sections and preview.</p></section> : <>
      <section className={s.panel}><h2>Photos</h2><p className={s.muted}>Up to eight JPEG, PNG or WebP images, 5 MB each. The first is the cover image.</p><div className={s.photoGrid}>{product.photo_paths.map((path, i) => <div key={path}><img alt={`Collectible photo ${i + 1}`} src={`/api/stores/owner/media?product=${product.id}&photo=${encodeURIComponent(path.split("/").pop()!)}`} /><div className={s.actions}><button aria-label={`Move photo ${i + 1} earlier`} disabled={locked || i === 0} onClick={() => task(async () => { const paths = [...product.photo_paths]; [paths[i-1], paths[i]] = [paths[i], paths[i-1]]; await mutate("photos", { paths }); })}>←</button><button aria-label={`Move photo ${i + 1} later`} disabled={locked || i === product.photo_paths.length - 1} onClick={() => task(async () => { const paths = [...product.photo_paths]; [paths[i], paths[i+1]] = [paths[i+1], paths[i]]; await mutate("photos", { paths }); })}>→</button><button disabled={locked} aria-label={`Remove photo ${i+1}`} onClick={() => task(async () => { await mutate("photos", { paths: product.photo_paths.filter(p => p !== path) }); }, "Photo removed. Removing the final photo unpublishes the listing.")}>Remove</button></div></div>)}</div><div className={s.actions}><label>Add photos<input className={s.file} type="file" multiple accept="image/png,image/jpeg,image/webp" disabled={locked || product.photo_paths.length >= 8} onChange={e => { const files = Array.from(e.target.files ?? []); e.target.value = ""; if (files.length) void task(async () => { if (files.length + product.photo_paths.length > 8) throw new Error("Up to eight photos per collectible."); const paths = [...product.photo_paths]; for (const file of files) paths.push(await uploadStoreImage(file, "product", product.id)); await mutate("photos", { paths }); }, "Photos attached."); }} /></label></div></section>
      <section className={s.panel}><h2>Sections</h2><p className={s.muted}>Choose from the sections selected for this store.</p>{owner.sections.filter(section => section.selected).map(section => <label className={s.check} key={section.id}><input type="checkbox" checked={product.section_ids.includes(section.id)} disabled={locked} onChange={e => { const ids = e.target.checked ? [...product.section_ids, section.id] : product.section_ids.filter(id => id !== section.id); void task(async () => { await mutate("sections", { section_ids: ids }); }); }} />{section.name}</label>)}</section>
      <section className={s.panel}><h2>Publication</h2><p className={s.muted}>Publishing a collectible makes it available only in store destinations you have also published. An archived listing retains its history.</p><div className={s.actions}><button className={s.primary} disabled={busy || dirty || Boolean(product.archived_at) || (!product.published && (!editable || Boolean(product.ineligible_reason)))} onClick={() => { if (!window.confirm(`${product.published ? "Unpublish" : "Publish"} this collectible?`)) return; void task(async () => { await mutate(product.published ? "unpublish" : "publish"); }, "Publication updated."); }}>{product.published ? "Unpublish collectible" : "Publish collectible"}</button><button disabled={busy || dirty || Boolean(product.archived_at)} onClick={() => { if (!window.confirm("Archive this collectible? It will be removed from public listings and retained in your records.")) return; void task(async () => { await mutate("archive"); }, "Collectible archived."); }}>Archive collectible</button></div></section>
    </>}
  </>;
}
