"use client";
/* eslint-disable @next/next/no-img-element -- Owner images require session cookies and uncached media authorization, not the shared optimizer. */
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { createWallSectionAction } from "@/lib/wallSections/createWallSectionAction";
import { ownerChange, storeRequest, uploadStoreImage, type OwnerModel } from "./storeManagerClient";
import StoreProductManager from "./StoreProductManager";
import { useStoreDraftGuard } from "./useStoreDraftGuard";
import s from "./StoreManager.module.css";

export type StoreTask = (work: () => Promise<void>, message?: string) => Promise<void>;
const tabs = ["Overview", "Store details", "Vault inventory", "Custom collectibles", "Sections"] as const;
export default function StoreManager() {
  const [owner, setOwner] = useState<OwnerModel | null>(null);
  const [tab, setTab] = useState<string>("Overview");
  const [busy, setBusy] = useState(false), [dirty, setDirty] = useState(false);
  const [notice, setNotice] = useState(""), [error, setError] = useState("");
  const [query, setQuery] = useState("");
  const load = useCallback(async (params = "") => { setOwner(await storeRequest<OwnerModel>(`/api/stores/owner${params ? `?${params}` : ""}`)); }, []);
  const task: StoreTask = async (work, message = "Saved.") => {
    setBusy(true); setError(""); setNotice("");
    try { await work(); setNotice(message); } catch (e) { setError(e instanceof Error ? e.message : "Could not save. Please retry."); }
    finally { setBusy(false); }
  };
  useEffect(() => { let active = true; storeRequest<OwnerModel>("/api/stores/owner").then(data => { if (active) setOwner(data); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, []);
  useStoreDraftGuard(dirty);
  const navigate = (next: string) => { if (dirty && !window.confirm("Discard your unsaved changes?")) return; setDirty(false); setTab(next); setError(""); setNotice(""); };
  const store = owner?.store;
  const canEdit = Boolean(owner?.capabilities.store_app && owner?.rollout.app_enabled);
  const refresh = () => load(query);
  return <div className={s.workspace}>
    <header className={s.header}><div><span className={s.eyebrow}>Vendor workspace</span><h1>{store?.display_name || "Your store"}</h1><p className={s.muted}>A home for your inventory. Manage it all from your computer.</p></div>
      <div className={s.actions}><Link className={s.linkButton} href="/account" target="_blank">Account & sharing</Link>{store && <Link className={s.linkButton} href={`/store/${store.slug}?preview=1`} target="_blank">Preview store ↗</Link>}</div></header>
    {error && <div className={`${s.notice} ${s.error}`} role="alert">{error} {error.includes("session ended") && <Link href="/login?next=%2Faccount%2Fstore" target="_blank">Sign in</Link>}</div>}
    {notice && <div className={s.notice} role="status">{notice}</div>}
    {!owner ? <div className={s.panel}><p role="status">{error ? "Your store could not be loaded." : "Loading your workspace…"}</p><button disabled={busy} onClick={() => task(refresh, "")}>Retry</button></div> : <div className={s.shell}>
      <nav className={s.sidebar} aria-label="Store management">{tabs.map(name => <button key={name} disabled={busy} aria-pressed={tab === name} onClick={() => navigate(name)}>{name}</button>)}<small>Browse-only listings.<br />Customers can view your offers; checkout is not enabled.</small></nav>
      <main className={s.stack} aria-busy={busy}>
        {!canEdit && <div className={s.notice}>Store editing is not available for this account. You can still inspect retained data, preview, remove listings and unpublish.</div>}
        {tab === "Overview" && <>
          <div className={s.stats}><div className={s.stat}><span className={s.muted}>In the app</span><strong>{store?.app_published ? "Published" : "Not published"}</strong></div><div className={s.stat}><span className={s.muted}>On the web</span><strong>{store?.web_published ? "Published" : "Not published"}</strong></div><div className={s.stat}><span className={s.muted}>Store access</span><strong>{owner.capabilities.store_web ? "App + web" : owner.capabilities.store_app ? "App" : "Inactive"}</strong></div></div>
          <section className={s.panel}><h2>{store ? "Add to your storefront" : "Make it your own"}</h2><p className={s.muted}>{store ? "Choose exact copies from your Vault, or create custom listings for other collectibles. Each listing is selected or published explicitly." : "Start with a store name and URL, then add your branding and inventory. Saving a store creates a private draft."}</p><div className={s.actions}><button className={s.primary} onClick={() => navigate(store ? "Custom collectibles" : "Store details")}>{store ? "Add a collectible" : "Set up your store"}</button>{store && <button onClick={() => navigate("Vault inventory")}>Choose Vault copies</button>}</div></section>
          <section className={s.panel}><h2>Catalog cards & your Vault</h2><p className={s.muted}>Use the existing catalog and import tools to add owned cards. Set exact-copy prices, condition and sale intent in your Vault, then choose which copies appear in your store.</p><div className={s.actions}><Link className={s.linkButton} href="/explore" target="_blank">Find & add cards ↗</Link><Link className={s.linkButton} href="/vault/import" target="_blank">Import inventory ↗</Link><Link className={s.linkButton} href="/vault" target="_blank">Manage Vault ↗</Link></div></section>
          {store && <section className={s.panel}><h2>Preview & publication</h2><p className={s.muted}>Review your store before publishing. Profile and Vault sharing must be enabled. App and web publication are separate choices.</p><div className={s.actions}>{(["app", "web"] as const).map(surface => { const published = store[`${surface}_published`]; return <button key={surface} className={published ? "" : s.primary} disabled={busy || (!published && (!canEdit || !owner.capabilities[`store_${surface}`] || !owner.rollout[`${surface}_enabled`]))} onClick={() => { if (!window.confirm(`${published ? "Unpublish" : "Publish"} your store ${surface === "web" ? "on the public web" : "in the app"}?`)) return; void task(async () => { await ownerChange({ action: "publish", surface, publish: !published }); await refresh(); }, published ? "Store unpublished." : "Store published."); }}>{published ? "Unpublish" : "Publish"} {surface === "web" ? "web store" : "in app"}</button>; })}</div><p className={s.muted}>Owner web preview is available even when your package includes only app publication.</p></section>}
        </>}
        {tab === "Store details" && <StoreDetails key={store?.id ?? "new"} owner={owner} canEdit={canEdit} busy={busy} task={task} refresh={refresh} setDirty={setDirty} />}
        {tab === "Vault inventory" && <Inventory initialQuery={query} owner={owner} canEdit={canEdit} busy={busy} task={task} load={async params => { await load(params); setQuery(params); }} refresh={refresh} />}
        {tab === "Custom collectibles" && (store ? <StoreProductManager owner={owner} canEdit={canEdit && Boolean(owner.rollout.custom_enabled)} busy={busy} task={task} setDirty={setDirty} /> : <Empty message="Save your store details before adding collectibles." />)}
        {tab === "Sections" && (store ? <StoreSections owner={owner} canEdit={canEdit} busy={busy} task={task} refresh={refresh} /> : <Empty message="Save your store details before selecting sections." />)}
      </main>
    </div>}
  </div>;
}
function Empty({ message }: { message: string }) { return <div className={s.empty}><h2>Nothing here yet</h2><p className={s.muted}>{message}</p></div>; }

function StoreDetails({ owner, canEdit, busy, task, refresh, setDirty }: { owner: OwnerModel; canEdit: boolean; busy: boolean; task: StoreTask; refresh: () => Promise<void>; setDirty: (v: boolean) => void }) {
  const store = owner.store;
  const [name, setName] = useState(store?.display_name ?? ""), [slug, setSlug] = useState(store?.slug ?? ""), [description, setDescription] = useState(store?.description ?? "");
  return <><section className={s.panel}><h2>Store identity</h2><p className={s.muted}>Your business identity is separate from your collector profile.</p><form onChange={() => setDirty(true)} onSubmit={e => { e.preventDefault(); void task(async () => { await ownerChange({ action: "save", slug, display_name: name, description }); setDirty(false); await refresh(); }); }}><fieldset disabled={busy || !canEdit} className={s.stack}><div className={s.grid}><label>Store name<input required maxLength={80} value={name} onChange={e => setName(e.target.value)} /></label><label>Store URL slug<input aria-label="Store URL slug" required minLength={3} maxLength={63} value={slug} disabled={Boolean(store?.first_published_at)} onChange={e => setSlug(e.target.value)} /><span className={s.muted}>{store?.first_published_at ? "Fixed after first publication." : "Letters, numbers and hyphens. Fixed after first publication."}</span></label></div><label>About your store<textarea maxLength={1000} value={description} onChange={e => setDescription(e.target.value)} /></label><div><button className={s.primary} type="submit">{store ? "Save store details" : "Create draft store"}</button></div></fieldset></form></section>
    {store && <section className={s.panel}><h2>Branding</h2><p className={s.muted}>JPEG, PNG or WebP, up to 5 MB. Uploads stay private until the store is published.</p><div className={s.grid}>{(["logo", "banner"] as const).map(kind => <div key={kind}><h3>{kind === "logo" ? "Store logo" : "Store banner"}</h3>{store[`${kind}_path`] && <img className={s.brandImage} alt={`Current store ${kind}`} src={`/api/stores/owner/media?kind=${kind}&v=${encodeURIComponent(store[`${kind}_path`]!)}`} />}<label>Upload {kind}<input className={s.file} type="file" accept="image/png,image/jpeg,image/webp" disabled={busy || !canEdit} onChange={e => { const file = e.target.files?.[0]; e.target.value = ""; if (file) void task(async () => { const path = await uploadStoreImage(file, kind); await ownerChange({ action: "media", kind, path }); await refresh(); }, "Branding updated."); }} /></label>{store[`${kind}_path`] && <button disabled={busy || !canEdit} onClick={() => task(async () => { await ownerChange({ action: "media", kind, path: null }); await refresh(); })}>Remove {kind}</button>}</div>)}</div></section>}
  </>;
}

function Inventory({ initialQuery, owner, canEdit, busy, task, load, refresh }: { initialQuery: string; owner: OwnerModel; canEdit: boolean; busy: boolean; task: StoreTask; load: (q: string) => Promise<void>; refresh: () => Promise<void> }) {
  const initial = new URLSearchParams(initialQuery);
  const [q, setQ] = useState(initial.get("q") ?? ""), [condition, setCondition] = useState(initial.get("condition") ?? ""), [kind, setKind] = useState(initial.get("kind") ?? "catalog");
  const inventory = owner.inventory;
  const search = (offset: number) => load(new URLSearchParams({ q, condition, kind, offset: String(offset) }).toString());
  if (!owner.store) return <Empty message="Create your store, then choose existing eligible Vault copies." />;
  return <section className={s.panel}><div className={s.row}><div><h2>Vault inventory</h2><p className={s.muted}>One row per physical copy. Ineligible copies stay visible here with a reason.</p></div><Link className={s.linkButton} href="/explore" target="_blank">Add catalog cards ↗</Link></div><form className={s.filters} onSubmit={e => { e.preventDefault(); void task(() => search(0), ""); }}><label>Search copies<input maxLength={120} placeholder="Name, GV-ID or GVVI" value={q} onChange={e => setQ(e.target.value)} /></label><label>Condition<select value={condition} onChange={e => setCondition(e.target.value)}><option value="">All conditions</option>{["NM","LP","MP","HP","DMG"].map(c => <option key={c}>{c}</option>)}</select></label><label>Type<select value={kind} onChange={e => setKind(e.target.value)}><option value="catalog">All copies</option><option value="raw">Raw</option><option value="slab">Graded</option></select></label><button disabled={busy} type="submit">Apply</button></form>
    <div className={s.row}><span className={s.muted}>{inventory?.total ?? 0} matching copies</span><button disabled={busy} onClick={() => task(refresh, "Inventory refreshed.")}>Refresh inventory</button></div>
    {!inventory?.items.length ? <Empty message="Add cards to your Vault or try a different search." /> : <div className={s.tableWrap}><table className={s.table}><thead><tr><th>Exact copy</th><th>Condition / finish</th><th>Asking price</th><th>Store selection</th><th>Manage</th></tr></thead><tbody>{inventory.items.map(item => item.entry_type !== "catalog_copy" ? null : <tr key={item.id}><td><strong>{item.display_name || item.name}</strong><small>{item.gv_vi_id}</small><small>{item.printing_gv_id || "Printing unassigned"}</small></td><td>{item.condition_label || "Not set"}<small>{item.finish_label || "—"}</small></td><td>{item.asking_price_amount ? `${item.asking_price_currency} ${item.asking_price_amount.toFixed(2)}` : "Not set"}</td><td><label className={s.check}><input type="checkbox" aria-label={`Select ${item.gv_vi_id}`} checked={Boolean(item.selected)} disabled={busy || (!item.selected && (!canEdit || Boolean(item.ineligible_reason)))} onChange={e => { const selected = e.target.checked; if (selected && (owner.store?.app_published || owner.store?.web_published) && !window.confirm("Add this copy to your published store?")) return; void task(async () => { await ownerChange({ action: "item", instance_id: item.id, selected }); await refresh(); }, selected ? "Copy selected." : "Copy removed from store."); }} />{item.selected ? "Selected" : "Not selected"}</label>{item.ineligible_reason && <small>{item.ineligible_reason}</small>}</td><td><Link href={`/vault/gvvi/${encodeURIComponent(item.gv_vi_id)}`} target="_blank">Edit price & copy ↗</Link></td></tr>)}</tbody></table></div>}
    <div className={s.row}><button disabled={busy || !inventory || inventory.offset === 0} onClick={() => task(() => search(Math.max(0, (inventory?.offset ?? 0) - 40)), "")}>Previous copies</button><span className={s.muted}>Page {Math.floor((inventory?.offset ?? 0) / 40) + 1}</span><button disabled={busy || !inventory || inventory.offset + inventory.limit >= inventory.total} onClick={() => task(() => search((inventory?.offset ?? 0) + 40), "")}>Next copies</button></div>
  </section>;
}
function StoreSections({ owner, canEdit, busy, task, refresh }: { owner: OwnerModel; canEdit: boolean; busy: boolean; task: StoreTask; refresh: () => Promise<void> }) {
  const [name, setName] = useState("");
  return <section className={s.panel}><h2>Store sections</h2><p className={s.muted}>Choose existing Wall sections and their order. Creating a Wall section makes it available on your collector Wall; it does not select it for this store. Store sections show only selected eligible copies and explicitly assigned custom listings.</p><form className={s.actions} onSubmit={e => { e.preventDefault(); void task(async () => { const result = await createWallSectionAction({ name }); if (!result.ok) throw new Error(result.message); setName(""); await refresh(); }, "Wall section created. Select it below to use it in this store."); }}><label>New Wall section<input required maxLength={40} value={name} onChange={e => setName(e.target.value)} /></label><button type="submit" disabled={busy || !canEdit}>Create section</button></form><div className={s.actions}><Link href="/account" target="_blank">Rename or manage Wall sections ↗</Link></div>
    {owner.sections.map(section => <div className={`${s.row} ${s.sectionRow}`} key={section.id}><label className={s.check}><input type="checkbox" checked={section.selected} disabled={busy || (!section.selected && !canEdit)} onChange={e => { const selected = e.target.checked; void task(async () => { await ownerChange({ action: "section", section_id: section.id, selected, position: section.position ?? owner.sections.length }); await refresh(); }); }} />{section.name}</label>{section.selected && <label>Display order<input aria-label={`Order for ${section.name}`} type="number" min={0} max={10000} defaultValue={section.position ?? 0} key={`${section.id}-${section.position}`} disabled={busy || !canEdit} onBlur={e => { const position = Number(e.target.value); if (position !== section.position && Number.isInteger(position) && position >= 0) void task(async () => { await ownerChange({ action: "section", section_id: section.id, selected: true, position }); await refresh(); }); }} /></label>}</div>)}
  </section>;
}
