import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import net from 'node:net';
import {randomUUID,createHash} from 'node:crypto';
import {execFileSync,spawn} from 'node:child_process';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import pg from 'pg';
import {localSupabaseStatusSecret} from '../../scripts/lib/local_supabase_cli_status_v1.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url)),requireWeb=createRequire(root+'apps/web/package.json');
const {createClient}=requireWeb('@supabase/supabase-js'),{chromium,webkit,expect}=requireWeb('@playwright/test');
const fixture='C:/gv_store_seller_link_20260928/.local/integration/seller-adoption-v2/replay-409',project='grookai-seller-review-20260929';
const out='C:/grookai_vault_operator_artifacts/web_import_recovery_20260929',web='http://127.0.0.1:58256',api='http://127.0.0.1:31021';
const hash=x=>createHash('sha256').update(x).digest('hex');
const docker=(...args)=>execFileSync('docker',args,{encoding:'utf8',windowsHide:true,timeout:60000,maxBuffer:16*1024*1024});
test('web imports: actual Auth, atomic receipts, browser retry and saved readback',{skip:process.env.GV_RUN_WEB_IMPORT_RECOVERY!=='1',timeout:240000},async t=>{
 const freeze=JSON.parse(fs.readFileSync(fixture+'/receipt.json'));assert.equal(freeze.project,project);assert.equal(Object.keys(freeze.sourceHashes).length,409);
 assert.equal(freeze.status,'passed');assert.equal(freeze.fullReplay,true);assert.ok(!fs.existsSync(fixture+'/supabase/.temp/project-ref'));
 assert.equal(hash(fs.readFileSync(fixture+'/supabase/config.toml')),JSON.parse(fs.readFileSync(fixture+'/intent.json')).configSha256);
 assert.equal(fs.readdirSync(root+'supabase/migrations').filter(n=>n.endsWith('.sql')).length,409);
 for(const [name,digest]of Object.entries(freeze.sourceHashes)){assert.equal(hash(fs.readFileSync(root+'supabase/migrations/'+name)),digest);assert.equal(hash(fs.readFileSync(fixture+'/supabase/migrations/'+name)),digest);}
 const inspect=n=>JSON.parse(docker('inspect',n))[0];assert.equal(inspect('supabase_db_'+project).State.Running,true);
 assert.deepEqual(Object.keys(inspect('supabase_db_'+project).NetworkSettings.Networks),[project]);assert.equal(JSON.parse(docker('network','inspect',project))[0].Internal,true);
 const relay=inspect(project+'-relay'),relayWasRunning=relay.State.Running;
 for(const bindings of Object.values(relay.HostConfig.PortBindings))for(const b of bindings)assert.equal(b.HostIp,'127.0.0.1');
 await new Promise((resolve,reject)=>{const s=net.createServer();s.once('error',reject);s.listen(58256,'127.0.0.1',()=>s.close(resolve));});
 const run=out+'/acceptance-'+Date.now();fs.mkdirSync(run,{recursive:true});const save=(n,v)=>fs.writeFileSync(run+'/'+n,JSON.stringify(v,null,2),{flag:'wx'});
 save('intent.json',{at:new Date().toISOString(),project,api,web,relayWasRunning,scope:'Fresh synthetic accounts/catalog only; no reset or migration; preserve existing rows'});
 if(!relayWasRunning)docker('start',project+'-relay');
 const status=JSON.parse(execFileSync('supabase',['status','--workdir',fixture,'--output','json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));assert.equal(status.API_URL,api);
 const db=new pg.Client({host:'127.0.0.1',port:31022,user:'postgres',password:'postgres',database:'postgres',statement_timeout:15000});await db.connect();
 let child,browser;const checks=[],screenshots=[];let before;
 const snap=async()=>{const value={};for(const table of ['vault_item_instances','vault_items','vault_import_receipts_v1','slab_certs'])value[table]=(await db.query('select * from public.'+table+' order by 1,2')).rows;return value;};
 const admin=createClient(api,localSupabaseStatusSecret(status),{auth:{persistSession:false,autoRefreshToken:false}});
 async function account(){const email=randomUUID()+'@web-import-fixture.invalid',password='Fixture-'+randomUUID()+'!';const r=await admin.auth.admin.createUser({email,password,email_confirm:true});assert.equal(r.error,null);return{id:r.data.user.id,email,password};}
 async function seed(){const setName='Import fixture '+randomUUID();const set=(await db.query("insert into public.sets(code,name,game) values($1,$2,'pokemon') returning id",[randomUUID(),setName])).rows[0].id;const gvId='GV-PK-IMPORT-'+randomUUID();const card=(await db.query("insert into public.card_prints(set_id,name,number,variant_key,gv_id,game_id) values($1,'Synthetic import card','065/165','normal',$2,(select id from games where code='pokemon')) returning id",[set,gvId])).rows[0].id;return{card,gvId,setName};}
 const rows=(f,n)=>({status:'matched',match:{card_id:f.card,gv_id:f.gvId},row:{quantity:n,condition:'LP',cost:4.25,notes:'Synthetic recovery note'}});
 const count=async(user,f)=>(await db.query('select count(*)::int n from vault_item_instances where user_id=$1 and card_print_id=$2 and archived_at is null',[user.id,f.card])).rows[0].n;
 const receipts=async(user,id)=>(await db.query('select * from vault_import_receipts_v1 where user_id=$1 and request_id=$2',[user.id,id])).rows;
 async function check(name,fn){let failure;await t.test(name,async()=>{try{await fn();checks.push(name);}catch(e){failure=e;throw e;}});if(failure)throw failure;}
 try{
  assert.equal((await db.query('show max_worker_processes')).rows[0].max_worker_processes,'0');assert.equal((await db.query('select count(*)::int n from cron.job_run_details')).rows[0].n,0);
  assert.deepEqual((await db.query('select version from supabase_migrations.schema_migrations order by version')).rows.map(r=>r.version),Object.keys(freeze.sourceHashes).sort().map(n=>n.split('_')[0]));before=await snap();save('before.private.json',before);
  const owner=await account(),other=await account();save('accounts.private.json',[owner,other]);
  const harness=run+'/web';fs.mkdirSync(harness+'/app/vault/import',{recursive:true});fs.mkdirSync(harness+'/app/login',{recursive:true});fs.symlinkSync(root+'apps/web/node_modules',harness+'/node_modules','junction');
  fs.writeFileSync(harness+'/package.json',JSON.stringify({private:true}));fs.writeFileSync(harness+'/tsconfig.json',JSON.stringify({compilerOptions:{target:'ES2020',lib:['dom','esnext'],jsx:'react-jsx',module:'esnext',moduleResolution:'bundler',esModuleInterop:true,skipLibCheck:true,paths:{'@/*':[path.join(root,'apps/web/src/*').replaceAll('\\','/')]}}}));
  fs.writeFileSync(harness+'/next.config.mjs',`export default {devIndicators:false,webpack(config){config.resolve.alias['@']=${JSON.stringify(path.join(root,'apps/web/src'))};return config;}};`);
  fs.writeFileSync(harness+'/app/Ready.tsx','"use client";import {useEffect,useState} from "react";export default function Ready(){const [r,s]=useState(false);useEffect(()=>s(true),[]);return <span hidden data-fixture-ready={String(r)}/>;}');
  fs.writeFileSync(harness+'/app/layout.tsx','import "./ui.css";import Ready from "./Ready";export default function Layout({children}){return <html><body>{children}<Ready/></body></html>}');
  fs.writeFileSync(harness+'/app/vault/import/page.tsx','export {default,dynamic,revalidate} from "@/app/vault/import/page";');
  fs.writeFileSync(harness+'/app/page.tsx',`import {createServerComponentClient} from '@/lib/supabase/server';import {importVaultItems} from '@/lib/import/importVaultItems';import {redirect} from 'next/navigation';
async function login(form:FormData){'use server';const c=await createServerComponentClient();const r=await c.auth.signInWithPassword({email:String(form.get('email')),password:String(form.get('password'))});redirect('/?result='+encodeURIComponent(JSON.stringify({login:!r.error})));}
async function raw(form:FormData){'use server';const i=JSON.parse(String(form.get('input')));const r=await importVaultItems(i.rows,i.attempt);redirect('/?result='+encodeURIComponent(JSON.stringify(r)));}
export default async function Page({searchParams}){const p=await searchParams;return <main><pre id="result">{p.result||'{}'}</pre><form action={login}><input name="email"/><input name="password" type="password"/><button>Login</button></form><form action={raw}><textarea name="input"/><button>Submit raw</button></form></main>}`);
  fs.writeFileSync(harness+'/app/login/page.tsx','export {default} from "../page";');
  fs.writeFileSync(harness+'/tailwind.config.cjs',`module.exports={content:[${JSON.stringify(path.join(root,'apps/web/src/app/vault/import/*.tsx').replaceAll('\\','/'))},'./app/**/*.tsx'],theme:{extend:{}},plugins:[]};`);
  execFileSync(process.execPath,[requireWeb.resolve('tailwindcss/lib/cli.js'),'-i',root+'apps/web/src/app/globals.css','-c',harness+'/tailwind.config.cjs','-o',harness+'/app/ui.css'],{cwd:harness,stdio:'pipe',windowsHide:true});
  const env={};for(const key of ['SystemRoot','SYSTEMROOT','WINDIR','PATH','Path','PATHEXT','TEMP','TMP','USERPROFILE','APPDATA','LOCALAPPDATA','COMSPEC','ComSpec'])if(process.env[key])env[key]=process.env[key];
  Object.assign(env,{NEXT_TELEMETRY_DISABLED:'1',SUPABASE_URL:api,NEXT_PUBLIC_SUPABASE_URL:api,SUPABASE_PUBLISHABLE_KEY:status.ANON_KEY,NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:status.ANON_KEY,SUPABASE_SECRET_KEY:localSupabaseStatusSecret(status)});
  const fd=fs.openSync(harness+'/server.private.log','wx');child=spawn(process.execPath,[requireWeb.resolve('next/dist/bin/next'),'dev','--webpack','--hostname','127.0.0.1','--port','58256'],{cwd:harness,env,stdio:['ignore',fd,fd],windowsHide:true});fs.closeSync(fd);
  let ready=false;for(let i=0;i<75;i++){try{if((await fetch(web,{signal:AbortSignal.timeout(5000)})).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,400));}assert.ok(ready);
  const pageFor=async()=>{const context=await browser.newContext({viewport:{width:390,height:844}});await context.route('**/*',r=>new URL(r.request().url()).origin===web?r.continue():r.abort());return context.newPage();};
  const go=async(page,url)=>{await page.goto(url,{waitUntil:'domcontentloaded'});await page.locator('[data-fixture-ready="true"]').waitFor({state:'attached'});};
  const login=async(page,user)=>{await go(page,web);await page.locator('[name=email]').fill(user.email);await page.locator('[name=password]').fill(user.password);await page.getByRole('button',{name:'Login',exact:true}).click();await page.waitForURL(u=>u.searchParams.get('result')==='{"login":true}');};
  const raw=async(page,list,id,userId=owner.id)=>{await go(page,web);await page.locator('[name=input]').fill(JSON.stringify({rows:list,attempt:{ownerId:userId,requestId:id}}));await page.getByRole('button',{name:'Submit raw',exact:true}).click();await page.waitForURL(u=>u.searchParams.has('result'));return JSON.parse(await page.locator('#result').innerText());};
  browser=await chromium.launch({headless:true});let page=await pageFor();await login(page,owner);
  await check('actual action rejects a forged owner before writes',async()=>{const f=await seed(),r=await raw(page,[rows(f,2)],randomUUID(),other.id);assert.equal(r.errorCode,'account_changed');assert.equal(await count(owner,f),0);assert.equal(await count(other,f),0);});
  await check('atomic multi-card import and replay preserve one receipt and archived copies',async()=>{const a=await seed(),b=await seed(),id=randomUUID(),list=[rows(a,3),rows(b,2)];const r=await raw(page,list,id);assert.equal(r.ok,true);assert.equal(r.importedCards,5);assert.equal(await count(owner,a),3);assert.equal(await count(owner,b),2);assert.deepEqual(await raw(page,list,id),r);assert.equal((await receipts(owner,id)).length,1);await db.query('update vault_item_instances set archived_at=now() where id=(select id from vault_item_instances where user_id=$1 and card_print_id=$2 limit 1)',[owner.id,a.card]);assert.deepEqual(await raw(page,list,id),r);assert.equal(await count(owner,a),2);const conflict=await raw(page,[rows(a,4),rows(b,2)],id);assert.equal(conflict.errorCode,'conflict');assert.equal(await count(owner,a),2);});
  await check('late canonical mismatch rolls back whole batch and persists a failed receipt',async()=>{const fixtures=[await seed(),await seed()].sort((a,b)=>a.card.localeCompare(b.card));const list=fixtures.map(f=>rows(f,2));list[1].match.gv_id='GV-PK-WRONG';const id=randomUUID(),r=await raw(page,list,id);assert.equal(r.errorCode,'failed');for(const f of fixtures)assert.equal(await count(owner,f),0);const saved=await receipts(owner,id);assert.equal(saved[0].status,'failed');assert.equal((await raw(page,list,id)).errorCode,'failed');assert.equal((await receipts(owner,id)).length,1);const fixed=await raw(page,fixtures.map(f=>rows(f,2)),randomUUID());assert.equal(fixed.importedCards,4);});
  await page.context().close();await browser.close();browser=null;
  for(const [engine,type]of [['chromium',chromium],['webkit',webkit]]){
   browser=await type.launch({headless:true});page=await pageFor();await login(page,owner);
   const upload=async(f,n)=>{await go(page,web+'/vault/import');await page.locator('input[type=file]').setInputFiles({name:'synthetic.csv',mimeType:'text/csv',buffer:Buffer.from(`Product Name,Set,Card Number,Quantity,Condition,Cost,Notes\nSynthetic import card,${f.setName},00065,${n},LP,4.25,Synthetic recovery note`)});await expect(page.getByRole('heading',{name:'Import Preview'})).toBeVisible();};
   await check(engine+' actual CSV saves only deficit and explains already-owned reupload',async()=>{const f=await seed();await db.query('select public.admin_vault_instance_create_v1(p_user_id=>$1,p_card_print_id=>$2)',[owner.id,f.card]);await upload(f,3);await expect(page.locator('tbody td').nth(3)).toHaveText('2');await page.getByRole('button',{name:'Import to Vault',exact:true}).click();await expect(page.getByRole('heading',{name:'Import complete'})).toBeVisible();await expect(page.getByText('Imported 2 cards across 1 vault entry.')).toBeVisible();assert.equal(await count(owner,f),3);await upload(f,3);await expect(page.getByText(/1 row already meets its requested quantity/)).toBeVisible();await expect(page.getByRole('button',{name:'Import to Vault',exact:true})).toBeDisabled();const image=run+'/'+engine+'-already-owned.png';await page.screenshot({path:image,fullPage:true});screenshots.push(image);});
   await check(engine+' lost committed response reloads and recovers the original attempt',async()=>{const f=await seed();await upload(f,3);let dropped=false,finishDrop,failDrop;const dropCompleted=new Promise((resolve,reject)=>{finishDrop=resolve;failDrop=reject;});const route=async r=>{if(!dropped&&r.request().method()==='POST'&&r.request().headers()['next-action']){dropped=true;try{await r.fetch();await r.abort('failed');finishDrop();}catch(error){failDrop(error);}}else await r.continue();};await page.route('**/vault/import',route);await page.getByRole('button',{name:'Import to Vault',exact:true}).click();await expect.poll(()=>dropped).toBe(true);await dropCompleted;await expect.poll(()=>count(owner,f)).toBe(3);const key='vault-import:v1:'+owner.id;const attempt=await page.evaluate(key=>JSON.parse(sessionStorage.getItem(key)),key);assert.ok(attempt.requestId);const receipt=(await receipts(owner,attempt.requestId))[0];assert.equal(receipt.status,'succeeded');await page.unroute('**/vault/import',route);await go(page,web+'/vault/import');await expect(page.getByRole('button',{name:'Retry import',exact:true})).toBeVisible();await expect(page.getByText('A previous save may have completed. Retry to recover its saved result before uploading another file.')).toBeVisible();await expect(page.locator('input[type=file]')).toBeDisabled();const image=run+'/'+engine+'-recover.png';await page.screenshot({path:image,fullPage:true});screenshots.push(image);await page.getByRole('button',{name:'Retry import',exact:true}).click();await expect(page.getByRole('heading',{name:'Import complete'})).toBeVisible();await expect(page.getByText('Imported 3 cards across 1 vault entry.')).toBeVisible();assert.equal(await count(owner,f),3);assert.deepEqual((await receipts(owner,attempt.requestId))[0],receipt);assert.equal(await page.evaluate(key=>sessionStorage.getItem(key),key),null);});
   await check(engine+' persisted attempt does not appear for a different signed-in owner',async()=>{const f=await seed(),key='vault-import:v1:'+owner.id;await page.evaluate(({key,draft})=>sessionStorage.setItem(key,JSON.stringify(draft)),{key,draft:{version:1,ownerId:owner.id,requestId:randomUUID(),rows:[rows(f,2)],fileName:'private-owner.csv'}});await login(page,other);await go(page,web+'/vault/import');await expect(page.getByRole('button',{name:'Retry import',exact:true})).toHaveCount(0);assert.equal(await count(other,f),0);await page.evaluate(key=>sessionStorage.removeItem(key),key);});
   await page.context().close();await browser.close();browser=null;
  }
  const after=await snap();for(const [table,oldRows]of Object.entries(before)){const key=r=>table==='vault_import_receipts_v1'?r.user_id+':'+r.request_id:r.id;const current=new Map(after[table].map(r=>[key(r),r]));for(const row of oldRows)assert.deepEqual(current.get(key(row)),row,'prior row changed in '+table);}
  save('result.json',{status:'passed',at:new Date().toISOString(),checks,screenshots,sourceHashes:Object.fromEntries(['apps/web/src/lib/import/matchCardPrints.ts','apps/web/src/lib/import/importVaultItems.ts','apps/web/src/lib/import/importAttempt.ts','apps/web/src/app/vault/import/ImportClient.tsx','apps/web/src/app/vault/import/page.tsx','apps/web/src/types/import.ts','tests/integration/web_import_recovery_v1.test.mjs'].map(f=>[f,hash(fs.readFileSync(root+f))])),preservedPriorRows:Object.fromEntries(Object.entries(before).map(([k,v])=>[k,v.length])),productionWrites:0,migrationsApplied:0,resets:0});
  fs.writeFileSync(out+'/acceptance-latest.json',JSON.stringify({run,status:'passed',checks:checks.length},null,2));
 }finally{
  await browser?.close();if(child?.pid){try{execFileSync('taskkill',['/PID',String(child.pid),'/T','/F'],{stdio:'ignore'});}catch{}}
  await db.end();if(!relayWasRunning)docker('stop',project+'-relay');
  save('cleanup.json',{at:new Date().toISOString(),webStopped:true,relayRestoredToInitialState:!relayWasRunning?'stopped':'left running',sharedDbReset:false});
 }
});
