// Unmodified build/shipcheck against a verified local read-only preview target.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {execFileSync,spawn} from 'node:child_process';import {createHash} from 'node:crypto';
import {inspectJungleRetainedRuntimeV1} from '../schema/inspect_jungle_retained_runtime_v1.mjs';
const mode=process.argv[2];assert.equal(process.argv.length,3);assert.ok(['build','shipcheck'].includes(mode));
const root='C:/gv_jungle_edition_20261001',base='C:/grookai_vault_operator_artifacts/jungle_edition_pricing_20261001/release-integration-414-v1';
assert.equal(fs.realpathSync('.').replaceAll('\\','/').toLowerCase(),root.toLowerCase());
const runtime=inspectJungleRetainedRuntimeV1(),project=runtime.project;
const out=base+'/'+mode+'-'+Date.now();fs.mkdirSync(out);fs.mkdirSync(out+'/temp');
const sha=b=>createHash('sha256').update(b).digest('hex'),save=(n,v)=>fs.writeFileSync(out+'/'+n,JSON.stringify(v,null,2),{flag:'wx'});
save('runtime.json',runtime);
const wsl=(...a)=>execFileSync('wsl',['-d','docker-desktop','--',...a],{encoding:'utf8',windowsHide:true,timeout:15000});
const configs=wsl('sh','-c','grep -l '+project+' /mnt/docker-desktop-disk/data/docker/containers/*/config.v2.json').trim().split(/\r?\n/).map(p=>JSON.parse(wsl('cat',p)));
const kong=configs.find(c=>c.Name==='/supabase_kong_'+project);assert.ok(kong?.State.Running);
const parent=wsl('cat','/run/linuxkit-parent.pid').trim();assert.match(parent,/^[1-9][0-9]*$/);
assert.equal(wsl('nsenter','-t',parent,'-m','-p','--','cat','/proc/'+kong.State.Pid+'/cgroup').trim(),'0::/docker/'+kong.ID);
const configPath=kong.Config.Env.find(v=>v.startsWith('KONG_DECLARATIVE_CONFIG=')).split('=').slice(1).join('=');assert.match(configPath,/^\/[a-zA-Z0-9_./-]+$/);
const config=wsl('nsenter','-t',parent,'-m','-p','--','cat','/proc/'+kong.State.Pid+'/root'+configPath);
const keys=[...config.matchAll(/(?:\bkey["']?:\s*["']?|\b)(eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+|sb_publishable_[A-Za-z0-9_-]+)/g)].map(m=>m[1]);
const anon=keys.find(k=>{try{return JSON.parse(Buffer.from(k.split('.')[1],'base64url')).role==='anon';}catch{return false;}});assert.ok(anon);
const response=await fetch('http://127.0.0.1:65041/rest/v1/',{headers:{apikey:anon,Authorization:'Bearer '+anon},signal:AbortSignal.timeout(10000)});assert.equal(response.status,200);
const env={};for(const key of ['PATH','Path','SystemRoot','SYSTEMROOT','USERPROFILE','APPDATA','LOCALAPPDATA','COMSPEC','PROGRAMFILES','ProgramFiles','JAVA_HOME','ANDROID_HOME','ANDROID_SDK_ROOT','PUB_CACHE','FLUTTER_ROOT'])if(process.env[key])env[key]=process.env[key];
for(const file of ['.env','.env.local','apps/web/.env','apps/web/.env.local'])if(fs.existsSync(file))for(const m of fs.readFileSync(file,'utf8').matchAll(/^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/gm))env[m[1]]='';
fs.writeFileSync(out+'/empty.env','',{flag:'wx'});
Object.assign(env,{TEMP:out+'/temp',TMP:out+'/temp',DOTENV_CONFIG_PATH:out+'/empty.env',SUPABASE_DB_URL:'postgresql://postgres:postgres@127.0.0.1:65040/postgres?options=-c%20default_transaction_read_only%3Don',SUPABASE_URL:'http://127.0.0.1:65041',SUPABASE_PUBLISHABLE_KEY:anon,SUPABASE_ANON_KEY:anon,NEXT_PUBLIC_SUPABASE_URL:'http://127.0.0.1:65041',NEXT_PUBLIC_SUPABASE_ANON_KEY:anon,NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:anon,SUPABASE_SECRET_KEY:'',NEXT_PUBLIC_COLLECTOR_PREVIEW_READ_ONLY:'true',NEXT_PUBLIC_COLLECTOR_STAGING:'false',NEXT_PUBLIC_COLLECTOR_FIXTURE_LAB:'false',NEXT_PUBLIC_COLLECTOR_HOSTED_STAGING:'false',GROOKAI_COLLECTOR_RELEASE_V1:'false',GROOKAI_DISABLE_TELEMETRY:'1',NEXT_TELEMETRY_DISABLED:'1',NODE_OPTIONS:'--use-system-ca',NODE_USE_SYSTEM_CA:'1',CI:'true',SITE_URL:'http://127.0.0.1:65060',NEXT_PUBLIC_SITE_URL:'http://127.0.0.1:65060'});
const pathKey=Object.hasOwn(env,'Path')?'Path':'PATH';env[pathKey]='C:\\src\\flutter\\bin;'+env[pathKey];
const command=mode==='build'?'web:build:strict':'shipcheck';
save('intent.json',{at:new Date().toISOString(),command:'npm run '+command,localReadOnlyPreview:true,productionWrites:0,sourceSha256:sha(fs.readFileSync(new URL(import.meta.url))),consumed:true});
const log=fs.openSync(out+'/checks.log','wx');const child=spawn('npm.cmd',['run',command],{cwd:root,env,shell:true,windowsHide:true,stdio:['ignore',log,log]});
const code=await new Promise((resolve,reject)=>{child.on('error',reject);child.on('exit',resolve);});fs.closeSync(log);
const receipt={at:new Date().toISOString(),status:code===0?'passed':'failed',exitCode:code,command:'npm run '+command,localReadOnlyPreview:true,productionWrites:0,logSha256:sha(fs.readFileSync(out+'/checks.log')),out};save('receipt.json',receipt);console.log(JSON.stringify(receipt));process.exitCode=code??1;
