// Normal release checks/hooks against the attested, read-only populated423 lab.
// No production credentials, reset, reseed, hook override or arbitrary command.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync,spawn} from 'node:child_process';import pg from 'pg';
import {inspectJungleFullSourceV30} from '../schema/inspect_jungle_full_source_v30.mjs';
const mode=process.argv[2];assert.equal(process.argv.length,3);assert.ok(['build','shipcheck','commit'].includes(mode));
const root='C:/gv_jungle_edition_20261001',base='C:/grookai_vault_operator_artifacts/jungle_edition_pricing_20261001',fixture=base+'/full-422-v30';assert.equal(fs.realpathSync('.').replaceAll('\\','/').toLowerCase(),root.toLowerCase());
const read=p=>JSON.parse(fs.readFileSync(p)),sha=b=>createHash('sha256').update(b).digest('hex'),git=(...a)=>execFileSync('git',a,{encoding:'utf8',windowsHide:true}).trim(),docker=(...a)=>execFileSync('docker',a,{encoding:'utf8',windowsHide:true,timeout:20000,maxBuffer:4*1024*1024});
const proof=read(base+'/retained-receipt-upgrade-v31/receipt.json'),parity=read(base+'/receipt-replay-parity-v31/receipt.json');assert.equal(proof.status,'passed');assert.equal(proof.migrations,423);assert.equal(parity.status,'passed');assert.equal(parity.comparison.normalizedBytes,0);
for(const [n,h]of Object.entries(proof.sourceHashes)){assert.equal(sha(fs.readFileSync('supabase/migrations/'+n)),h,n);assert.equal(sha(fs.readFileSync(fixture+'/supabase/migrations/'+n)),h,n);}
const runtime=inspectJungleFullSourceV30(),project=runtime.project;
const c=new pg.Client({host:'127.0.0.1',port:53400,user:'postgres',password:'postgres',database:'postgres',options:'-c default_transaction_read_only=on',connectionTimeoutMillis:10000});await c.connect();let state;
try{state=(await c.query("select host(inet_server_addr()) address,current_setting('transaction_read_only') readonly,current_setting('max_worker_processes') workers,(select count(*)::int from supabase_migrations.schema_migrations) migrations,(select count(*)::int from vault_item_instances) copies,(select count(*)::int from market_price_publication_snapshots) snapshots,(select count(*)::int from market_price_current_publication) pointers")).rows[0];assert.deepEqual(state,{address:runtime.address,readonly:'on',workers:'0',migrations:423,copies:5,snapshots:164804,pointers:0});}finally{await c.end();}
const kong=JSON.parse(docker('inspect','supabase_kong_'+project))[0];assert.equal(kong.State.Running,true);assert.deepEqual(Object.keys(kong.NetworkSettings.Networks),[project]);const configPath=kong.Config.Env.find(v=>v.startsWith('KONG_DECLARATIVE_CONFIG=')).split('=').slice(1).join('=');assert.match(configPath,/^\/[a-zA-Z0-9_./-]+$/);const config=docker('exec',kong.Name,'cat',configPath);
const keys=[...config.matchAll(/(?:\bkey["']?:\s*["']?|\b)(eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+|sb_publishable_[A-Za-z0-9_-]+)/g)].map(m=>m[1]);const anon=keys.find(k=>{try{return JSON.parse(Buffer.from(k.split('.')[1],'base64url')).role==='anon';}catch{return false;}});assert.ok(anon);
assert.equal((await fetch('http://127.0.0.1:53401/rest/v1/',{headers:{apikey:anon,Authorization:'Bearer '+anon},signal:AbortSignal.timeout(10000)})).status,200);
if(mode==='commit'){assert.equal(git('diff','--name-only'),'','Stage reviewed changes first');assert.equal(git('ls-files','--others','--exclude-standard'),'');assert.match(fs.readFileSync(path.resolve(root,git('rev-parse','--git-path','hooks/pre-commit')),'utf8'),/GROOKAI_MANAGED_HOOK_V1[\s\S]*npm run shipcheck/);}
const out=base+'/release-checks-v32/'+mode+'-'+Date.now();fs.mkdirSync(out);fs.mkdirSync(out+'/temp');const save=(n,v)=>fs.writeFileSync(out+'/'+n,JSON.stringify(v,null,2),{flag:'wx'});save('runtime.json',{runtime,state});
const env={};for(const k of ['PATH','Path','SystemRoot','SYSTEMROOT','USERPROFILE','APPDATA','LOCALAPPDATA','COMSPEC','PROGRAMFILES','ProgramFiles','JAVA_HOME','ANDROID_HOME','ANDROID_SDK_ROOT','PUB_CACHE','FLUTTER_ROOT'])if(process.env[k])env[k]=process.env[k];
for(const dir of [root,root+'/apps/web',root+'/backend'])for(const n of ['.env','.env.local','.env.production','.env.production.local']){const f=dir+'/'+n;if(fs.existsSync(f))for(const m of fs.readFileSync(f,'utf8').matchAll(/^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/gm))env[m[1]]='';}
fs.writeFileSync(out+'/empty.env','',{flag:'wx'});Object.assign(env,{TEMP:out+'/temp',TMP:out+'/temp',DOTENV_CONFIG_PATH:out+'/empty.env',SUPABASE_DB_URL:'postgresql://postgres:postgres@127.0.0.1:53400/postgres?options=-c%20default_transaction_read_only%3Don',SUPABASE_URL:'http://127.0.0.1:53401',SUPABASE_PUBLISHABLE_KEY:anon,SUPABASE_ANON_KEY:anon,NEXT_PUBLIC_SUPABASE_URL:'http://127.0.0.1:53401',NEXT_PUBLIC_SUPABASE_ANON_KEY:anon,NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:anon,SUPABASE_SECRET_KEY:'',SUPABASE_SERVICE_ROLE_KEY:'',NEXT_PUBLIC_COLLECTOR_PREVIEW_READ_ONLY:'true',NEXT_PUBLIC_COLLECTOR_STAGING:'false',NEXT_PUBLIC_COLLECTOR_FIXTURE_LAB:'false',NEXT_PUBLIC_COLLECTOR_HOSTED_STAGING:'false',GROOKAI_COLLECTOR_RELEASE_V1:'false',GROOKAI_DISABLE_TELEMETRY:'1',NEXT_TELEMETRY_DISABLED:'1',NODE_OPTIONS:'--use-system-ca',NODE_USE_SYSTEM_CA:'1',CI:'true',SITE_URL:'http://127.0.0.1:53460',NEXT_PUBLIC_SITE_URL:'http://127.0.0.1:53460'});
const pathKey=Object.hasOwn(env,'Path')?'Path':'PATH';env[pathKey]='C:\\src\\flutter\\bin;'+env[pathKey];
const head=git('rev-parse','HEAD'),tree=git('write-tree'),command=mode==='commit'?'git commit with normal pre-commit shipcheck':'npm run '+(mode==='build'?'web:build:strict':'shipcheck');save('intent.json',{at:new Date().toISOString(),command,head,tree,scriptSha256:sha(fs.readFileSync(new URL(import.meta.url))),localReadOnlyPreview:true,productionWrites:0,consumed:true});
const fd=fs.openSync(out+'/checks.private.log','wx'),child=mode==='commit'?spawn('git',['commit','-m','fix: qualify Jungle catalog release against schema423'],{cwd:root,env,windowsHide:true,stdio:['ignore',fd,fd]}):spawn('npm.cmd',['run',mode==='build'?'web:build:strict':'shipcheck'],{cwd:root,env,shell:true,windowsHide:true,stdio:['ignore',fd,fd]});console.log(JSON.stringify({state:'running',command,out}));
const code=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',resolve);});fs.closeSync(fd);const receipt={at:new Date().toISOString(),status:code===0?'passed':'failed',exitCode:code,command,initialHead:head,stagedTree:tree,finalHead:git('rev-parse','HEAD'),normalHooks:mode==='commit',localReadOnlyPreview:true,productionWrites:0,logSha256:sha(fs.readFileSync(out+'/checks.private.log')),remainingStatus:git('status','--porcelain'),out};save('receipt.json',receipt);if(mode==='commit'&&code===0)fs.writeFileSync(base+'/release-checks-v32/normal-hook-latest.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify({status:receipt.status,exitCode:code,head:receipt.finalHead,out}));process.exitCode=code??1;
