// Synthetic browser fixture only: no database, provider or live inventory writes.
import './vendor_storefront_network_guard.cjs';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {createServer} from 'node:http';
const root=process.cwd(),dir=path.join(root,'.local/integration/store-sold-v1'),web=path.join(root,'apps/web');
fs.mkdirSync(dir,{recursive:true});
const require=createRequire(path.join(web,'package.json'));
const {webpack}=require('next/dist/compiled/webpack/webpack');
const loader=path.join(dir,'loader.cjs');
fs.writeFileSync(loader,`const ts=require(${JSON.stringify(require.resolve('typescript'))});module.exports=function(source){if(this.resourcePath.endsWith('.css')){const css=source.replace(/:global\\(([^)]+)\\)/g,'$1');return 'const style=document.createElement("style");style.textContent='+JSON.stringify(css)+';document.head.appendChild(style);export default '+JSON.stringify(Object.fromEntries([...source.matchAll(/\\.([a-zA-Z_][a-zA-Z0-9_-]*)/g)].map(m=>[m[1],m[1]])))+';';}return ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true},fileName:this.resourcePath}).outputText;};`);
fs.writeFileSync(path.join(dir,'batch.tsx'),'export default function Batch(){return null;}');
fs.writeFileSync(path.join(dir,'action.ts'),`export async function recordVaultDispositionAction(input){const r=await fetch('/sale',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});if(!r.ok)throw Error('Synthetic response loss');return r.json();}`);
const entry=path.join(dir,'entry.tsx');
fs.writeFileSync(entry,`import React,{useState,useEffect} from 'react';import{createRoot}from'react-dom/client';import Workspace from '@/components/stores/StoreInventoryWorkspace';import s from '@/components/stores/StoreManager.module.css';
function App(){const[owner,setOwner]=useState(null),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[canEdit,setCanEdit]=useState(true);const refresh=async()=>{const r=await fetch('/fixture');if(!r.ok)throw Error('Synthetic refresh failed');setOwner(await r.json());};useEffect(()=>{void refresh()},[]);const task=async(fn,message='Saved.')=>{setBusy(true);setError('');setNotice('');try{await fn();setNotice(message)}catch(e){setError(e.message)}finally{setBusy(false)}};return <main className={s.workspace}><p>LOCAL SYNTHETIC SALE PROOF — NO DATABASE</p><p>Unsaved draft: {String(dirty)}</p><button onClick={()=>document.documentElement.classList.toggle('gv-dark')}>Toggle theme</button><button onClick={()=>fetch('/mode',{method:'POST',body:'lost'})}>Simulate lost response</button><button onClick={()=>fetch('/mode',{method:'POST',body:'refresh'})}>Simulate refresh failure</button><button onClick={()=>setCanEdit(v=>!v)}>Toggle retained access</button>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{owner&&<Workspace initialQuery="" owner={owner} busy={busy} canEdit={canEdit} task={task} load={refresh} refresh={refresh} setDirty={setDirty} onIntakePending={()=>{}}/>}<a href="/proof">Read synthetic write receipt</a></main>};createRoot(document.getElementById('root')).render(<App/>);`);
await new Promise((resolve,reject)=>webpack({mode:'development',devtool:false,entry,context:web,output:{path:path.join(dir,'dist'),filename:'bundle.js'},resolve:{extensions:['.tsx','.ts','.js'],alias:{'@/lib/vault/recordVaultDispositionAction':path.join(dir,'action.ts'),'@':path.join(web,'src'),'./StoreBatchIntake':path.join(dir,'batch.tsx')},modules:[path.join(web,'node_modules'),path.join(root,'node_modules')]},module:{rules:[{test:/\.(tsx?|css)$/,exclude:/node_modules/,use:loader}]},optimization:{minimize:false}},(e,stats)=>e||stats.hasErrors()?reject(e||Error(stats.toString({all:false,errors:true}))):resolve()));
const bundle=fs.readFileSync(path.join(dir,'dist/bundle.js'));
const section='22222222-2222-4222-8222-222222222222';
const copies=[['Showcase card','showcase',400],['Unpriced card','hold',null],['Quarantined card','sell',20]].map(([name,intent,amount],i)=>({id:`11111111-1111-4111-8111-11111111111${i}`,gv_vi_id:`GVVI-TEST-${i+1}`,name,display_name:name,entry_type:'catalog_copy',condition_label:'NM',finish_label:'Holo',printing_gv_id:'GV-PK-TEST-001-HOLO',display_image_url:null,intent,pricing_mode:'asking',asking_price_amount:amount,asking_price_currency:'USD',selected:false,sections:[section],ineligible_reason:i===2?'Printing is quarantined':intent!=='sell'?'Copy is not for sale':null}));
const writes=[],sales=[];let mode='',refreshFailures=0;
createServer(async(req,res)=>{res.setHeader('cache-control','no-store');const json=(d,status=200)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(d));};
 const url=new URL(req.url,'http://127.0.0.1');
 if(req.url==='/mode'&&req.method==='POST'){let body='';for await(const b of req)body+=b;mode=body;json({ok:true});return;}
 if(req.url==='/sale'&&req.method==='POST'){let body='';for await(const b of req)body+=b;const input=JSON.parse(body);writes.push(input);const copy=copies.find(c=>c.id===input.instanceId);if(!copy||input.type!=='sale'||!(Number(input.salePrice)>0)){json({ok:false,message:'Invalid synthetic sale'});return;}let receipt=sales.find(s=>s.instanceId===copy.id);if(!receipt){receipt={id:'fixture-sale-'+sales.length,instanceId:copy.id,gvviId:copy.gv_vi_id,type:'sale',salePrice:Number(input.salePrice),saleCurrency:'USD',counterparty:input.counterparty||null,tradeReceived:null,cashDirection:null,cashAmount:null,cashCurrency:null,recordedAt:new Date().toISOString()};sales.push(receipt);}if(mode==='lost'){mode='';json({error:'Synthetic response loss'},503);return;}if(mode==='refresh'){mode='';refreshFailures=1;}json({ok:true,receipt});return;}
 if(req.url==='/bundle.js'){res.setHeader('content-type','text/javascript; charset=utf-8');res.end(bundle);return;}
 if(req.url==='/fixture'){if(refreshFailures){refreshFailures--;json({error:'Synthetic refresh failure'},503);return;}json({store:{id:'synthetic-store',slug:'synthetic',app_published:false,web_published:false},sections:[{id:section,name:'Featured',selected:true}],inventory:{items:copies.filter(c=>!sales.some(s=>s.instanceId===c.id)),total:copies.length-sales.length,offset:0,limit:40}});return;}
 if(req.url==='/proof'){res.setHeader('content-type','text/html; charset=utf-8');res.end('<pre>'+JSON.stringify({writes,sales},null,2).replaceAll('&','&amp;').replaceAll('<','&lt;')+'</pre>');return;}
 if(url.pathname==='/api/stores/owner/inventory'&&req.method==='GET'){const c=copies.find(c=>c.id===url.searchParams.get('id'));json(c??{},c?200:404);return;}
 if(req.method==='POST'&&['/api/stores/owner/inventory','/api/stores/owner'].includes(url.pathname)){const chunks=[];for await(const c of req)chunks.push(c);const data=JSON.parse(Buffer.concat(chunks));writes.push(data);const c=copies.find(c=>c.id===(data.id??data.instance_id));if(!c){json({error:'Unknown copy'},404);return;}if(c.name==='Quarantined card'){json({error:'Printing is quarantined. This copy cannot be listed.'},409);return;}if(data.action==='save'){if(data.selected&&(!(data.amount>0)||data.intent!=='sell')){json({error:'Invalid listing'},400);return;}Object.assign(c,{condition_label:data.condition,intent:data.intent,pricing_mode:data.mode,asking_price_amount:data.amount,asking_price_currency:data.currency,selected:data.selected,sections:data.sections,ineligible_reason:null});}else if(data.action==='item'&&data.selected===false)c.selected=false;else{json({error:'Unexpected action'},400);return;}json({ok:true});return;}
 if(req.url==='/'){res.setHeader('content-type','text/html; charset=utf-8');res.end('<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>body{margin:24px;font-family:system-ui;background:#f4f6f4}main{max-width:1200px;margin:auto}</style></head><body><div id="root"></div><script src="/bundle.js"></script></body></html>');return;}
 res.writeHead(404).end();
}).listen(26446,'127.0.0.1',()=>console.log('Synthetic sale proof at http://127.0.0.1:26446'));
