import test from 'node:test';
import assert from 'node:assert/strict';
import { newIntakeBatch, naturalFileOrder, pairAssets, defaultBatchSettings, itemProblem, applyBatchDefaults, selectBatchMatch, commitSelection, settingsProblem } from '../../apps/web/src/lib/stores/batchIntake.ts';
const image = n => ({id:`asset-${n}`,name:`Scan ${n}.jpg`,hash:`hash-${n}`,original:new Blob(['image']),preview:new Blob(['preview']),error:null});
const card = {id:'card',gv_id:'GV-PK-EXAMPLE',name:'Example',number:'1',set_code:'TEST',image:null,printings:[{id:'printing',printing_gv_id:'GV-PK-EXAMPLE-HOLO',finish_label:'Holo'}]};
function fixture(){const b=newIntakeBatch('store-a');b.assets=[image(1),image(2)];b.items=pairAssets(b.assets,'front',b.defaults);b.items=b.items.map(i=>({...i,card,printing:'printing',confirmed:true}));return b;}
test('natural scan order preserves 2 before 10 and does not mutate the input',()=>{const files=[{name:'Scan 10.jpg'},{name:'Scan 2.jpg'},{name:'Scan 1.jpg'}];assert.deepEqual(naturalFileOrder(files).map(x=>x.name),['Scan 1.jpg','Scan 2.jpg','Scan 10.jpg']);assert.equal(files[0].name,'Scan 10.jpg');});
test('front/back pairs never create an extra physical copy for a back; odd tail is explicit',()=>{const b=newIntakeBatch('store');b.layout='pairs';b.assets=[image(1),image(2),image(3)];b.items=pairAssets(b.assets,'pairs',b.defaults);assert.equal(b.items.length,2);assert.equal(b.items[0].back,'asset-2');assert.equal(b.items[1].back,null);assert.match(itemProblem(b,b.items[1]),/Missing back/);});
test('matching artwork and even identical input hashes do not merge physical copies',()=>{const b=fixture();b.assets[1].hash=b.assets[0].hash;assert.equal(commitSelection(b,false).length,2);assert.notEqual(b.items[0].id,b.items[1].id);});
test('each copy receives independent settings and section arrays',()=>{const settings=defaultBatchSettings();settings.sections=['section'];const items=pairAssets([image(1),image(2)],'front',settings);items[0].settings.sections.push('new');assert.deepEqual(items[1].settings.sections,['section']);assert.deepEqual(settings.sections,['section']);});
test('bad media, wrong printing and missing confirmation block committing',()=>{for(const mutate of [b=>b.assets[0].preview=null,b=>b.items[0].printing='foreign',b=>b.items[0].confirmed=false,b=>b.items[0].card=null]){const b=fixture();mutate(b);assert.throws(()=>commitSelection(b,false));}});
test('completed receipts cannot create another copy',()=>{const b=fixture();b.items[0].receipt={id:'instance',gvvi:'GVVI-existing'};assert.equal(commitSelection(b,false).length,1);b.items[1].receipt={id:'instance2',gvvi:'GVVI-existing2'};assert.throws(()=>commitSelection(b,false),/unfinished/);});
test('bulk defaults preserve overrides and completed copies, reset confirmation on changed copies',()=>{const b=fixture();b.defaults.condition='LP';b.items[0].overridden=true;const next=applyBatchDefaults(b,false);assert.equal(next.items[0].settings.condition,'NM');assert.equal(next.items[1].settings.condition,'LP');assert.equal(next.items[1].confirmed,false);assert.equal(applyBatchDefaults(b,true).items[0].settings.condition,'LP');b.items[1].receipt={id:'done',gvvi:'done'};assert.equal(applyBatchDefaults(b,true).items[1].settings.condition,'NM');});
test('a new match invalidates printing and review without inventing another finish',()=>{const b=fixture();const next=selectBatchMatch(b.items[0],{...card,id:'other',printings:[]});assert.equal(next.printing,'');assert.equal(next.confirmed,false);assert.match(itemProblem(b,next),/eligible finish/);});
test('for-sale copies need valid manual asking prices; private inventory does not',()=>{const b=fixture();assert.equal(commitSelection(b,false).length,2);assert.throws(()=>commitSelection(b,true),/for-sale/);b.items=b.items.map(i=>({...i,settings:{...i.settings,intent:'sell',amount:'12.50'}}));assert.equal(commitSelection(b,true).length,2);for(const amount of ['','0','-1','2.001','NaN','Infinity','100000000'])assert.ok(settingsProblem({...b.items[0].settings,amount}));});
test('batch limits and per-copy validation fail closed',()=>{assert.throws(()=>pairAssets(Array.from({length:51},(_,i)=>image(i)),'front',defaultBatchSettings()));assert.ok(settingsProblem({...defaultBatchSettings(),currency:'$'}));assert.ok(settingsProblem({...defaultBatchSettings(),condition:'Perfect'}));assert.ok(settingsProblem({...defaultBatchSettings(),location:'x'.repeat(121)}));});
test('an explicitly front-only copy can coexist with front/back pairs without changing other reviews',()=>{const b=fixture();b.layout='pairs';b.items[0].requiresBack=true;assert.match(itemProblem(b,b.items[0]),/Missing back/);b.items[0].requiresBack=false;assert.equal(itemProblem(b,b.items[0]),null);assert.equal(b.items[1].confirmed,true);});
