import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{createHash}from'node:crypto';
const read=p=>JSON.parse(fs.readFileSync(p)),hash=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const local='.local/integration/vendor-scan-runtime-v26',base='.local/integration/vendor-scan-hosted-v26-baseline',pipe='.local/integration/vendor-scan-hosted-v26-pipeline',dest='docs/audits/vendor_scan_runtime_v26/PROOF_20260924.json';assert.ok(!fs.existsSync(dest));
const priorPath='docs/audits/vendor_scan_runtime_v25/CANCELLATION_PROOF_20260924.json',prior=read(priorPath),runtimePath=local+'/runtime-final.private.json',runtime=read(runtimePath);
assert.equal(runtime.summary.same,17);assert.equal(runtime.summary.errors,0);for(const[n,h]of Object.entries(runtime.sourceHashes))assert.equal(hash('apps/web/src/lib/stores/'+n),h);
const changed=new Set(['scanVisualProcessV24.mjs','scanVisualProcessV24.d.mts','scanVisualServerV24.ts'].map(n=>'apps/web/src/lib/stores/'+n));for(const[p,h]of Object.entries(prior.sourceHashes))if(!changed.has(p))assert.equal(hash(p),h);
for(const[p,h]of Object.entries(read('docs/audits/vendor_scan_visual_v23/PROOF_20260924.json').sourceHashes))assert.equal(hash(p),h);
const testsPath=local+'/tests-final.txt',tests=fs.readFileSync(testsPath,'utf8');assert.match(tests,/# tests 34\b/);assert.match(tests,/# fail 0\b/);assert.equal(fs.statSync(local+'/typecheck-final.txt').size,0);assert.equal(fs.statSync(local+'/lint-final.txt').size,0);
const bpath=base+'/hosted-proof-after-fixture-renewal.private.json',ppath=pipe+'/hosted-proof.private.json',b=read(bpath),p=read(ppath);for(const r of[b,p]){assert.equal(r.status,'passed');assert.equal(r.rows.length,7);assert.ok(r.rows.every(x=>x.same)&&r.checks.every(x=>x.passed)&&r.retainedDataUnchanged);}
assert.ok(p.cancellation.passed&&p.cancellation.firstRetryHttp===200);assert.deepEqual(p.concurrency.map(x=>x.http).sort(),[200,429]);
function resource(dir,n){const files=fs.readdirSync(dir).filter(x=>/^resources-.*\.json$/.test(x)).sort().reverse();const file=files.find(f=>read(dir+'/'+f).summary.resources===n);assert.ok(file);return{file:dir+'/'+file,data:read(dir+'/'+file)};}
const br=resource(base,7),pr=resource(pipe,15);assert.ok(pr.data.summary.aborted>=1);assert.ok(pr.data.rows.some(r=>{const stages=Object.fromEntries(r.stages.map(s=>[s.stage,s.ms]));return stages.delivery_start<stages.prepared&&stages.prepared<stages.delivery_complete;}));
const pixelPath=pipe+'/pixel-boundary-card-aspect.private.json',pixel=read(pixelPath);assert.equal(pixel.status,'passed');assert.ok(pixel.retainedDataUnchanged);assert.deepEqual(pixel.rows.map(x=>x.http),[200,503]);
const browserPath=pipe+'/browser-1790297978937.json',browser=read(browserPath);assert.equal(browser.status,'passed');assert.equal(browser.inventoryWrites,0);assert.equal(browser.requests.length,2);assert.ok(browser.requests.every(r=>r.status===200));assert.ok(browser.capabilitiesReadyAfterReload&&browser.comparisonImageLoadedAfterReload);assert.ok(read(pipe+'/post-browser-readback.json').retainedDataUnchanged);
for(const dir of[base,pipe]){assert.equal(read(dir+'/ready.json').state,'READY');const plan=read(dir+'/package.json');for(const f of plan.files){assert.equal(hash(path.join(plan.dest,f.path)),f.sha256);assert.equal(hash(f.path),f.sha256);}}
const files=[...Object.keys(prior.sourceHashes),'apps/web/src/lib/stores/scanResourceSamplerV26.mjs','apps/web/src/lib/stores/scanVisualWorkerV26.mjs'],sourceHashes=Object.fromEntries(files.map(f=>[f,hash(f)]));
const harnesses=['scripts/tests/vendor_scan_resources_v26.test.mjs','scripts/tests/vendor_scan_visual_process_v24.test.mjs','scripts/tests/vendor_scan_visual_server_v24.test.mjs','scripts/tests/vendor_scan_visual_runtime_v26.mjs',...['hosting','hosted-proof','resources','browser-proof','pixel-boundary','renew-fixtures'].map(n=>'scripts/preview/vendor-pilot/visual-v26-'+n+'.mjs')];
const times=r=>{const t=r.rows.map(x=>x.ms).sort((a,b)=>a-b);return{minMs:t[0],medianMs:t[3],maxMs:t.at(-1)};};
const proof={at:new Date().toISOString(),baseline:prior.baseline,precedingProofSha256:hash(priorPath),sourceHashes,harnessHashes:Object.fromEntries(harnesses.map(f=>[f,hash(f)])),algorithmUnchanged:true,tests:{passed:34,failed:0,receiptSha256:hash(testsPath),typecheckPassed:true,lintPassed:true},local:{...runtime.summary,receiptSha256:hash(runtimePath)},hosting:[base,pipe].map(dir=>({...read(dir+'/ready.json'),packageSha256:hash(dir+'/package.json')})),comparison:{baseline:{...times(b),cases:7,same:7,receiptSha256:hash(bpath),resources:br.data.summary,resourceReceiptSha256:hash(br.file),rawLogsSha256:hash(base+'/'+br.data.source)},pipeline:{...times(p),cases:7,same:7,receiptSha256:hash(ppath),resources:pr.data.summary,resourceReceiptSha256:hash(pr.file),rawLogsSha256:hash(pipe+'/'+pr.data.source)},controlledPerformanceComparison:false,demonstratedLatencyImprovement:false,demonstratedMemoryReduction:false,cgroupEnvelopeKnown:false,notes:'Sequential cloud deployments have different pre-overlap CPU stage durations. Summed sampled RSS counts shared pages twice, excludes other processes and can miss peaks; parent HWM is process lifetime.'},accessChecks:p.checks,concurrency:p.concurrency,cancellation:{...p.cancellation,serverAbortObserved:true},pixelBoundary:{rows:pixel.rows,retainedDataUnchanged:true,receiptSha256:hash(pixelPath)},browser:{status:browser.status,steps:browser.steps,catalogImages:browser.catalogImages,inventoryWrites:0,receiptSha256:hash(browserPath),screenshotsInspected:true,screenshotHashes:Object.fromEntries(['desktop','mobile-layout'].map(n=>[n,hash(pipe+'/browser-1790297978937-'+n+'.png')])),physicalPhone:false},retainedDataUnchanged:true,postBrowserReadbackSha256:hash(pipe+'/post-browser-readback.json'),syntheticFixtureRenewal:{members:2,invites:2,expiredNegativeStillBlocked:true,entitlementRowsChanged:0,receiptSha256:hash(local+'/fixture-renewal-result.private.json')},preservedFailures:[{name:'First local runtime source-freeze failure',receiptSha256:hash(local+'/runtime.private.json')},{name:'Expired synthetic test access',receiptSha256:hash(base+'/hosted-proof.private.json')},{name:'Square fixture rejected by card-aspect guard',receiptSha256:hash(pipe+'/pixel-boundary.private.json')}],device:read(local+'/device-readback.json'),sharedAliasChanged:false,sharedDeployment:'dpl_F9id47NjSDscTwE2wx1F1gWpgGRR',productionWrites:0,schemaChanges:0,paymentsEnabled:false,releaseQualified:false,remaining:['Hash-bound metadata-only parent projection; full matching artifact unchanged','Function resource-envelope and cold/warm performance qualification','Physical phone workflow: Samsung currently disconnected','Governed pilot activation after qualification; production separate']};
fs.writeFileSync(dest,JSON.stringify(proof,null,2),{flag:'wx'});console.log(JSON.stringify({proof:dest,tests:34,localCases:17,hostedCases:14,resourceSummaries:22,browserPassed:true,releaseQualified:false}));
