import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {newIntakeBatch,pairAssets,commitSelection} from '../../apps/web/src/lib/stores/batchIntake.ts';
import {freezeBatchSubmission,reconcileBatchCancellation,retryCancelledItem,assertSubmittedItemsRetained} from '../../apps/web/src/lib/stores/batchSubmission.ts';
import {exportBatchBackup,importBatchBackup} from '../../apps/web/src/lib/stores/batchBackup.ts';
async function fixture(){const b=newIntakeBatch(randomUUID()),blob=new Blob([new Uint8Array([255,216,255,1,2,3])],{type:'image/jpeg'});b.assets=[{id:randomUUID(),name:'front.jpg',hash:'a'.repeat(64),original:blob,preview:blob,error:null}];b.items=pairAssets(b.assets,'front',b.defaults);const i=b.items[0];i.card={id:randomUUID(),gv_id:'GV-PK-TEST-001',name:'Test',number:'001',set_code:'TEST',image:null,printings:[{id:randomUUID(),printing_gv_id:'GV-PK-TEST-001-NORMAL',finish_label:'Normal'}]};i.printing=i.card.printings[0].id;i.confirmed=true;i.submission=await freezeBatchSubmission(b,i,false);return b;}
test('ambiguous or mismatched cancellation cannot unlock frozen submissions',async()=>{const b=await fixture(),i=b.items[0];assert.throws(()=>retryCancelledItem(i));for(const result of [{cancelled:false,completed:false},{cancelled:true,completed:true},{cancelled:true,completed:false,batch_id:randomUUID()},{cancelled:false,completed:true,id:'',gvvi:''}])assert.throws(()=>reconcileBatchCancellation(b,i.id,{batch_id:b.id,item_id:i.id,...result}));assert.throws(()=>assertSubmittedItemsRetained(b,{...b,items:[]}));});
test('server cancellation permits editing only through a fresh unconfirmed item identity',async()=>{const b=await fixture(),i=b.items[0],stopped=reconcileBatchCancellation(b,i.id,{batch_id:b.id,item_id:i.id,cancelled:true,completed:false});assertSubmittedItemsRetained(b,stopped);assert.equal(stopped.items[0].picked,false);assert.throws(()=>commitSelection(stopped,false));const next=retryCancelledItem(stopped.items[0]);assert.notEqual(next.id,i.id);assert.equal(next.submission,undefined);assert.equal(next.confirmed,false);assertSubmittedItemsRetained(stopped,{...stopped,items:[next]});assert.throws(()=>commitSelection({...stopped,items:[next]},false),/Review and confirm/);});
test('already completed cancellation recovers receipt without enabling retry',async()=>{const b=await fixture(),i=b.items[0],id=randomUUID(),done=reconcileBatchCancellation(b,i.id,{batch_id:b.id,item_id:i.id,cancelled:false,completed:true,id,gvvi:'GVVI-EXACT'});assertSubmittedItemsRetained(b,done);assert.equal(done.items[0].receipt.id,id);assert.throws(()=>retryCancelledItem(done.items[0]));});
test('backup cancellation claims never authorize a new attempt',async()=>{const b=await fixture();b.items[0].cancelled=true;const r=await importBatchBackup(await exportBatchBackup(b,'http://127.0.0.1:27621'),b.storeId,'http://127.0.0.1:27621');assert.equal(r.items[0].cancelled,undefined);assert.ok(r.items[0].submission);assert.throws(()=>retryCancelledItem(r.items[0]));});
