import './vendor_storefront_network_guard.cjs';
import fs from'node:fs';import os from'node:os';import path from'node:path';import test from'node:test';import assert from'node:assert/strict';import{gunzipSync}from'node:zlib';import{randomUUID}from'node:crypto';
import{loadVisualCatalogV24,VISUAL_ARTIFACT_SHA256}from'../../apps/web/src/lib/stores/scanVisualCatalogV24.mjs';
import{loadReferenceMetadataV27,validateMetadataEnvelopeV27,METADATA_SOURCE_SHA256}from'../../apps/web/src/lib/stores/scanReferenceMetadataV27.mjs';
const artifact='apps/web/src/lib/stores/scanExpandedMetadataV27.json.gz',bytes=fs.readFileSync(artifact),envelope=JSON.parse(gunzipSync(bytes));
test('every metadata row exactly equals the frozen full-catalog projection',()=>{const source=loadVisualCatalogV24('apps/web/src/lib/stores/scanExpandedCatalogV13.json.gz'),map=loadReferenceMetadataV27(artifact);assert.equal(METADATA_SOURCE_SHA256,VISUAL_ARTIFACT_SHA256);assert.equal(map.size,20079);assert.deepEqual([...map.values()],source.map(({id,gv_id,image_path,sha256})=>({id,gv_id,image_path,sha256})));});
test('metadata loading never opens the descriptor artifact and cannot mutate cached rows',()=>{const original=fs.readFileSync;fs.readFileSync=function(file,...args){assert.ok(!String(file).includes('scanExpandedCatalogV13'),'Full catalog is not allowed in this parent loader');return original.call(this,file,...args);};try{const map=loadReferenceMetadataV27(artifact),row=map.values().next().value;assert.throws(()=>{row.image_path='bad';});assert.equal(map.size,20079);}finally{fs.readFileSync=original;}});
test('missing, shortened and same-length tampered artifacts fail closed without fallback',()=>{const file=path.join(os.tmpdir(),'scan-v27-'+randomUUID()+'.gz');assert.throws(()=>loadReferenceMetadataV27(file));try{fs.writeFileSync(file,bytes.subarray(0,bytes.length-1));assert.throws(()=>loadReferenceMetadataV27(file));const bad=Buffer.from(bytes);bad[bad.length-4]^=1;fs.writeFileSync(file,bad);assert.throws(()=>loadReferenceMetadataV27(file));}finally{if(fs.existsSync(file))fs.unlinkSync(file);}});
test('envelope binds source version, count, exact identity keys and unique safe references',()=>{for(const mutate of[v=>v.sourceArtifactSha256='0'.repeat(64),v=>v.version='other',v=>v.rows.pop(),v=>v.rows[1]={...v.rows[0]},v=>v.rows[0].image_path='https://invalid.example/private',v=>v.rows[0].image_path='warehouse-derived/image-truth-v1/../a.jpg',v=>v.rows[0].id='invalid',v=>v.rows[0].sha256='invalid',v=>v.rows[0].gv_id=null,v=>v.rows[0].feature=[],v=>v.extra=true]){const value=structuredClone(envelope);mutate(value);assert.throws(()=>validateMetadataEnvelopeV27(value));}});
