import './vendor_storefront_network_guard.cjs';import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{createHash}from'node:crypto';import{gunzipSync}from'node:zlib';
import{prepareVisualIndex,VISUAL_VERSION}from'../../apps/web/src/lib/stores/visualMatchCore.mjs';import{shortlistVisualReferences}from'../../apps/web/src/lib/stores/scanShortlistV16.mjs';
const dir='.local/integration/vendor-scan-visual-v16';fs.mkdirSync(dir,{recursive:true});const hash=b=>createHash('sha256').update(b).digest('hex');
const catalog=JSON.parse(gunzipSync(fs.readFileSync('apps/web/src/lib/stores/scanExpandedCatalogV13.json.gz'))),references=prepareVisualIndex({version:VISUAL_VERSION,references:catalog});
const base=path.join(process.env.USERPROFILE,'.codex/tmp/vendor-real-scans-20260923'),prior=JSON.parse(fs.readFileSync('.local/integration/vendor-scan-expansion-v15/regression-2026-09-24T08-33-49-529Z.private.json'));
const rows=prior.rows.map(r=>({...r,path:path.join(base,r.corpus==='v2_100'?'holdout-v2/derived':r.corpus==='gallery_v12'?'gallery-v12/derived':'holdout-'+r.corpus+'/derived',r.file+(r.corpus==='v2_100'?'.jpg':''))}));
for(const [file,gv]of [['browser-preview-3f24400435b46194e24a4eab0f52f309023a8ecb484880fd8e284748d01f762c.jpg','GV-PK-LOR-TG02'],['browser-preview-24b1e46bd69e0d5c6c5ed3422eae09eb362a9d02271b20f327e0f9e131ae340e.jpg','GV-PK-ASR-TG02']])rows.push({corpus:'browser_heic',file,expected:[gv],path:path.resolve('.local/integration/vendor-scan-release-20260924',file)});
rows.push({corpus:'legacy',file:'scan-0075.jpeg.jpg',expected:['GV-PK-MEW-003'],path:path.join(base,'derived/scan-0075.jpeg.jpg')});assert.equal(rows.length,308);
const labels=rows.map(r=>({corpus:r.corpus,file:r.file,expected:r.expected,path:r.path,sha256:hash(fs.readFileSync(r.path))}));fs.writeFileSync(dir+'/labels.private.json',JSON.stringify(labels,null,2),{flag:'wx'});
const report={at:new Date().toISOString(),sourceHash:hash(fs.readFileSync('apps/web/src/lib/stores/scanShortlistV16.mjs')),scope:'development retrieval only, not recognition',rows:[]};
for(const label of labels){let ids=[],error;try{ids=await shortlistVisualReferences(fs.readFileSync(label.path),references,catalog);}catch(e){error=e.message;}report.rows.push({...label,ids,error,retrieved:ids.some(id=>label.expected.includes(catalog.find(c=>c.id===id).gv_id))});fs.writeFileSync(dir+'/shortlist.private.json',JSON.stringify(report,null,2));if(report.rows.length%25===0)console.log(JSON.stringify({processed:report.rows.length,retrieved:report.rows.filter(r=>r.retrieved).length}));}
report.finishedAt=new Date().toISOString();fs.writeFileSync(dir+'/shortlist.private.json',JSON.stringify(report,null,2));console.log(JSON.stringify({finished:true,retrieved:report.rows.filter(r=>r.retrieved).length,supported:labels.filter(l=>l.expected.length).length}));
