// One-use offline receipt. Reuses existing results, never reruns the fresh holdout.
import './vendor_storefront_network_guard.cjs';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {loadCatalogV8,sha256} from './vendor_scan_catalog_v8.mjs';
const work='.local/integration/vendor-scan-expansion-v11',base=path.join(process.env.USERPROFILE,'.codex/tmp/vendor-real-scans-20260923'),freshBase=path.join(base,'holdout-v11'),read=p=>JSON.parse(fs.readFileSync(p)),hash=p=>sha256(fs.readFileSync(p));
const regressionPath=work+'/regression-2026-09-24T06-46-42-951Z.private.json',regression=read(regressionPath),fresh=read(path.join(freshBase,'results.private.json')),selection=read(path.join(freshBase,'selection.private.json')),frozen=read(path.join(freshBase,'frozen-labels.private.json')),enriched=loadCatalogV8();
const matcherSha256=hash('apps/web/src/lib/stores/scanMatchV11.mjs');assert.equal(matcherSha256,'0b734bb136d0d27cfcd0493c82cb2a0836765e3c60056d194629a8eded850a3b');
assert.equal(selection.matcherSha256,matcherSha256);assert.equal(frozen.matcherSha256,matcherSha256);assert.deepEqual(selection.matcherDependencies,frozen.matcherDependencies);assert.equal(selection.metadataSha256,enriched.metadataSha256);assert.equal(frozen.metadataSha256,enriched.metadataSha256);
assert.ok(Date.parse(selection.at)<Date.parse(frozen.at)&&Date.parse(frozen.at)<Date.parse(fresh.at));
assert.equal(regression.rows.length,283);assert.equal(fresh.rows.length,19);assert.deepEqual(fresh.excluded,['fresh-0009.jpg']);
for(const report of [regression,fresh]){assert.ok(report.finishedAt);assert.equal(report.matcherSha256,matcherSha256);assert.equal(report.indexSha256,enriched.indexSha256);assert.equal(report.metadataSha256,enriched.metadataSha256);assert.deepEqual(Object.keys(report.dependencies).sort(),Object.keys(selection.matcherDependencies).sort());for(const [file,sha] of Object.entries(report.dependencies)){assert.equal(hash('apps/web/src/lib/stores/'+file),sha);assert.equal(selection.matcherDependencies[file],sha);}for(const r of report.rows){assert.equal(r.wrong,r.candidates.some(c=>!r.expected.includes(c.gv_id)));assert.equal(r.correct,r.candidates.length>0&&!r.wrong);}}
for(const row of fresh.rows){const label=frozen.labels.find(r=>r.file===row.file);assert.ok(label&&!label.previouslySeen);assert.ok(!selection.priorHashes.includes(label.originalSha256));assert.deepEqual(row.expected,label.expectedGvIds);assert.equal(hash(path.join(freshBase,'derived',row.file)),label.sha256);}
const prior=[...read('.local/integration/vendor-scan-expansion-v10/regression-2026-09-24T06-23-26-349Z.private.json').rows,...read(path.join(base,'holdout-v10/results.private.json')).rows.map(r=>({...r,corpus:'v10'}))];assert.equal(prior.length,283);const byKey=new Map(prior.map(r=>[r.corpus+':'+r.file,r]));const gained=[],lost=[],changedCandidates=[];
for(const r of regression.rows){const old=byKey.get(r.corpus+':'+r.file);assert.ok(old);assert.deepEqual(r.expected,old.expected);const identity={corpus:r.corpus,file:r.file,expected:r.expected};if(r.correct&&!old.correct)gained.push(identity);if(!r.correct&&old.correct)lost.push(identity);if(old.correct&&JSON.stringify(old.candidates.map(c=>c.gv_id))!==JSON.stringify(r.candidates.map(c=>c.gv_id)))changedCandidates.push(identity);}
const summarize=rows=>{const times=rows.map(r=>r.ms).sort((a,b)=>a-b);return {scans:rows.length,supported:rows.filter(r=>r.expected.length).length,correctSuggestions:rows.filter(r=>r.correct).length,wrongSuggestions:rows.filter(r=>r.wrong).length,ambiguous:rows.filter(r=>r.status==='ambiguous').length,unmatchedSupported:rows.filter(r=>r.expected.length&&!r.candidates.length).length,rejectedNegatives:rows.filter(r=>!r.expected.length&&!r.candidates.length).length,errors:rows.filter(r=>r.error).map(r=>({corpus:r.corpus??'fresh',file:r.file,supported:!!r.expected.length,error:r.error})),matchedStoredDenominator:rows.filter(r=>r.correct&&r.candidates.every(c=>c.printedIdentity?.totalMatch)).length,p50Ms:times[Math.floor(times.length*.5)],p95Ms:times[Math.floor(times.length*.95)],maxMs:times.at(-1)};};
const log=fs.readFileSync(work+'/node-tests.txt','utf8');assert.match(log,/# pass 47/);assert.match(log,/# fail 0/);const targeted=read(work+'/recovered-three.private.json');assert.equal(targeted.rows.length,3);assert.ok(targeted.rows.every(r=>r.candidates.length&&!r.wrong&&r.candidates.every(c=>c.printedIdentity.totalMatch)));
const oldProof=read('docs/audits/vendor_scan_expansion_v10/proof-20260924.json');assert.equal(hash('apps/web/src/lib/stores/scanMatchV10.mjs'),oldProof.matcherSha256);assert.equal(hash('apps/web/src/lib/stores/scanMatchV2.mjs'),'ac0b5ed5c19de6d5d1de77a9ac29e7080c6a874add34761110b73991be562409');
const files=[regressionPath,path.join(freshBase,'results.private.json'),path.join(freshBase,'selection.private.json'),path.join(freshBase,'frozen-labels.private.json'),path.join(freshBase,'derived-receipt.private.json'),work+'/recovered-three.private.json',work+'/full-confidence.private.json',work+'/recrop.private.json',work+'/promo-diagnostic.private.json',work+'/promo-reference-readback.private.json',work+'/node-tests.txt'];
const proof={at:new Date().toISOString(),scope:'Offline V11 only; not activated',sourceBaseline:'7ef0ba02040d290bfa390b8bd3882d7b960f4ccd',matcherSha256,dependencies:regression.dependencies,indexSha256:enriched.indexSha256,metadataSha256:enriched.metadataSha256,coverage:enriched.coverage,regression283:summarize(regression.rows),priorV10Same283:summarize(prior),comparison:{gained,lost,changedPriorCorrectCandidates:changedCandidates},targetedThree:{recovered:3,wrong:0,matchedStoredDenominator:3},fresh19:summarize(fresh.rows),freshExcluded:fresh.excluded,freshLabelCorrections:[],realPromoDevelopment:regression.rows.filter(r=>r.expected.some(id=>id.includes('SWSH'))).map(r=>({corpus:r.corpus,file:r.file,expected:r.expected,status:r.status,correct:r.correct})),freshPromoGalleryScans:0,checks:{nodePassed:47,nodeFailed:0,targetedEslint:'passed',fullHook:false,appBuild:false,hostedRuntime:false,physicalPhone:false},evidenceHashes:Object.fromEntries(files.map(p=>[p.replace(freshBase,'private-holdout-v11').replaceAll('\\','/'),hash(p)])),limitations:['Convenience scan bytes, not independently sampled physical cards. No second human labeler.','Local timing includes overlap with fresh evaluation; not hosted load or deadline proof.','Stored metadata is the frozen V8 snapshot; no new live eligibility or denominator audit. Known SLG78/73 conflict remains.','Artwork-only matches do not verify print identity or finish.','Real Flapple promo development scans fail visual admission; fresh promo/gallery proof still absent.'],initialHarnessFailure:'Dependency list initially named nonexistent scanOcrEvidenceV11; fixed to frozen V10 helper before any image evaluation. Failure log retained.',releaseReady:false,live:{matcher:'V2',references:321,deployment:'dpl_51kcAzAJggMdURgDoXkEordUerUH',changed:false}};
fs.mkdirSync('docs/audits/vendor_scan_expansion_v11',{recursive:true});fs.writeFileSync('docs/audits/vendor_scan_expansion_v11/proof-20260924.json',JSON.stringify(proof,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({regression:proof.regression283,prior:proof.priorV10Same283,fresh:proof.fresh19,gained:gained.length,lost:lost.length,changedPriorCorrectCandidates:changedCandidates.length}));
