// Exact production component and HTTP handlers backed by an isolated synthetic database.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';import{createServer}from'node:http';import{setTimeout as delay}from'node:timers/promises';
export async function startBrowserHarness({root,fixture,owner,token,status}){
 const web=path.join(root,'apps/web'),require=createRequire(path.join(web,'package.json')),{webpack}=require('next/dist/compiled/webpack/webpack');const dir=path.join(fixture,'browser-harness');fs.mkdirSync(dir,{recursive:true});
const loader=path.join(dir,'loader.cjs');
fs.writeFileSync(loader,`const ts=require(${JSON.stringify(require.resolve('typescript'))});module.exports=function(source){if(this.resourcePath.endsWith('.css')){const css=source.replace(/:global\\(([^)]+)\\)/g,'$1');return 'const style=document.createElement("style");style.textContent='+JSON.stringify(css)+';document.head.appendChild(style);export default '+JSON.stringify(Object.fromEntries([...source.matchAll(/\\.([a-zA-Z_][a-zA-Z0-9_-]*)/g)].map(m=>[m[1],m[1]])))+';';}return ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true},fileName:this.resourcePath}).outputText;};`);

const entry=path.join(dir,'entry.tsx');fs.writeFileSync(entry,"import React from 'react';import{createRoot}from'react-dom/client';import StoreBatchIntake from '@/components/stores/StoreBatchIntake';import{loadIntakeBatch}from '@/lib/stores/batchIntakeStorage';import s from '@/components/stores/StoreManager.module.css';\nconst owner=OWNER_FIXTURE;function App(){const[pending,setPending]=React.useState(false),[state,setState]=React.useState('');return <main className={s.workspace}><h1>Real scan → local inventory proof</h1><p>Isolated synthetic account · Real local Auth, Storage and SQL · No production or payment access</p><StoreBatchIntake owner={owner as any} close={()=>location.reload()} refresh={async()=>{}} onPendingChange={setPending}/><aside><h2>Test controls</h2>{['upload_once','finish_response_once','cancel_response_once','slow','none'].map(mode=><button disabled={pending} key={mode} onClick={async()=>{await fetch('/qa/fault',{method:'POST',body:JSON.stringify({mode})});setState('Fault mode: '+mode);}}>{'Set '+mode}</button>)}<button disabled={pending} onClick={async()=>{const b=await loadIntakeBatch(owner.store.id);const summary={at:new Date().toISOString(),batch:b?.id,items:b?.items.length,assets:b?.assets.length,originalBytes:b?.assets.reduce((n,a)=>n+a.original.size,0),previewBytes:b?.assets.reduce((n,a)=>n+(a.preview?.size??0),0),undecoded:b?.assets.filter(a=>!a.preview).length,confirmed:b?.items.filter(i=>i.confirmed).length,completed:b?.items.filter(i=>i.receipt).length,pending:b?.items.filter(i=>i.submission&&!i.receipt&&!i.cancelled).length,cancelled:b?.items.filter(i=>i.cancelled).length,jsHeapBytes:(performance as any).memory?.usedJSHeapSize,db:await(await fetch('/qa/status')).json()};await fetch('/qa/report',{method:'POST',body:JSON.stringify(summary)});setState(JSON.stringify(summary));}}>Check saved draft and database</button><pre role=\"status\">{state}</pre></aside></main>}createRoot(document.getElementById('root')!).render(<App/>);".replace('OWNER_FIXTURE',JSON.stringify(owner)));
await new Promise((resolve,reject)=>webpack({mode:'development',devtool:false,entry,context:web,output:{path:path.join(dir,'dist'),filename:'bundle.js',publicPath:'/'},resolve:{extensions:['.tsx','.ts','.js'],alias:{'@':path.join(web,'src')},modules:[path.join(web,'node_modules'),path.join(root,'node_modules')]},module:{rules:[{test:/\.(tsx?|css)$/,exclude:/node_modules/,use:loader}]},plugins:[new (require('next/dist/compiled/webpack/webpack').webpack.DefinePlugin)({'process.env.NEXT_PUBLIC_SUPABASE_URL':JSON.stringify('http://127.0.0.1:27621')})],optimization:{minimize:false}},(error,stats)=>error||stats.hasErrors()?reject(error||new Error(stats.toString({all:false,errors:true}))):resolve()));

let mode='none',faults=[];const reports=[];
const server=createServer(async(req,res)=>{res.setHeader('cache-control','no-store');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data: http://127.0.0.1:27621; connect-src 'self'; worker-src 'self' blob:");const url=new URL(req.url,'http://127.0.0.1:27643');const json=(body,status=200)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(body));};try{
const chunks=[];let length=0;if(req.method==='POST')for await(const chunk of req){length+=chunk.length;if(length>5*1024*1024){res.writeHead(413).end();return;}chunks.push(chunk);}const bytes=Buffer.concat(chunks);
if(url.pathname==='/qa/status'){json(await status());return;}
if(url.pathname==='/qa/fault'&&req.method==='POST'){const next=JSON.parse(bytes).mode;assert.ok(['upload_once','finish_response_once','cancel_response_once','slow','none'].includes(next));mode=next;json({mode});return;}
if(url.pathname==='/qa/report'&&req.method==='POST'){const report=JSON.parse(bytes);reports.push(report);fs.writeFileSync(path.join(dir,'reports.private.json'),JSON.stringify({reports,faults},null,2));json({saved:true});return;}
if(url.pathname.startsWith('/api/')){
 if(mode==='slow')await delay(1200);
 if(mode==='upload_once'&&url.pathname.endsWith('/media')){mode='none';faults.push({type:'upload_interrupted',at:new Date().toISOString()});json({error:'Local QA interrupted the upload. Resume or cancel this saved attempt.'},503);return;}
 const headers={authorization:'Bearer '+token,origin:'http://127.0.0.1:27640','content-type':req.headers['content-type']??'application/json'};
 const upstream=await fetch('http://127.0.0.1:27640'+url.pathname+url.search,{method:req.method,headers,body:req.method==='POST'?bytes:undefined,signal:AbortSignal.timeout(90000)});const body=Buffer.from(await upstream.arrayBuffer());
 if(upstream.ok&&((mode==='finish_response_once'&&url.pathname.endsWith('/finish'))||(mode==='cancel_response_once'&&url.pathname.endsWith('/cancel')))){faults.push({type:mode,at:new Date().toISOString(),upstreamStatus:upstream.status});mode='none';json({error:'Local QA discarded a successful response. Its server transaction is retained.'},503);return;}
 res.writeHead(upstream.status,{'content-type':upstream.headers.get('content-type')??'application/json'});res.end(body);return;
}
if(url.pathname==='/'){res.setHeader('content-type','text/html; charset=utf-8');res.end('<!doctype html><html class="gv-dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Grookai real database scan proof</title><style>body{background:#111518;color:#eee;font-family:system-ui;margin:20px}#root{max-width:1500px;margin:auto}button{cursor:pointer}pre{white-space:pre-wrap;overflow-wrap:anywhere}</style></head><body><div id="root"></div><script src="/bundle.js"></script></body></html>');return;}
const name=url.pathname.slice(1);if(/^[a-zA-Z0-9_.-]+\.js$/.test(name)&&fs.existsSync(path.join(dir,'dist',name))){res.setHeader('content-type','text/javascript');res.end(fs.readFileSync(path.join(dir,'dist',name)));return;}res.writeHead(404).end();
}catch(error){json({error:error.message},500);}});
const other=createServer(server.listeners('request')[0]);await new Promise(resolve=>server.listen(27643,'127.0.0.1',resolve));await new Promise(resolve=>other.listen(27644,'127.0.0.1',resolve));return{reports,faults,close:async()=>{server.closeAllConnections();other.closeAllConnections();await Promise.all([new Promise(resolve=>server.close(resolve)),new Promise(resolve=>other.close(resolve))]);}};
}
