import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{createHash}from'node:crypto';
const read=p=>JSON.parse(fs.readFileSync(p)),hash=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const local='.local/integration/vendor-scan-runtime-v27',base='.local/integration/vendor-scan-hosted-v27-baseline',meta='.local/integration/vendor-scan-hosted-v27-metadata',dest='docs/audits/vendor_scan_runtime_v27/PROOF_20260924.json';assert.ok(!fs.existsSync(dest));
const priorPath='docs/audits/vendor_scan_runtime_v26/PROOF_20260924.json',prior=read(priorPath),runtimePath=local+'/runtime-final.private.json',runtime=read(runtimePath);
assert.equal(runtime.summary.same,17);assert.equal(runtime.summary.errors,0);for(const[n,h]of Object.entries(runtime.sourceHashes))assert.equal(hash('apps/web/src/lib/stores/'+n),h);
for(const[p,h]of Object.entries(prior.sourceHashes))if(p!=='apps/web/src/lib/stores/scanVisualServerV24.ts')assert.equal(hash(p),h);
for(const[p,h]of Object.entries(read('docs/audits/vendor_scan_visual_v23/PROOF_20260924.json').sourceHashes))assert.equal(hash(p),h);
const testsPath=local+'/tests.txt',tests=fs.readFileSync(testsPath,'utf8');assert.match(tests,/# tests 39\b/);assert.match(tests,/# fail 0\b/);assert.equal(fs.statSync(local+'/typecheck.txt').size,0);assert.equal(fs.statSync(local+'/lint.txt').size,0);
const artifactPath='apps/web/src/lib/stores/scanExpandedMetadataV27.json.gz',generation=read(local+'/metadata-generation.json'),readback=read(local+'/metadata-readback.json');assert.equal(generation.sha256,hash(artifactPath));assert.equal(readback.sha256,generation.sha256);assert.equal(generation.rows,20079);
const bpath=base+'/hosted-proof.private.json',mpath=meta+'/hosted-proof.private.json',b=read(bpath),m=read(mpath);for(const r of[b,m]){assert.equal(r.status,'passed');assert.equal(r.rows.length,7);assert.ok(r.rows.every(x=>x.same)&&r.checks.every(x=>x.passed)&&r.retainedDataUnchanged);}
assert.ok(m.cancellation.passed&&m.cancellation.firstRetryHttp===200);assert.deepEqual(m.concurrency.map(x=>x.http).sort(),[200,429]);
function resource(dir,n){const file=fs.readdirSync(dir).filter(x=>/^resources-.*\.json$/.test(x)).sort().reverse().find(f=>read(dir+'/'+f).summary.resources===n);assert.ok(file);return{file:dir+'/'+file,data:read(dir+'/'+file)};}
const br=resource(base,7),mr=resource(meta,12);assert.ok(mr.data.summary.aborted>=1);
const pixelPath=meta+'/pixel-boundary-card-aspect.private.json',pixel=read(pixelPath);assert.equal(pixel.status,'passed');assert.ok(pixel.retainedDataUnchanged);assert.deepEqual(pixel.rows.map(x=>x.http),[200,503]);
for(const dir of[base,meta]){assert.equal(read(dir+'/ready.json').state,'READY');const plan=read(dir+'/package.json');for(const f of plan.files){assert.equal(hash(path.join(plan.dest,f.path)),f.sha256);assert.equal(hash(f.path),f.sha256);}}
assert.deepEqual(read(base+'/package.json').files,read(meta+'/package.json').files);
const files=[...Object.keys(prior.sourceHashes),'apps/web/src/lib/stores/scanReferenceMetadataV27.mjs','apps/web/src/lib/stores/scanReferenceMetadataV27.d.mts',artifactPath],sourceHashes=Object.fromEntries(files.map(f=>[f,hash(f)]));
const harnesses=['scripts/tests/vendor_scan_metadata_v27.test.mjs','scripts/tests/vendor_scan_metadata_generate_v27.mjs','scripts/tests/vendor_scan_parent_profile_v27.mjs','scripts/tests/vendor_scan_visual_server_v24.test.mjs','scripts/tests/vendor_scan_visual_runtime_v27.mjs',...['hosting','hosted-proof','resources','pixel-boundary'].map(n=>'scripts/preview/vendor-pilot/visual-v27-'+n+'.mjs')];
const times=r=>{const t=r.rows.map(x=>x.ms).sort((a,b)=>a-b);return{minMs:t[0],medianMs:t[3],maxMs:t.at(-1)};};
const summarize=rows=>Object.fromEntries(['parentPeakRssBytes','parentLifetimeHighWaterBytes','childPeakRssBytes','combinedPeakRssBytes'].map(k=>[k,Math.max(...rows.map(r=>r.resources?.[k]??0))]));
const proof={at:new Date().toISOString(),baseline:prior.baseline,precedingProofSha256:hash(priorPath),sourceHashes,harnessHashes:Object.fromEntries(harnesses.map(f=>[f,hash(f)])),algorithmUnchanged:true,metadata:{...generation,allRowsEqualFrozenProjection:true,readbackReceiptSha256:hash(local+'/metadata-readback.json')},tests:{passed:39,failed:0,receiptSha256:hash(testsPath),typecheckPassed:true,lintPassed:true},local:{...runtime.summary,receiptSha256:hash(runtimePath),parentProfile:read(local+'/parent-profile.json'),parentProfileSha256:hash(local+'/parent-profile.json')},hosting:[base,meta].map(dir=>({...read(dir+'/ready.json'),packageSha256:hash(dir+'/package.json')})),comparison:{identicalPackages:true,sameV25Worker:true,v26Pipeline:false,baseline:{...times(b),cases:7,same:7,receiptSha256:hash(bpath),normalCaseResources:summarize(br.data.rows),resources:br.data.summary,resourceReceiptSha256:hash(br.file),rawLogsSha256:hash(base+'/'+br.data.source)},metadata:{...times(m),cases:7,same:7,receiptSha256:hash(mpath),normalCaseResources:summarize(mr.data.rows.slice(0,7)),resources:mr.data.summary,resourceReceiptSha256:hash(mr.file),rawLogsSha256:hash(meta+'/'+mr.data.source)},controlledLatencyComparison:false,demonstratedLatencyImprovement:false,cgroupEnvelopeKnown:false,notes:'Sequential cloud builds. Parent-only local comparisons and hosted sampled RSS show memory reduction. Summed RSS double-counts shared pages and excludes other processes; parent HWM is lifetime. No request-latency win is claimed.'},accessChecks:m.checks,concurrency:m.concurrency,cancellation:{...m.cancellation,serverAbortObserved:true},pixelBoundary:{rows:pixel.rows,retainedDataUnchanged:true,receiptSha256:hash(pixelPath)},resourceDashboard:read(local+'/resource-dashboard.json'),resourceDashboardSha256:hash(local+'/resource-dashboard.json'),browser:{runThisTurn:false,frontendSourcesUnchanged:true,precedingReceiptSha256:prior.browser.receiptSha256},retainedDataUnchanged:true,device:read(local+'/device-readback.json'),sharedAliasChanged:false,sharedDeployment:'dpl_F9id47NjSDscTwE2wx1F1gWpgGRR',productionWrites:0,schemaChanges:0,entitlementWrites:0,paymentsEnabled:false,releaseQualified:false,remaining:['Reduce worker reference-preparation CPU without changing recognition decisions','Deployment-pinned resource envelope; dashboard route tooltip is not pinned','Physical phone workflow: Samsung currently disconnected','Governed pilot activation after qualification; production separate']};
fs.writeFileSync(dest,JSON.stringify(proof,null,2),{flag:'wx'});console.log(JSON.stringify({proof:dest,tests:39,localCases:17,hostedCases:14,resourceSummaries:19,releaseQualified:false}));
