import './vendor_storefront_network_guard.cjs';import fs from'node:fs';import assert from'node:assert/strict';import{createRequire}from'node:module';import{createHash}from'node:crypto';import{gunzipSync}from'node:zlib';
import{prepareGeometryImage,verifyGeometry}from'../../apps/web/src/lib/stores/scanGeometryV16.mjs';
const require=createRequire(new URL('../../.local/integration/opencv-runtime-v16/package.json',import.meta.url)),cv=require('@techstark/opencv-js');if(!cv.Mat)await new Promise(resolve=>{cv.onRuntimeInitialized=resolve;});
const dir='.local/integration/vendor-scan-visual-v16',read=p=>JSON.parse(fs.readFileSync(p)),hash=b=>createHash('sha256').update(b).digest('hex'),shortlist=read(dir+'/shortlist.private.json');assert.ok(shortlist.finishedAt);
const catalog=JSON.parse(gunzipSync(fs.readFileSync('apps/web/src/lib/stores/scanExpandedCatalogV13.json.gz'))),byId=new Map(catalog.map(c=>[c.id,c])),images=new Map(read('.local/integration/vendor-scan-release-20260924/image-plan.private.json').images.map(r=>[r.id,r]));
const previous=read('.local/integration/vendor-scan-expansion-v15/regression-2026-09-24T08-33-49-529Z.private.json'),cache=new Map(),source=fs.readFileSync('apps/web/src/lib/stores/scanGeometryV16.mjs'),report={at:new Date().toISOString(),sourceSha256:hash(source),shortlistSha256:hash(fs.readFileSync(dir+'/shortlist.private.json')),scope:'308 development files; visual-only candidate, not deployed',rows:[]};
async function reference(id){if(cache.has(id)){const value=cache.get(id);cache.delete(id);cache.set(id,value);return value;}const row=images.get(id),bytes=fs.readFileSync(row.source);assert.equal(hash(bytes),row.sha256);const value=await prepareGeometryImage(cv,bytes);cache.set(id,value);if(cache.size>96){const first=cache.keys().next().value;cache.get(first).dispose();cache.delete(first);}return value;}
try{for(const label of shortlist.rows){const start=performance.now();let candidates=[],error,scan;try{
const bytes=fs.readFileSync(label.path);assert.equal(hash(bytes),label.sha256);scan=await prepareGeometryImage(cv,bytes);for(const id of label.ids){const result=verifyGeometry(cv,await reference(id),scan);if(result)candidates.push({id,gv_id:byId.get(id).gv_id,...result});}
}catch(e){error=e.message;}finally{scan?.dispose();}
const previousRow=previous.rows.find(r=>r.corpus===label.corpus&&r.file===label.file),expectedRotation=label.corpus==='legacy'?180:label.corpus==='browser_heic'?0:label.corpus==='gallery_v12'?(label.file==='gallery-3.jpg'?180:0):undefined;
const wrong=candidates.some(c=>!label.expected.includes(c.gv_id)||expectedRotation!==undefined&&c.rotation!==expectedRotation),correct=!!candidates.length&&!wrong;
report.rows.push({corpus:label.corpus,file:label.file,expected:label.expected,candidates,error,correct,wrong,previousCorrect:previousRow?.correct??false,ms:Math.round(performance.now()-start)});fs.writeFileSync(dir+'/geometry-js-regression.private.json',JSON.stringify(report,null,2));if(report.rows.length%20===0)console.log(JSON.stringify({processed:report.rows.length,correct:report.rows.filter(r=>r.correct).length,wrong:report.rows.filter(r=>r.wrong).length}));
}}finally{for(const value of cache.values())value.dispose();}
assert.equal(hash(fs.readFileSync('apps/web/src/lib/stores/scanGeometryV16.mjs')),report.sourceSha256);report.finishedAt=new Date().toISOString();report.summary={scans:report.rows.length,correct:report.rows.filter(r=>r.correct).length,wrong:report.rows.filter(r=>r.wrong).length,previousLosses:report.rows.filter(r=>r.previousCorrect&&!r.correct).length,peakRss:process.resourceUsage().maxRSS*1024};fs.writeFileSync(dir+'/geometry-js-regression.private.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report.summary));
