import fs from'node:fs';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{createRequire}from'node:module';import{spawn,execFileSync}from'node:child_process';
const root='C:/gv_vendor_receipts_20261002',proof='C:/gv_store_reconcile_414_20261001',req=createRequire(root+'/package.json'),webReq=createRequire(root+'/apps/web/package.json'),{Client}=req('pg'),{createClient}=webReq('@supabase/supabase-js'),{chromium,expect}=webReq('@playwright/test');
const cfg=JSON.parse(fs.readFileSync(proof+'/.local/reconcile414/full/runtime-config.private.json'));assert.equal(cfg.API_URL,'http://127.0.0.1:41421');assert.equal(new URL(cfg.DB_URL).port,'41422');
const out=root+'/.local/receipt-release/web-proof-'+Date.now();fs.mkdirSync(out);const db=new Client({connectionString:cfg.DB_URL}),admin=createClient(cfg.API_URL,cfg.SECRET_KEY,{auth:{persistSession:false}});await db.connect();
let owner,buyer,browser,app,failure,removed=false;const set=randomUUID(),card=randomUUID(),legacy=randomUUID(),instance=randomUUID(),sale=randomUUID(),password=randomUUID()+randomUUID(),checks=[],errors=[];
try{
 assert.equal((await db.query('select count(*)::int n from auth.users')).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from vendor_orders')).rows[0].n,0);
 for(const who of ['owner','buyer']){const r=await admin.auth.admin.createUser({email:'receipt-'+who+'@fixture.invalid',password,email_confirm:true});assert.equal(r.error,null);if(who==='owner')owner=r.data.user.id;else buyer=r.data.user.id;}
 await db.query("insert into sets(id,code,name,game) values($1,'receipt-fixture','Synthetic receipt set','pokemon')",[set]);
 await db.query("insert into card_prints(id,game_id,set_id,name,number,set_code,gv_id,image_status) values($1,(select id from games where code='pokemon'),$2,'Synthetic receipt card','001','receipt-fixture','GV-PK-RECEIPTFIXTURE-001','missing')",[card,set]);
 await db.query("insert into vault_items(id,user_id,card_id,name,gv_id) values($1,$2,$3,'Synthetic receipt card','GV-PK-RECEIPTFIXTURE-001')",[legacy,owner,card]);
 await db.query("insert into vault_item_instances(id,user_id,card_print_id,legacy_vault_item_id,gv_vi_id,archived_at) values($1,$2,$3,$4,'GVVI-RECEIPT-000001',now())",[instance,owner,card,legacy]);
 await db.query("insert into vault_item_instance_dispositions(id,user_id,vault_item_instance_id,card_print_id,gv_vi_id,disposition_type,sale_price_amount,sale_price_currency,counterparty_label) values($1,$2,$3,$4,'GVVI-RECEIPT-000001','sale',12.34,'USD','Synthetic customer')",[sale,owner,instance,card]);
 const fd=fs.openSync(out+'/web.private.log','wx');try{app=spawn(process.execPath,[root+'/.local/receipt-release/run.mjs','web'],{cwd:root,windowsHide:true,stdio:['ignore',fd,fd]});}finally{fs.closeSync(fd);}
 const base='http://127.0.0.1:15440';for(let n=0;;n++){assert.equal(app.exitCode,null);try{if((await fetch(base+'/account/store/receipts',{redirect:'manual'})).status===307)break;}catch{}assert.ok(n<50,'Next not ready');await new Promise(r=>setTimeout(r,500));}
 browser=await chromium.launch({headless:true});
 async function context(){const c=await browser.newContext({viewport:{width:1440,height:1000}});await c.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());return c;}
 const oc=await context(),bc=await context(),anon=await context();const response=await anon.request.get(base+'/account/store/receipts?sale='+sale,{maxRedirects:0});assert.equal(response.status(),307);assert.ok(response.headers().location.includes('/login?next='));
 async function login(c,who){const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/account/store/receipts?sale='+sale);await p.waitForURL(/\/login\?next=/);assert.equal(new URL(p.url()).searchParams.get('next'),'/account/store/receipts?sale='+sale);await p.getByLabel('Email',{exact:true}).fill('receipt-'+who+'@fixture.invalid');await p.getByLabel('Password',{exact:true}).fill(password);await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.waitForURL(base+'/account/store/receipts?sale='+sale);return p;}
 const op=await login(oc,'owner'),bp=await login(bc,'buyer');await expect(bp.getByText('This recorded sale is unavailable for your account.',{exact:true})).toBeVisible();await expect(bp.getByText('GVVI-RECEIPT-000001',{exact:true})).toHaveCount(0);
 await expect(op.getByLabel('Item / card',{exact:true})).toHaveValue('GVVI-RECEIPT-000001');await expect(op.getByLabel('Unit price (USD)',{exact:true})).toHaveValue('12.34');await expect(op.getByLabel('Name',{exact:true})).toHaveValue('Synthetic customer');checks.push('actual Auth/cookie Next page preserves safe destination; owner reads saved sale through RLS, buyer and anonymous cannot read source');
 const mutations=[];op.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))mutations.push(new URL(r.url()).pathname);});
 await op.getByLabel('Store / seller name').fill('Synthetic receipt store');await op.getByLabel('Email',{exact:true}).fill('receipt@example.invalid');await op.getByLabel('Private customer notes').fill('PRIVATE_OWNER_NOTE');await op.getByLabel('I received this payment and the sale is complete.').check();await op.getByRole('button',{name:'Save sale & create receipt'}).click();await expect(op.locator('dd.rd-total')).toHaveText('$12.34');await op.reload();await expect(op.locator('dd.rd-total')).toHaveText('$12.34');await expect(op.getByText('Sale saved on this device',{exact:true})).toBeVisible();
 await bp.goto(base+'/account/store/receipts');await expect(bp.getByRole('heading',{name:'Receipt desk',exact:true})).toBeVisible();await expect(bp.locator('[data-open]')).toHaveCount(0);await expect(bp.getByText('PRIVATE_OWNER_NOTE',{exact:true})).toHaveCount(0);
 await op.screenshot({path:out+'/desktop.png',fullPage:true});await op.setViewportSize({width:390,height:844});await op.screenshot({path:out+'/mobile.png',fullPage:true});assert.equal(await op.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(mutations,[]);assert.deepEqual(errors,[]);assert.equal((await db.query('select sale_price_amount::text p from vault_item_instance_dispositions where id=$1',[sale])).rows[0].p,'12.34');assert.equal((await db.query('select count(*)::int n from vault_item_instance_dispositions')).rows[0].n,1);checks.push('actual compiled receipt desk saves/reopens account-scoped device record, shows mobile/desktop, sends zero mutation requests and leaves source sale unchanged');
}catch(e){failure=e;}finally{
 await browser?.close();if(app&&app.exitCode===null){execFileSync('taskkill',['/PID',String(app.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});}
 // Kill only the child Next instance this driver started; run.mjs may exit before its child.
 if(owner){await db.query('begin');try{await db.query('set local session_replication_role=replica');await db.query('delete from vault_item_instance_dispositions where id=$1',[sale]);await db.query('delete from vault_item_instances where id=$1',[instance]);await db.query('delete from vault_items where id=$1',[legacy]);await db.query('delete from pricing_watch where card_print_id=$1',[card]);await db.query('delete from card_prints where id=$1',[card]);await db.query('delete from sets where id=$1',[set]);await db.query('delete from card_events where actor_user_id=any($1::uuid[]) or subject_user_id=any($1::uuid[])',[[owner,buyer].filter(Boolean)]);await db.query('set local session_replication_role=origin');await db.query('delete from auth.users where id=any($1::uuid[])',[[owner,buyer].filter(Boolean)]);await db.query('commit');}catch(e){await db.query('rollback');failure??=e;}}
 removed=(await db.query('select count(*)::int n from auth.users')).rows[0].n===0;await db.end();
}
const receipt={status:failure?'failed':'passed',at:new Date().toISOString(),checks,fixturesRemoved:removed,actualAuth:true,actualNext:true,actualPostgres:true,productionWrites:0,messagesSent:0,error:failure?.stack};fs.writeFileSync(out+'/receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify({...receipt,out}));if(failure)process.exitCode=1;
