import fs from 'node:fs';import path from'node:path';import assert from'node:assert/strict';import {createRequire}from'node:module';import{fileURLToPath,pathToFileURL}from'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),out=root+'/artifacts/receipts',{chromium,expect}=createRequire(root+'/apps/web/package.json')('@playwright/test');
const browser=await chromium.launch({headless:true}),context=await browser.newContext({acceptDownloads:true,viewport:{width:1365,height:1000}}),page=await context.newPage(),errors=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));await context.route('**/*',r=>{requests.push(r.request().url());return r.request().url().startsWith('file:')?r.continue():r.abort();});
let failure;
try{
 const url=pathToFileURL(out+'/Grookai-Receipt-Desk.html').href;await page.goto(url);await expect(page.getByRole('heading',{name:'Receipt desk'})).toBeVisible();
 await page.getByLabel('Store / seller name').fill('Demo Cards');await page.getByLabel('Item / card',{exact:true}).fill('Pikachu — Near mint');await page.getByLabel('Unit price (USD)',{exact:true}).fill('12.34');await page.getByLabel('Qty',{exact:true}).fill('2');
 await page.getByRole('button',{name:'+ Add item',exact:true}).click();await page.getByLabel('Item / card',{exact:true}).nth(1).fill('Charizard sleeve');await page.getByLabel('Unit price (USD)',{exact:true}).nth(1).fill('1.00');
 await page.getByLabel('Discount (USD)').fill('1.00');await page.getByLabel('Tax collected (USD)').fill('2.00');await page.getByLabel('Name',{exact:true}).fill('Synthetic buyer');await page.getByLabel('Email',{exact:true}).fill('buyer@example.invalid');await page.getByLabel('Phone',{exact:true}).fill('+1 555 010 1234');await page.getByLabel('What are they looking for?').fill('NM Pikachu under $50');await page.getByLabel('Private customer notes').fill('PRIVATE_FIXTURE_NOTE');
 await page.getByLabel('I received this payment and the sale is complete.').check();await page.getByRole('button',{name:'Save sale & create receipt'}).click();await expect(page.getByText('Sale saved on this device',{exact:true})).toBeVisible();await expect(page.locator('dd.rd-total')).toHaveText('$26.68');
 const backupPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Back up records'}).click();const backup=await backupPromise;await backup.saveAs(out+'/synthetic-backup.json');const book=JSON.parse(fs.readFileSync(out+'/synthetic-backup.json'));assert.equal(book.receipts.length,1);assert.equal(book.customers.length,1);
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download receipt',exact:true}).click();const download=await downloadPromise;await download.saveAs(out+'/synthetic-receipt.html');const html=fs.readFileSync(out+'/synthetic-receipt.html','utf8');assert.doesNotMatch(html,/PRIVATE_FIXTURE_NOTE|buyer@example.invalid|555 010|under \$50/);
 const popupPromise=context.waitForEvent('page');await page.getByRole('button',{name:'Print / save PDF',exact:true}).click();const popup=await popupPromise;await expect(popup.getByRole('heading',{name:'Demo Cards',exact:true})).toBeVisible();await popup.close();
 const printable=await context.newPage();await printable.goto(pathToFileURL(out+'/synthetic-receipt.html').href);await expect(printable.getByText(/TOTAL: \$26.68/)).toBeVisible();await printable.screenshot({path:out+'/receipt.png',fullPage:true});await printable.close();
 await page.screenshot({path:out+'/desk-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/desk-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.reload();await page.locator('[data-open]').click();await expect(page.locator('dd.rd-total')).toHaveText('$26.68');
 await page.getByRole('button',{name:'New sale',exact:true}).click();await page.locator('[data-customer]').selectOption(book.customers[0].id);await expect(page.getByLabel('Phone',{exact:true})).toHaveValue('+1 555 010 1234');await expect(page.getByLabel('What are they looking for?')).toHaveValue('NM Pikachu under $50');
 await page.getByLabel('Item / card',{exact:true}).fill('Eevee');await page.getByLabel('Unit price (USD)',{exact:true}).fill('5');await page.getByLabel('I received this payment and the sale is complete.').check();await page.getByRole('button',{name:'Save sale & create receipt'}).click();await expect(page.getByText(/2 saved purchase/)).toBeVisible();
 await page.getByLabel('Find a receipt or customer').fill('555');await expect(page.locator('[data-open]')).toHaveCount(2);await page.getByLabel('Find a receipt or customer').fill('not-present');await expect(page.locator('[data-open]')).toHaveCount(0);
 const blank=await browser.newContext(),restore=await blank.newPage();await restore.goto(url);await restore.getByLabel('Restore receipt backup').setInputFiles(out+'/synthetic-backup.json');await expect(restore.getByText('Backup restored on this device.',{exact:true})).toBeVisible();await restore.locator('[data-open]').click();await expect(restore.locator('dd.rd-total')).toHaveText('$26.68');await restore.getByLabel('Restore receipt backup').setInputFiles(out+'/synthetic-backup.json');await expect(restore.getByRole('alert')).toContainText('only in an empty receipt book');await blank.close();
 // An actual storage-write failure must retain the draft and never claim success.
 await page.getByRole('button',{name:'New sale',exact:true}).click();await page.getByLabel('Item / card',{exact:true}).fill('Unsaved');await page.getByLabel('Unit price (USD)',{exact:true}).fill('5');await page.getByLabel('I received this payment and the sale is complete.').check();await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw Error('quota exceeded');};});await page.getByRole('button',{name:'Save sale & create receipt'}).click();await expect(page.getByRole('alert')).toContainText('sale was not saved');await expect(page.getByLabel('Item / card',{exact:true})).toHaveValue('Unsaved');
 assert.deepEqual(errors,[]);assert.ok(requests.every(u=>u.startsWith('file:')));
}catch(e){failure=e;}finally{await browser.close();}
const receipt={status:failure?'failed':'passed',at:new Date().toISOString(),actualBrowser:true,externalNetworkRequests:requests.filter(u=>!u.startsWith('file:')).length,realCustomerData:false,checks:['two-item exact totals','device persistence/reopen','private customer notes excluded from receipt','HTML receipt download and print popup','repeat customer reuse','receipt/customer search','backup restore and overwrite refusal','storage failure retains draft','desktop/mobile no overflow'],error:failure?.stack};fs.writeFileSync(out+'/browser-proof.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));if(failure)process.exitCode=1;
