// Read-only production comparison against the isolated 400-migration lab.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {guard,fixture,sql,hash,root} from './storefront_production_lab_v1.mjs';
import {snapshotSql,compareSnapshots} from 'file:///C:/gv_store_billing_20260919/scripts/schema/vendor_billing_schema_v1.mjs';
assert.equal(process.argv.length,2);
const localGuard=guard();assert.equal(localGuard.migrations,400);
const target='ycdxbpibncqcchqiihfz';
const output=path.join(fixture,`baseline-audit-${new Date().toISOString().replaceAll(':','-')}`);
fs.mkdirSync(output,{recursive:false});
const dependencies=['vendor_billing_schema_v1.mjs','column_order_reconciliation_v1.mjs','audit_collector_schema_baseline_v1.mjs'];
const dependencyHashes=Object.fromEntries(dependencies.map(name=>[name,hash(fs.readFileSync(`C:/gv_store_billing_20260919/scripts/schema/${name}`))]));
fs.writeFileSync(path.join(output,'read-only.sql'),snapshotSql,{flag:'wx'});
const token=execFileSync('pwsh',['-NoProfile','-File','C:/gv_store_billing_20260919/scripts/preview/collector_management_credential.ps1'],{encoding:'utf8',windowsHide:true,stdio:['ignore','pipe','pipe']}).trim();
assert.match(token,/^sbp_/);
const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};
const projectResponse=await fetch(`https://api.supabase.com/v1/projects/${target}`,{headers});
assert.equal(projectResponse.status,200,'Cannot verify production target');
const project=await projectResponse.json();assert.equal(project.id,target);
const local=JSON.parse(sql(snapshotSql));
const response=await fetch(`https://api.supabase.com/v1/projects/${target}/database/query`,{method:'POST',headers,body:JSON.stringify({query:snapshotSql}),signal:AbortSignal.timeout(180000)});
assert.ok(response.ok,`Read-only snapshot HTTP ${response.status}`);
const remote=(await response.json())[0]?.receipt;assert.ok(remote);assert.equal(remote.read_only,'on');
fs.writeFileSync(path.join(output,'local.private.json'),JSON.stringify(local));
fs.writeFileSync(path.join(output,'production.private.json'),JSON.stringify(remote));
assert.equal(local.LEDGER.length,400);assert.deepEqual(local.LEDGER,remote.LEDGER);
const comparison=await compareSnapshots(remote,local,{reconcile:true,output});
const result={at:new Date().toISOString(),status:'passed',target,local:localGuard,productionSanity:remote.sanity,comparison,dependencyHashes,productionWrites:0};
fs.writeFileSync(path.join(output,'receipt.json'),JSON.stringify(result,null,2));
fs.writeFileSync(path.join(root,'docs/audits/storefront_production_20260926/baseline-schema.json'),JSON.stringify(result,null,2));
console.log(JSON.stringify(result));
