// Read-only428 baseline. No migration application or local service changes.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {snapshotSql,compareSnapshots} from './vendor_billing_schema_v1.mjs';
import {query,ref,dbUrl} from '../release/storefront_production_live_common_v1.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url));
assert.equal(fs.realpathSync(root).replaceAll('\\','/').toLowerCase(),'c:/gv_receipt_delivery_20261005');
assert.equal(ref,'ycdxbpibncqcchqiihfz');assert.equal(new URL(dbUrl).hostname,ref+'.supabase.co');
assert.ok(fs.readFileSync(root+'supabase/config.toml','utf8').includes('project_id = "'+ref+'"'));
const prior='C:/grookai_vault_operator_artifacts/collectr_sealed_save_20261005/full-428-v3';
const read=n=>JSON.parse(fs.readFileSync(prior+'/'+n));
const freeze=read('freeze.json'),proof=read('replay-result.json');
assert.equal(proof.status,'passed');assert.equal(proof.migrations,428);assert.ok(proof.fullReplay&&proof.noOpPush);
const hash=b=>createHash('sha256').update(b).digest('hex');
const names=fs.readdirSync(root+'supabase/migrations').filter(n=>n.endsWith('.sql')).sort();
assert.equal(Object.keys(freeze.sourceHashes).length,428);
for(const [n,h]of Object.entries(freeze.sourceHashes))assert.equal(hash(fs.readFileSync(root+'supabase/migrations/'+n)),h,n);
const pending=names.filter(n=>!freeze.sourceHashes[n]);
assert.ok(pending.length===0||(pending.length===1&&pending[0]==='20261005150000_vendor_receipt_delivery_v1.sql'));
const local=read('replayed.private.json'),remote=(await query(snapshotSql))[0].receipt;
assert.equal(remote.LEDGER.length,428);assert.deepEqual(remote.LEDGER,local.LEDGER);
assert.ok(remote.sanity.cards>=40000&&remote.sanity.sets>=150&&remote.sanity.traits>=5000);
const out='C:/grookai_vault_operator_artifacts/receipt_delivery_20261005/baseline-'+Date.now();
fs.mkdirSync(out,{recursive:true});fs.writeFileSync(out+'/remote.private.json',JSON.stringify(remote),{flag:'wx'});
const comparison=await compareSnapshots(local,remote,{reconcile:true,output:out+'/comparison'});
const receipt={at:new Date().toISOString(),status:'passed',migrations:428,comparison,sanity:remote.sanity,productionWrites:0,applyAuthority:false};
fs.writeFileSync(out+'/receipt.json',JSON.stringify(receipt,null,2),{flag:'wx'});
fs.writeFileSync('C:/grookai_vault_operator_artifacts/receipt_delivery_20261005/BASELINE_428.json',JSON.stringify({...receipt,out},null,2));
console.log(JSON.stringify({...receipt,out}));
