// Read-only baseline diagnosis. Never authorizes production mutation or changes apply gates.
// No SQL generated by Migration is ever executed.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import pg from 'pg';
import dotenv from 'dotenv';
import { createRequire } from 'node:module';
import { pgSslConfig } from '../audits/japanese_master_index_v4/read_only_guard_v1.mjs';
import { assertPokemonSealedDatabaseTargetV1 } from '../../backend/pricing/pokemon_sealed_maintenance_v1.mjs';
import { RECONCILIATION_MIGRATIONS, sha256, reconcileKnownTableColumnOrderV1 } from './column_order_reconciliation_v1.mjs';

const root = fileURLToPath(new URL('../../', import.meta.url));
const args = Object.fromEntries(process.argv.slice(2).map(arg => {
  assert.match(arg, /^--[a-z-]+=.+$/);
  const index = arg.indexOf('=');
  return [arg.slice(2, index), arg.slice(index + 1)];
}));
for (const key of Object.keys(args)) assert.ok(['env-file', 'out-dir', 'expected-pending', 'inspection-deps'].includes(key), `unknown_argument:${key}`);
const dependencyRoot=path.resolve(args['inspection-deps']??root);
const require=createRequire(path.join(dependencyRoot,'package.json'));
const {PostgreSQL}=require('@pgkit/schemainspect');
const {Migration}=require('@pgkit/migra');
assert.ok(args['env-file'] && args['out-dir'] && args['expected-pending'], 'explicit_env_output_and_pending_required');
assert.ok(process.execArgv.includes('--use-system-ca'), 'verified_system_CA_required');
dotenv.config({ path: path.resolve(args['env-file']), quiet: true, override: true });
assertPokemonSealedDatabaseTargetV1(process.env.SUPABASE_URL, process.env.SUPABASE_DB_URL);
const expected = args['expected-pending'].split(',').sort();
assert.equal(new Set(expected).size, expected.length, 'duplicate_expected_pending');
assert.deepEqual(expected,['20260912050000'],'Only the confirmed-cameo pending migration is expected');
assert.equal(sha256((await fs.readFile(path.join(root,'supabase/migrations/20260912050000_confirmed_card_cameo_read_v2.sql'),'utf8')).replaceAll('\r\n','\n')),'5626c20bf8a422d5143a770478cfb2b2621c8fcac851b85363aafd2d7deef5ad','pending_migration_changed');
const container = JSON.parse(execFileSync('docker', ['inspect', 'supabase_db_sealed-ownership-replay-20260907'], { encoding: 'utf8' }))[0];
assert.equal(container.State.Running, true, 'isolated_replay_not_running');
assert.equal(container.NetworkSettings.Ports['5432/tcp'][0].HostPort, '55430', 'isolated_replay_port_mismatch');
const output = path.resolve(args['out-dir']);
await fs.mkdir(output, { recursive: false });
const migrationFiles = (await fs.readdir(path.join(root, 'supabase/migrations'))).filter(name => /^\d+.*\.sql$/.test(name)).sort();
const sourceIds = migrationFiles.map(name => name.match(/^\d+/)[0]);
assert.equal(new Set(sourceIds).size, sourceIds.length, 'duplicate_migration_id');
const sources = {};
for (const name of migrationFiles) sources[name] = sha256(await fs.readFile(path.join(root, 'supabase/migrations', name)));
const toolSources = {};
for (const name of ['scripts/schema/audit_collector_schema_baseline_v1.mjs', 'scripts/schema/column_order_reconciliation_v1.mjs', 'scripts/migration_preflight_strict.ps1', 'package.json', 'package-lock.json']) {
  toolSources[name] = sha256(await fs.readFile(path.join(root, name)));
}
const engineVersions = {};
for (const name of ['migra', 'schemainspect', 'client']) {
  const version = JSON.parse(await fs.readFile(path.join(dependencyRoot, 'node_modules/@pgkit', name, 'package.json'), 'utf8')).version;
  assert.equal(version, '0.6.1', 'inspection_engine_version_mismatch');
  engineVersions[name] = version;
}
for (const binding of Object.values(RECONCILIATION_MIGRATIONS)) {
  const source = await fs.readFile(path.join(root, 'supabase/migrations', binding.file), 'utf8');
  assert.equal(sha256(source.replaceAll('\r\n', '\n')), binding.lf_sha256, 'reconciliation_source_drift');
}
const sha = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' }).trim();
const report = { version: 'COLLECTOR_BASELINE_DIAGNOSIS_V1', started_at: new Date().toISOString(), base_commit: sha, source_hashes: sources, tool_hashes: toolSources, engine_versions: engineVersions, production_writes: 0, local_writes: 0, apply_authorized: false, scope: ['public'], status: 'started' };
await fs.writeFile(path.join(output, 'run_plan.json'), JSON.stringify(report, null, 2), { flag: 'wx' });
const remote = new pg.Client({ connectionString: process.env.SUPABASE_DB_URL, ssl: pgSslConfig(process.env.SUPABASE_DB_URL), connectionTimeoutMillis: 15000, statement_timeout: 30000 });
const local = new pg.Client({ host: '127.0.0.1', port: 55430, database: 'postgres', user: 'postgres', password: 'postgres', connectionTimeoutMillis: 5000, statement_timeout: 30000 });
const adapter = c => ({
  any: async q => (await c.query(q.sql, q.values)).rows,
  oneFirst: async q => Object.values((await c.query(q.sql, q.values)).rows[0])[0],
});
const ledger = async c => (await c.query('select version from supabase_migrations.schema_migrations order by version')).rows.map(row => row.version);
async function inspector(c) {
  const result = await PostgreSQL.create(adapter(c));
  result.one_schema('public');
  for (const field of ['types', 'domains', 'materialized_views', 'composite_types']) {
    result[field] = Object.fromEntries(Object.entries(result[field]).filter(([, value]) => value.schema === 'public'));
  }
  return result;
}
async function diff(a, b) {
  const migration = await Migration.create(a, b, { schema: 'public' });
  migration.set_safety(false); // Permit generating diagnostic SQL; never apply it.
  migration.add_all_changes(true);
  return migration.sql;
}
// The upstream diff does not cover every owner/ACL/forced-RLS attribute. Check
// these separately, treating ACL entries as a set without changing SQL text.
const securitySql = `
select 'relation' kind,c.relname::text name,pg_get_userbyid(c.relowner) owner,
  to_jsonb(array(select x::text from unnest(c.relacl) x order by x::text)) acl,
  jsonb_build_object('rowsecurity',c.relrowsecurity,'forcerowsecurity',c.relforcerowsecurity,
    'options',c.reloptions,'columns',(select jsonb_agg(jsonb_build_object('name',a.attname,
      'acl',array(select x::text from unnest(a.attacl) x order by x::text)) order by a.attname)
      from pg_attribute a where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped)) attributes
from pg_class c join pg_namespace n on n.oid=c.relnamespace
where n.nspname='public' and c.relkind in ('r','p','v','m','S','f')
union all
select 'function',p.proname||'('||pg_get_function_identity_arguments(p.oid)||')',pg_get_userbyid(p.proowner),
  to_jsonb(array(select x::text from unnest(p.proacl) x order by x::text)),
  jsonb_build_object('security_definer',p.prosecdef,'config',p.proconfig,'leakproof',p.proleakproof)
from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'
order by kind,name`;
try {
  await remote.connect();
  await local.connect();
  for (const c of [remote, local]) {
    await c.query('begin isolation level repeatable read read only');
    assert.equal((await c.query('show transaction_read_only')).rows[0].transaction_read_only, 'on');
  }
  report.sanity = (await remote.query('select (select count(*) from public.card_prints)::int cards,(select count(*) from public.sets)::int sets,(select count(*) from public.card_print_traits)::int traits')).rows[0];
  assert.ok(report.sanity.cards >= 40000 && report.sanity.sets >= 150 && report.sanity.traits >= 5000, 'environment_maturity_mismatch');
  const productionLedger = await ledger(remote);
  const replayLedger = await ledger(local);
  assert.deepEqual(replayLedger, productionLedger, 'baseline_replay_ledger_mismatch');
  report.baseline_migrations_checked=productionLedger.length;
  assert.ok(productionLedger.every(id => sourceIds.includes(id)), 'remote_only_migration');
  report.pending_ids = sourceIds.filter(id => !productionLedger.includes(id));
  assert.deepEqual(report.pending_ids, expected, 'pending_set_mismatch');
  const production = await inspector(remote);
  const replay = await inspector(local);
  const rawSql = await diff(replay, production);
  await fs.writeFile(path.join(output, 'raw_diagnostic_diff.sql'), rawSql, { flag: 'wx' });
  report.raw_diff_sha256 = sha256(rawSql);
  report.raw_diff_bytes=Buffer.byteLength(rawSql);
  report.raw_view_replacements=[...rawSql.matchAll(/create or replace view "public"\."([^"]+)"/g)].map(m=>m[1]);
  report.column_order_changes = reconcileKnownTableColumnOrderV1(replay, production);
  const normalizedSql = await diff(replay, production);
  report.reconciled_diff_bytes=Buffer.byteLength(normalizedSql);
  await fs.writeFile(path.join(output, 'reconciled_diagnostic_diff.sql'), normalizedSql, { flag: 'wx' });
  const securityProduction = (await remote.query(securitySql)).rows;
  const securityReplay = (await local.query(securitySql)).rows;
  await fs.writeFile(path.join(output, 'security_comparison.json'), JSON.stringify({ production: securityProduction, replay: securityReplay }, null, 2), { flag: 'wx' });
  const securityByName=new Map(securityProduction.map(r=>[r.kind+':'+r.name,r]));
  report.security_differences=securityReplay.filter(r=>JSON.stringify(r)!==JSON.stringify(securityByName.get(r.kind+':'+r.name))).map(r=>r.kind+':'+r.name);
  assert.deepEqual(securityReplay, securityProduction, 'owner_acl_or_rls_drift');
  report.security_objects_checked = securityProduction.length;
  assert.equal(normalizedSql.trim(),'','unexpected_baseline_schema_delta');
  report.classification={status:'baseline_matches_after_exact_column_order_comparison',apply_authorized:false};
  for (const name of migrationFiles) assert.equal(sha256(await fs.readFile(path.join(root, 'supabase/migrations', name))), sources[name], 'source_changed_during_audit');
  assert.deepEqual((await fs.readdir(path.join(root, 'supabase/migrations'))).filter(name => /^\d+.*\.sql$/.test(name)).sort(), migrationFiles, 'migration_set_changed_during_audit');
  for (const [name, hash] of Object.entries(toolSources)) assert.equal(sha256(await fs.readFile(path.join(root, name))), hash, 'tool_changed_during_audit');
  report.status = report.classification.status;
} catch (error) {
  report.status = 'failed';
  report.failure = error.code === 'ERR_ASSERTION' ? error.message.split('\n')[0] : `audit_error:${error.code ?? error.name}`;
  process.exitCode = 1;
} finally {
  await remote.query('rollback').catch(() => {});
  await local.query('rollback').catch(() => {});
  await remote.end();
  await local.end();
  report.finished_at = new Date().toISOString();
  await fs.writeFile(path.join(output, 'summary.json'), JSON.stringify(report, null, 2), { flag: 'wx' });
  const hashes = {};
  for (const name of (await fs.readdir(output)).sort()) hashes[name] = sha256(await fs.readFile(path.join(output, name)));
  await fs.writeFile(path.join(output, 'artifact_hashes.json'), JSON.stringify(hashes, null, 2), { flag: 'wx' });
  console.log(JSON.stringify({ status: report.status, failure: report.failure, pending_ids: report.pending_ids, security_objects_checked: report.security_objects_checked, production_writes: 0, artifact_dir: output }));
}
