// Read-only verification of the fixed populated422 lab after Desktop recovery.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {snapshotSql,compareSnapshots} from './vendor_billing_schema_v1.mjs';
const base='C:/grookai_vault_operator_artifacts/jungle_edition_pricing_20261001';
const project='jungle-edition-upgrade-421-v23-20261001',container='supabase_db_'+project;
assert.equal(process.argv.length,2);
assert.equal(fs.realpathSync('.').replaceAll('\\','/').toLowerCase(),'c:/gv_jungle_edition_20261001');
const docker=(...args)=>execFileSync('docker',args,{encoding:'utf8',windowsHide:true,timeout:20000,maxBuffer:2*1024*1024});
const db=JSON.parse(docker('inspect',container))[0];
assert.equal(db.State.Running,true);assert.equal(db.Config.Image,'public.ecr.aws/supabase/postgres:17.6.1.113');
assert.deepEqual(Object.keys(db.NetworkSettings.Networks),[project]);
assert.equal(JSON.parse(docker('network','inspect',project))[0].Internal,true);
const sql=q=>execFileSync('docker',['exec','-i',container,'psql','-U','postgres','-d','postgres','-X','-qAt','-v','ON_ERROR_STOP=1'],{input:q,encoding:'utf8',windowsHide:true,timeout:180000,maxBuffer:64*1024*1024}).trim();
const readonly=q=>'begin isolation level repeatable read read only; set local statement_timeout=\'90s\'; '+q+'; rollback;';
const state=JSON.parse(sql(readonly("select json_build_object('migrations',(select count(*) from supabase_migrations.schema_migrations),'copies',(select count(*) from vault_item_instances),'workers',current_setting('max_worker_processes'),'receipts',(select count(*) from jungle_slab_intake_receipts_v1))")));
assert.deepEqual(state,{migrations:422,copies:2,workers:'0',receipts:0});
const expected=JSON.parse(fs.readFileSync(base+'/retained-slab-upgrade-v1/after-footprints.json'));
assert.equal(expected.length,329);
for(const row of expected)assert.match(row.table_name,/^[a-z_][a-z0-9_]*$/);
const query=expected.map(({table_name:n})=>`select '${n}' table_name,count(*)::int rows,md5(coalesce(string_agg(md5(to_jsonb(t)::text),'' order by md5(to_jsonb(t)::text)),'')) digest from public."${n}" t`).join(' union all ');
const actual=JSON.parse(sql(readonly('select json_agg(f order by table_name) from ('+query+') f')));
assert.deepEqual(actual,expected);
const snapshot=JSON.parse(sql(snapshotSql));
const previous=JSON.parse(fs.readFileSync(base+'/retained-slab-upgrade-v1/after-schema.private.json'));
assert.deepEqual(snapshot.LEDGER,previous.LEDGER);
const out=base+'/retained-runtime-v26';assert.ok(!fs.existsSync(out),'Preserve previous evidence');fs.mkdirSync(out);
fs.writeFileSync(out+'/schema.private.json',JSON.stringify(snapshot),{flag:'wx'});
fs.writeFileSync(out+'/footprints.json',JSON.stringify(actual),{flag:'wx'});
const comparison=await compareSnapshots(snapshot,previous,{output:out+'/comparison'});
const receipt={at:new Date().toISOString(),status:'passed',project,containerId:db.Id,state,protectedPublicTables:329,allExistingRowsUnchanged:true,comparison,readOnly:true,productionWrites:0,localDatabaseWrites:0};
fs.writeFileSync(out+'/receipt.json',JSON.stringify(receipt,null,2),{flag:'wx'});
console.log(JSON.stringify(receipt));
