// Real local Auth/HTTP and immutable-ledger preservation. Never targets production.
import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync,spawnSync} from 'node:child_process';import {createHash,randomUUID} from 'node:crypto';import {fileURLToPath} from 'node:url';import pg from 'pg';import {createClient} from '@supabase/supabase-js';
import {seedMappingPriceFixture,mappingPriceFixture} from '../../tests/fixtures/mapping_price_quarantine_v1.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url)),out='C:/grookai_vault_operator_artifacts/gamestop_duraludon_20261001',fixture=out+'/full-413-v1',project='mapping-pricing-full-413-v1-20261001';
assert.equal(process.argv.length,2);assert.equal(fs.realpathSync(root).replaceAll('\\','/').toLowerCase(),'c:/gv_gamestop_zoroark_20261001');
const read=p=>JSON.parse(fs.readFileSync(p)),save=(p,v)=>fs.writeFileSync(out+'/'+p,JSON.stringify(v,null,2)+'\n',{flag:'wx'});
assert.equal(read(fixture+'/replay-result.json').status,'passed');assert.equal(read(fixture+'/freeze.json').project,project);assert.ok(!fs.existsSync(fixture+'/supabase/.temp/project-ref'));assert.ok(!fs.existsSync(out+'/runtime-v4-intent.json'));
const docker=JSON.parse(execFileSync('docker',['inspect','supabase_db_'+project],{encoding:'utf8'}))[0];assert.equal(docker.State.Running,true);assert.deepEqual(Object.keys(docker.NetworkSettings.Networks),[project]);assert.equal(JSON.parse(execFileSync('docker',['network','inspect',project],{encoding:'utf8'}))[0].Internal,true);
const status=JSON.parse(execFileSync('supabase',['status','--workdir',fixture,'--output','json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));const url=new URL(status.DB_URL);assert.equal(url.hostname,'127.0.0.1');assert.equal(url.port,'64040');
const db=new pg.Client({connectionString:url.toString()});await db.connect();const report={at:new Date().toISOString(),project,productionWrites:0,checks:[]};
try{
 // V1 seeded successfully, then the worker's clean-source gate stopped it before
 // database access. Preserve that fixture/failed receipt; do not seed or reset it.
 assert.equal(read(out+'/runtime-result.json').status,'failed');assert.match(fs.readFileSync(out+'/runtime-shadow.private.log','utf8'),/clean tracked working tree/);
 assert.equal((await db.query('select count(*)::int n from market_price_pipeline_runs')).rows[0].n,1);assert.equal((await db.query('select state from market_price_pipeline_runs')).rows[0].state,'failed');assert.equal((await db.query('select count(*)::int n from card_prints')).rows[0].n,1);
 const f=read(out+'/runtime-intent.json').fixture;save('runtime-v4-intent.json',{at:report.at,project,fixture:f,consumed:true,synthetic:true,retains_seed:'runtime-intent.json'});
 const workerRoot='C:/gv_duraludon_runtime_worker_20261001';assert.equal(execFileSync('git',['status','--porcelain','--untracked-files=no'],{cwd:workerRoot,encoding:'utf8'}).trim(),'');execFileSync('git',['diff','--exit-code','origin/main','--','backend/pricing','backend/env.mjs','scripts/workers/tcgplayer_market_publication_worker_v1.mjs'],{cwd:root,stdio:'pipe'});report.workerProducer=execFileSync('git',['rev-parse','HEAD'],{cwd:workerRoot,encoding:'utf8'}).trim();
 assert.equal(read(out+'/runtime-result-v2.json').status,'failed');assert.match(fs.readFileSync(out+'/runtime-v2-shadow.private.log','utf8'),/publication scope evidence missing/);
 assert.equal(read(out+'/runtime-result-v3.json').status,'failed');assert.match(read(out+'/runtime-result-v3.json').error,/tcgcsv_source_groups_category_id_fkey/);
 await db.query("insert into tcgcsv_source_categories(category_id,name,raw_payload,payload_hash,last_seen_run_id) values(3,'Pokemon','{}','synthetic-local-category',$1)",[f.sourceRunId]);
 await db.query("insert into tcgcsv_source_groups(group_id,category_id,name,raw_payload,payload_hash,last_seen_run_id) values(1,3,'Base Set','{}','synthetic-local-group',$1)",[f.sourceRunId]);
 const env={...process.env};for(const k of Object.keys(env))if(/SUPABASE|DATABASE_URL|POSTGRES_URL|^PG|TOKEN|SECRET/i.test(k))delete env[k];Object.assign(env,{SUPABASE_DB_URL:url.toString(),DOTENV_CONFIG_PATH:out+'/no-env',DO_NOT_TRACK:'1'});
 const runKey='MAPPING-PRICE-LOCAL-'+randomUUID();const worker=spawnSync(process.execPath,['scripts/workers/tcgplayer_market_publication_worker_v1.mjs','--mode=shadow','--run-key='+runKey,'--out-root='+out+'/local-shadow-v4'],{cwd:workerRoot,env,encoding:'utf8',timeout:180000,maxBuffer:8e6});fs.writeFileSync(out+'/runtime-v4-shadow.private.log',(worker.stdout??'')+(worker.stderr??''),{flag:'wx'});assert.equal(worker.status,0,'Inspect retained local shadow log');
 const run=(await db.query('select * from market_price_pipeline_runs where run_key=$1',[runKey])).rows[0];assert.equal(run.state,'shadow_verified');assert.equal(run.eligible_count,1);
 const set=(await db.query('select * from market_price_publication_sets where run_id=$1',[run.id])).rows[0];
 // Construct a published LOCAL fixture from reconciled shadow evidence. This is
 // reader qualification, not production-worker activation/rollout evidence.
 await db.query("update market_price_pipeline_runs set state='reconciled',run_mode='canary' where id=$1",[run.id]);await db.query('select * from activate_market_price_publication_set_v1($1,$2,1)',[run.id,set.id]);
 const api='http://127.0.0.1:64041',options={auth:{persistSession:false,autoRefreshToken:false}},anon=createClient(api,status.ANON_KEY,options),admin=createClient(api,status.SECRET_KEY,options),member=createClient(api,status.ANON_KEY,options);
 const email=randomUUID()+'@mapping-price-fixture.invalid',password=randomUUID()+'Aa9!';const user=await admin.auth.admin.createUser({email,password,email_confirm:true});assert.ifError(user.error);assert.ifError((await member.auth.signInWithPassword({email,password})).error);
 await db.query("select admin_vault_instance_create_v1(p_user_id=>$1,p_card_print_id=>$2,p_condition_label=>'NM')",[user.data.user.id,f.cardPrintId]);
 const forbidden=await anon.rpc('get_market_pricing_read_model_v1',{p_card_print_ids:[f.cardPrintId]});assert.ok(forbidden.error);report.checks.push('anonymous pricing permission unchanged');
 const sqlRead=async available=>{const p=(await db.query('select * from get_market_pricing_read_model_v1($1,$2)',[[f.cardPrintId],[f.cardPrintingId]])).rows;assert.equal(p.length,2);assert.ok(p.every(r=>r.status===(available?'available':'unavailable')));if(!available)assert.ok(p.every(r=>r.market_close===null));for(const v of ['v_market_price_current_v1','v_market_price_history_v1'])assert.equal((await db.query('select count(*)::int n from '+v+' where card_printing_id=$1',[f.cardPrintingId])).rows[0].n,available?1:0);};
 const httpRead=async available=>{for(const [name,args]of [['get_market_pricing_read_model_v1',{p_card_print_ids:[f.cardPrintId],p_card_printing_ids:[f.cardPrintingId]}],['get_market_price_history_v1',{p_card_printing_id:f.cardPrintingId,p_days:365}],['get_top_market_pricing_v1',{p_limit:100}]]){const r=await member.rpc(name,args);assert.ifError(r.error);if(name==='get_market_pricing_read_model_v1'){assert.equal(r.data.length,2);assert.ok(r.data.every(x=>x.status===(available?'available':'unavailable')));}else assert.equal(r.data.length,available?1:0);}};
 await sqlRead(true);await httpRead(true);report.checks.push('initial exact parent/child/history/ranked price available via real authenticated HTTP');
 const tables=['card_prints','card_printings','market_evidence_variant_assignments','market_price_pipeline_candidates','market_price_qualification_decisions','market_price_publication_snapshots','market_price_publication_sets','market_price_current_publication','vault_item_instances'];const preserve=async()=>Object.fromEntries(await Promise.all(tables.map(async t=>[t,(await db.query('select md5(coalesce(jsonb_agg(to_jsonb(t) order by id)::text,\'null\')) digest from '+t+' t')).rows[0].digest])));
 // The pointer has no id column; preserve its full row separately.
 tables.splice(tables.indexOf('market_price_current_publication'),1);const before=await preserve(),pointer=(await db.query('select * from market_price_current_publication')).rows;
 const mapping=(await db.query("select * from external_mappings where source='tcgplayer' and external_id=$1",[String(f.productId)])).rows[0];const reason='PROVEN_UNSTAMPED_PRODUCT_ON_STAMPED_PARENT';
 await db.query('begin');await db.query('update external_mappings set active=false where id=$1',[mapping.id]);await sqlRead(true);await db.query("update external_mappings set meta=meta||$2::jsonb where id=$1",[mapping.id,JSON.stringify({reviewed_invalidation:{reason_code:'UNRELATED_REASON'}})]);await sqlRead(true);await db.query('rollback');report.checks.push('ordinary inactive and unrelated metadata retain existing pricing behavior');
 await db.query('begin');await db.query('update external_mappings set active=false,meta=meta||$2::jsonb where id=$1',[mapping.id,JSON.stringify({reviewed_invalidation:{reason_code:reason}})]);await sqlRead(false);await db.query('rollback');await sqlRead(true);assert.deepEqual(await preserve(),before);report.checks.push('real invalidation withdrawal rolls back without ledger or copy changes');
 await db.query('begin');await db.query('update external_mappings set active=false,meta=meta||$2::jsonb where id=$1',[mapping.id,JSON.stringify({reviewed_invalidation:{reason_code:reason}})]);await db.query('commit');await sqlRead(false);await httpRead(false);report.checks.push('committed rejection removes current/history/ranked prices without deleting snapshots');
 await db.query('begin');await db.query('update external_mappings set active=true where id=$1',[mapping.id]);await sqlRead(false);await db.query('rollback');report.checks.push('accidental reactivation cannot restore rejected prices');
 assert.deepEqual(await preserve(),before);assert.deepEqual((await db.query('select * from market_price_current_publication')).rows,pointer);report.checks.push('all pricing evidence, card/printing, publication pointer and owned copy preserved');
 report.migrationSha256=createHash('sha256').update(fs.readFileSync(root+'/supabase/migrations/20261001190000_reviewed_mapping_price_quarantine_v1.sql')).digest('hex');report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;throw e;}finally{await db.end();save('runtime-result-v4.json',report);console.log({status:report.status,checks:report.checks});}
