// Exactly one correction of the failed, empty 196xx draft replay. No shared reset.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {root,fixture,project,container,relay,output,addition,hash,hashes,docker,sql,sourceState,guard} from './vendor_orders_runtime_v1.mjs';
assert.equal(process.argv.length,2);
const initial='71943172596a6cdf55239902bb1012a426bfa84a149ca7f17e681f1bb6293c0f',source=sourceState();
assert.equal(Object.keys(source).length,402);assert.notEqual(source[addition],initial);
assert.deepEqual(hashes(path.join(fixture,'supabase/migrations')),{...source,[addition]:initial});
const logFile=path.join(fixture,'full-reset-private.log'),oldLog=fs.readFileSync(logFile);
assert.equal(hash(oldLog),'44d02c210bdbfbcd2a0e6ec87eda676a90ce1ee71fae9d1cde6699e2b7c70282');
assert.match(oldLog.toString(),/unterminated quoted string/);
assert.ok(!fs.existsSync(path.join(output,'replay.json')));
const prep=JSON.parse(fs.readFileSync(path.join(fixture,'preparation.json')));
assert.equal(prep.project,project);assert.equal(prep.databasePort,19622);
const prior={...source};delete prior[addition];assert.deepEqual(prior,prep.sourceHashes);
assert.equal(fs.realpathSync(fixture).replaceAll('\\','/').toLowerCase(),'c:/gv_store_billing_20260919/.local/integration/vendor-orders-replay');
assert.ok(!fs.existsSync(path.join(fixture,'supabase/.temp/project-ref')));
assert.equal(hash(fs.readFileSync(path.join(fixture,'supabase/config.toml'))),prep.configSha256);
const db=JSON.parse(docker('inspect',container))[0];assert.equal(db.State.Running,true);
assert.equal(db.Image,'sha256:4c39816ce8d9303a3aba1161c842929c73a40c7109a9ef1b644582478e31832e');
assert.deepEqual(Object.keys(db.NetworkSettings.Networks),[project]);assert.equal(JSON.parse(docker('network','inspect',project))[0].Internal,true);
assert.deepEqual(JSON.parse(docker('inspect',relay))[0].NetworkSettings.Ports['19622/tcp'],[{HostIp:'127.0.0.1',HostPort:'19622'}]);
assert.deepEqual(sql('select version from supabase_migrations.schema_migrations order by version;').split(/\r?\n/),Object.keys(prior).sort().map(n=>n.split('_')[0]));
assert.equal(sql("select current_setting('max_worker_processes')||'|'||(select count(*) from auth.users)||'|'||(select count(*) from card_prints)||'|'||(select count(*) from sealed_product_variants)||'|'||(select count(*) from cron.job_run_details)||'|'||(select count(*) from vendor_stock_reservations);"),'0|0|0|0|0|0');
assert.equal(sql("select app_enabled::text||'|'||web_enabled::text||'|'||custom_enabled::text from vendor_store_rollout;"),'false|false|false');
assert.equal(sql("select reservations_enabled::text from vendor_stock_rollout;"),'false');
const footprintSql=fs.readFileSync(path.join(root,'scripts/audits/storefront_schema_footprint_v1.sql'),'utf8');
assert.deepEqual(JSON.parse(sql(footprintSql)).objects,JSON.parse(fs.readFileSync(path.join(fixture,'prior-192-footprint.json'))).objects);
const baselineFile=fs.readdirSync(output).filter(n=>/^baseline-.*\.json$/.test(n)).sort().at(-1),baseline=JSON.parse(fs.readFileSync(path.join(output,baselineFile)));
assert.equal(baseline.status,'passed');assert.equal(baseline.comparison.normalizedBytes,0);assert.equal(baseline.applied,396);
assert.ok(Date.now()-Date.parse(baseline.finishedAt)<86400000);
for(const [name,digest] of Object.entries(baseline.toolHashes))assert.equal(hash(fs.readFileSync(path.join(root,name))),digest);
// Preserve the failed bytes/log before replacing the unpublished local draft.
fs.copyFileSync(path.join(fixture,'supabase/migrations',addition),path.join(output,'initial-syntax-migration.sql'),fs.constants.COPYFILE_EXCL);
fs.copyFileSync(logFile,path.join(fixture,'initial-syntax-reset-private.log'),fs.constants.COPYFILE_EXCL);
fs.writeFileSync(path.join(fixture,'supabase/migrations',addition),fs.readFileSync(path.join(root,'supabase/migrations',addition)));
const env={...process.env};for(const key of Object.keys(env))if(/SUPABASE|DATABASE_URL|POSTGRES_URL/.test(key))delete env[key];
const run=spawnSync('supabase',['db','reset','--local','--no-seed','--yes','--workdir',fixture,'--network-id',project],{cwd:fixture,env,encoding:'utf8',windowsHide:true,timeout:600000,maxBuffer:32*1024*1024});
fs.writeFileSync(logFile,(run.stdout??'')+(run.stderr??''));assert.equal(run.status,0,'Inspect retained correction log');
guard({full:true});fs.writeFileSync(path.join(fixture,'full-footprint.json'),sql(footprintSql),{flag:'wx'});
console.log(JSON.stringify({status:'corrected_full_reset',initialMigrationSha256:initial,productionWrites:0,sharedResets:0}));
