// One bounded local replay after recovering the already-applied Foil-scope ledger.
// No production apply, shared reset, arbitrary target or SQL arguments.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {execFileSync,spawnSync} from 'node:child_process';
const root=fileURLToPath(new URL('../../',import.meta.url));
const fixture='C:/gv_store_billing_20260919/.local/integration/billing-replay';
const project='grookai-vendor-billing-20260919';
const container=`supabase_db_${project}`;
const pending='20260919050000_vendor_storefront_release_v1.sql';
const hash=x=>createHash('sha256').update(x).digest('hex');
const hashes=dir=>Object.fromEntries(fs.readdirSync(dir).filter(n=>/^\d+.*\.sql$/.test(n)).sort().map(n=>[n,hash(fs.readFileSync(path.join(dir,n)))]));
const inspect=(...args)=>JSON.parse(execFileSync('docker',args,{encoding:'utf8',windowsHide:true}))[0];
const sql=s=>execFileSync('docker',['exec','-i',container,'psql','-U','postgres','-d','postgres','-X','-qAt','-v','ON_ERROR_STOP=1'],{input:s,encoding:'utf8',windowsHide:true,maxBuffer:32*1024*1024}).trim();
assert.equal(process.argv.length,2);
assert.ok(['c:/gv_store_schema_reconcile_20260919','c:/gv_store_release_20260919'].includes(fs.realpathSync(root).replaceAll('\\','/').toLowerCase()));
assert.equal(fs.realpathSync(fixture).replaceAll('\\','/').toLowerCase(),fixture.toLowerCase());
assert.equal(hash(fs.readFileSync(path.join(fixture,'supabase/config.toml'))),'8624ef18a63b95faf3d9bd910c711436e17894e0318577abd0005dd365094ab8');
assert.ok(!fs.existsSync(path.join(fixture,'supabase/.temp/project-ref')));
const state=inspect('inspect',container);assert.equal(state.State.Running,true);
assert.deepEqual(Object.keys(state.NetworkSettings.Networks),[project]);assert.equal(inspect('network','inspect',project).Internal,true);
assert.deepEqual(inspect('inspect','grookai-vendor-billing-relay-20260919').NetworkSettings.Ports['17222/tcp'],[{HostIp:'127.0.0.1',HostPort:'17222'}]);
const emptySql="select current_setting('max_worker_processes')||'|'||(select count(*) from auth.users)||'|'||(select count(*) from public.card_prints)||'|'||(select count(*) from public.sealed_product_variants)||'|'||(select count(*) from cron.job_run_details);";
assert.equal(sql(emptySql),'0|0|0|0|0');
const baseline=JSON.parse(fs.readFileSync('C:/gv_store_billing_20260919/docs/audits/vendor_stripe_billing_schema_v1/baseline.json'));
assert.equal(baseline.status,'passed');assert.equal(baseline.applied,395);assert.equal(baseline.comparison.normalizedBytes,0);
assert.equal(baseline.comparison.securityObjects,893);assert.deepEqual(baseline.pending,['20260919050000']);
assert.ok(Date.now()-Date.parse(baseline.finishedAt)<86400000);
const source=hashes(path.join(root,'supabase/migrations'));
assert.equal(Object.keys(source).length,396);assert.deepEqual(source,baseline.sourceHashes);
const before={...source};delete before[pending];
assert.deepEqual(hashes(path.join(fixture,'supabase/migrations')),before);
const expectedBefore=Object.keys(before).sort().map(n=>n.match(/^\d+/)[0]);
assert.deepEqual(sql('select version from supabase_migrations.schema_migrations order by version;').split('\n'),expectedBefore);
const output=path.join(root,'docs/audits/vendor_storefront_ledger_reconcile_v1');
fs.mkdirSync(output,{recursive:true});assert.ok(!fs.existsSync(path.join(output,'replay.json')));
fs.copyFileSync(path.join(root,'supabase/migrations',pending),path.join(fixture,'supabase/migrations',pending),fs.constants.COPYFILE_EXCL);
assert.deepEqual(hashes(path.join(fixture,'supabase/migrations')),source);
const env={...process.env};for(const k of Object.keys(env))if(/SUPABASE|DATABASE_URL|POSTGRES_URL/.test(k))delete env[k];
const run=spawnSync('supabase',['db','reset','--workdir',fixture,'--network-id',project,'--local','--no-seed','--yes'],{env,encoding:'utf8',windowsHide:true,timeout:600000,maxBuffer:32*1024*1024});
const log=(run.stdout??'')+(run.stderr??'');fs.writeFileSync(path.join(fixture,'storefront-reconciled-reset.log'),log,{flag:'wx'});
assert.equal(run.status,0,'New local replay failed; retain the log and investigate');
assert.equal(sql(emptySql),'0|0|0|0|0');
assert.deepEqual(sql('select version from supabase_migrations.schema_migrations order by version;').split('\n'),Object.keys(source).sort().map(n=>n.match(/^\d+/)[0]));
assert.equal(sql("select app_enabled::text||'|'||web_enabled::text||'|'||custom_enabled::text from public.vendor_store_rollout;"),'false|false|false');
assert.equal(sql("select meta->'game_scope' from public.finish_keys where key='foil';"),'["mtg", "one_piece"]');
const original=JSON.parse(fs.readFileSync('C:/gv_store_release_20260919/docs/audits/vendor_storefront_release_package_v1/release-schema-footprint.json'));
const footprint=JSON.parse(sql(fs.readFileSync('C:/gv_store_release_20260919/scripts/audits/storefront_schema_footprint_v1.sql','utf8')));
assert.deepEqual(footprint.objects,original.objects,'Unexpected storefront schema/security difference');
const report={at:new Date().toISOString(),status:'passed',project,sourceHashes:source,fullChainResetReplay:true,applied:396,publicSchemaObjectsUnchanged:footprint.objects.length,baselineSource:'395-migration fresh production comparison',resetLogSha256:hash(log),productionWrites:0,sharedResets:0,rolloutEnabled:false,remotePrePushPassed:false};
fs.writeFileSync(path.join(output,'replay.json'),JSON.stringify(report,null,2),{flag:'wx'});
console.log(JSON.stringify({status:'passed',applied:396,publicSchemaObjectsUnchanged:footprint.objects.length,productionWrites:0,sharedResets:0}));
