// One full replay of the new synthetic 248xx project. Never reset an earlier proof DB.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync,spawnSync} from 'node:child_process';
import {root,fixture,project,output,pending,addition,hash,hashes,sql,guard} from './vendor_order_resolutions_runtime_v1.mjs';
assert.ok(process.argv.length===2||(process.argv.length===3&&process.argv[2]==='--verify'));
const verifyOnly=process.argv[2]==='--verify',before=guard({full:verifyOnly});
const files=fs.readdirSync(output).filter(n=>/^baseline-.*\.json$/.test(n)).sort();assert.ok(files.length);
const baselineFile=files.at(-1),baseline=JSON.parse(fs.readFileSync(path.join(output,baselineFile)));
assert.equal(baseline.status,'passed');assert.equal(baseline.applied,400);
assert.equal(baseline.comparison.normalizedBytes,0);const original={...before.sourceHashes};delete original[addition];assert.deepEqual(original,baseline.sourceHashes);
assert.ok(Date.now()-Date.parse(baseline.finishedAt)<86400000);
for(const [name,digest] of Object.entries(baseline.toolHashes))assert.equal(hash(fs.readFileSync(path.join(root,name))),digest);
assert.match(fs.readFileSync(path.join(fixture,'strict-baseline.log'),'utf8'),/STRICT VENDOR ORDER RESOLUTIONS BASELINE PASS - DEVELOPMENT ONLY/);
assert.ok(!fs.existsSync(path.join(output,'replay.json')),'Replay already proved; preserve it');
const intent=path.join(fixture,'full-replay-intent.json'),logFile=path.join(fixture,'full-reset-private.log');
assert.equal(fs.existsSync(intent),verifyOnly,'Never repeat a consumed reset; inspect its retained state');
assert.equal(fs.existsSync(logFile),verifyOnly);
const footprintSql=fs.readFileSync(path.join(root,'scripts/audits/storefront_schema_footprint_v1.sql'),'utf8');
const priorContainer='supabase_db_grookai-notifications-20260922';
const priorState=JSON.parse(execFileSync('docker',['inspect',priorContainer],{encoding:'utf8',windowsHide:true}))[0];
assert.equal(priorState.State.Running,true);
assert.equal(priorState.Image,'sha256:4c39816ce8d9303a3aba1161c842929c73a40c7109a9ef1b644582478e31832e');
assert.deepEqual(Object.keys(priorState.NetworkSettings.Networks),['grookai-notifications-20260922']);
const old=JSON.parse(execFileSync('docker',['exec','-i',priorContainer,'psql','-U','postgres','-d','postgres','-X','-qAt','-v','ON_ERROR_STOP=1'],{input:footprintSql,encoding:'utf8',windowsHide:true,timeout:180000,maxBuffer:32*1024*1024}));
if(verifyOnly)assert.deepEqual(JSON.parse(fs.readFileSync(path.join(fixture,'prior-412-footprint.json'))).objects,old.objects);
else fs.writeFileSync(path.join(fixture,'prior-412-footprint.json'),JSON.stringify(old),{flag:'wx'});
let log;
if(!verifyOnly){
  fs.writeFileSync(intent,JSON.stringify({at:new Date().toISOString(),project,sourceHashes:before.sourceHashes}),{flag:'wx'});
  for(const name of [...pending,addition])fs.copyFileSync(path.join(root,'supabase/migrations',name),path.join(fixture,'supabase/migrations',name),fs.constants.COPYFILE_EXCL);
  assert.deepEqual(hashes(path.join(fixture,'supabase/migrations')),before.sourceHashes);
  const env={...process.env,DO_NOT_TRACK:'1'};for(const key of Object.keys(env))if(/SUPABASE|DATABASE_URL|POSTGRES_URL/.test(key))delete env[key];
  const run=spawnSync('supabase',['db','reset','--local','--no-seed','--yes','--workdir',fixture,'--network-id',project],{cwd:fixture,env,encoding:'utf8',windowsHide:true,timeout:600000,maxBuffer:32*1024*1024});
  log=(run.stdout??'')+(run.stderr??'');fs.writeFileSync(logFile,log,{flag:'wx'});
  assert.equal(run.status,0,'Inspect retained replay logs; no automatic reset retry');
}else{log=fs.readFileSync(logFile,'utf8');assert.match(log,/Finished supabase db reset/);}
const after=guard({full:true}),current=JSON.parse(sql(footprintSql));
const key=o=>o.kind+'|'+o.key,previous=new Map(old.objects.map(o=>[key(o),o])),next=new Map(current.objects.map(o=>[key(o),o]));
const added=current.objects.filter(o=>!previous.has(key(o))),removed=old.objects.filter(o=>!next.has(key(o))),changed=current.objects.filter(o=>previous.has(key(o))&&JSON.stringify(o)!==JSON.stringify(previous.get(key(o))));
assert.deepEqual(removed,[]);
assert.deepEqual(changed,[],'Existing schema objects must remain exact');
assert.ok(added.length>0);assert.ok(added.every(o=>o.key.includes('vendor_order_resolution')),'Unrelated schema addition');
const untouched=old.objects.filter(o=>!removed.some(r=>key(r)===key(o))&&!changed.some(c=>key(c)===key(o)));
assert.deepEqual(current.objects.filter(o=>untouched.some(p=>key(p)===key(o))),untouched);
const migration=fs.readFileSync(path.join(root,'supabase/migrations',addition),'utf8');
sql('begin;\n'+migration.replace(/^begin;$/m,'').replace(/^commit;$/m,'')+'\nrollback;');
assert.deepEqual(JSON.parse(sql(footprintSql)).objects,current.objects);
const report={idempotentRollback:true,at:new Date().toISOString(),status:'passed',...after,baselineFile,fullChainResetReplay:true,unchangedObjects:untouched.length,changedObjects:changed,addedObjects:added,removedObjects:removed,resetLogSha256:hash(log),productionWrites:0,sharedResets:0,providerRequests:0,rolloutEnabled:false};
fs.writeFileSync(path.join(fixture,'full-footprint.json'),JSON.stringify(current),{flag:'wx'});
fs.writeFileSync(path.join(output,'replay.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({status:'passed',applied:after.applied,unchangedObjects:untouched.length,changed:changed.length,added:added.length,removed:removed.length,productionWrites:0}));
