// One full local reset of the new empty 180xx project, after its strict baseline.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync,spawnSync} from 'node:child_process';
import {root,fixture,project,output,pending,hash,hashes,sql,guard} from './store_index_reconcile_v1.mjs';
import {guardRuntime} from 'file:///C:/gv_store_billing_20260919/scripts/tests/vendor_billing_runtime_v1.mjs';
assert.equal(process.argv.length,2);
const before=guard();guardRuntime();
const baselines=fs.readdirSync(output).filter(n=>/^baseline-.*\.json$/.test(n)).sort();
assert.ok(baselines.length);
const baselineFile=baselines.at(-1),baseline=JSON.parse(fs.readFileSync(path.join(output,baselineFile)));
assert.equal(baseline.status,'passed');assert.equal(baseline.applied,396);
assert.equal(baseline.comparison.normalizedBytes,0);assert.equal(baseline.comparison.securityObjects,893);
assert.deepEqual(baseline.sourceHashes,before.sourceHashes);
assert.ok(Date.now()-Date.parse(baseline.finishedAt)<86400000);
for(const [name,digest] of Object.entries(baseline.toolHashes))assert.equal(hash(fs.readFileSync(path.join(root,name))),digest);
assert.match(fs.readFileSync(path.join(fixture,'strict-baseline.log'),'utf8'),/STRICT INDEX BASELINE PASS - DEVELOPMENT ONLY/);
assert.ok(!fs.existsSync(path.join(output,'replay.json')));
assert.ok(!fs.existsSync(path.join(fixture,'full-reset-private.log')));
const footprintSql=fs.readFileSync(path.join(root,'scripts/audits/storefront_schema_footprint_v1.sql'),'utf8');
const old=JSON.parse(execFileSync('docker',['exec','-i','supabase_db_grookai-vendor-billing-runtime-20260919','psql','-U','postgres','-d','postgres','-X','-qAt','-v','ON_ERROR_STOP=1'],{input:footprintSql,encoding:'utf8',windowsHide:true,timeout:60000,maxBuffer:32*1024*1024}));
fs.writeFileSync(path.join(fixture,'prior-176-footprint.json'),JSON.stringify(old),{flag:'wx'});
for(const name of pending)fs.copyFileSync(path.join(root,'supabase/migrations',name),path.join(fixture,'supabase/migrations',name),fs.constants.COPYFILE_EXCL);
assert.deepEqual(hashes(path.join(fixture,'supabase/migrations')),before.sourceHashes);
const env={...process.env};for(const key of Object.keys(env))if(/SUPABASE|DATABASE_URL|POSTGRES_URL/.test(key))delete env[key];
const run=spawnSync('supabase',['db','reset','--local','--no-seed','--yes','--workdir',fixture,'--network-id',project],{cwd:fixture,env,encoding:'utf8',windowsHide:true,timeout:600000,maxBuffer:32*1024*1024});
const log=(run.stdout??'')+(run.stderr??'');
fs.writeFileSync(path.join(fixture,'full-reset-private.log'),log,{flag:'wx'});
assert.equal(run.status,0,'Replay failed; preserve logs and investigate before retry');
const after=guard({full:true});guardRuntime();
assert.equal(sql("select app_enabled::text||'|'||web_enabled::text||'|'||custom_enabled::text from public.vendor_store_rollout;"),'false|false|false');
const current=JSON.parse(sql(footprintSql));
fs.writeFileSync(path.join(fixture,'full-footprint.json'),JSON.stringify(current),{flag:'wx'});
const priorKeys=new Set(old.objects.map(o=>`${o.kind}|${o.key}`));
const added=current.objects.filter(o=>!priorKeys.has(`${o.kind}|${o.key}`));
assert.equal(added.length,1);assert.equal(added[0].kind,'index');assert.equal(added[0].key,'public.market_price_pipeline_candidates.market_price_pipeline_candidates_card_print_id_idx');
assert.deepEqual(current.objects.filter(o=>priorKeys.has(`${o.kind}|${o.key}`)),old.objects,'Previously verified source or permissions changed');
const report={at:new Date().toISOString(),status:'passed',...after,baselineFile,fullChainResetReplay:true,unchangedObjects:old.objects.length,addedObjects:added,resetLogSha256:hash(log),productionWrites:0,sharedResets:0,providerRequests:0,rolloutEnabled:false,remotePrePushPassed:false};
fs.writeFileSync(path.join(output,'replay.json'),JSON.stringify(report,null,2),{flag:'wx'});
console.log(JSON.stringify({status:'passed',applied:after.applied,unchangedObjects:old.objects.length,addedObjects:added.length,productionWrites:0,sharedResets:0}));
