// Private real-evidence guard exercise. No DB connection or writes.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {assertJungleExecutionRefreshV1 as validate} from '../../backend/catalog/jungle_edition_execution_refresh_v1.mjs';
import {assertJungleReleasePlan,executeJungleRelease} from '../../backend/catalog/jungle_edition_catalog_release_v2.mjs';
import {printingManifestHash as hash} from '../../backend/catalog/printing_completeness_gate_v1.mjs';
import {assertJungleEditionMasterV1} from '../../backend/catalog/jungle_edition_master_authority_v1.mjs';
const b='C:/grookai_vault_operator_artifacts/jungle_edition_pricing_20261001',r=b+'/current-source-v29/refresh',read=p=>JSON.parse(fs.readFileSync(p));assert.equal(process.argv.length,2);
const manifest=read('docs/catalog/master_printing_authority_v1/jungle_editions/manifest.json'),ar=b+'/catalog-authority-v2',artifacts=new Map(read(ar+'/artifact-map.portable.json').map(e=>[e.ref,fs.readFileSync(path.resolve(ar,e.path))])),refresh=read(r+'/execution-refresh.json');
const asOf=new Date(Date.parse(refresh.delta.at)+1000).toISOString(),checks=[];const base=validate(manifest,artifacts,refresh,{asOf});assert.equal(base.retainedParents,83);assert.equal(base.retainedChildren,84);checks.push('fresh_reconciliation_preserves_frozen_manifest');
assert.throws(()=>assertJungleEditionMasterV1(manifest,artifacts,{asOf}),/snapshot_stale_or_future/);checks.push('original_validator_still_rejects_expired_snapshot');
for(const [name,change]of [
 ['wrong_project',r=>r.snapshot.project_ref='other'],['wrong_set',r=>r.snapshot.setId='other'],['missing_TLS_proof',r=>r.snapshot.tls_verified=false],['write_capture',r=>r.snapshot.read_only=false],['wrong_schema',r=>r.snapshot.sanity.migrations=415],['low_sanity_count',r=>r.snapshot.sanity.cards=0],['stale_capture',r=>r.snapshot.at=new Date(Date.parse(asOf)-3600001).toISOString()],['future_capture',r=>r.snapshot.at=new Date(Date.parse(asOf)+1000).toISOString()],['stale_delta',r=>r.delta.at=new Date(Date.parse(asOf)-3600001).toISOString()],['collision',r=>r.snapshot.collisions.parents.push({id:manifest.parents[0].id})],['allocation_drift',r=>r.snapshot.allocationSha256='a'.repeat(64)],['parent_rename',r=>r.snapshot.cards[0].name='changed'],['child_reassignment',r=>r.snapshot.printings[0].card_print_id=manifest.parents[0].id],['species_change',r=>r.snapshot.species[0].active=false],['schema_change',r=>r.snapshot.schema.pop()],['missing_dependency',r=>r.snapshot.dependencies.pop()],['duplicate_dependency',r=>r.snapshot.dependencies.push(r.snapshot.dependencies[0])],['FK_definition_change',r=>r.snapshot.dependencies[0].definition+=' changed'],['unreviewed_dependency_change',r=>r.snapshot.dependencies[0].rowsSha256='f'.repeat(64)],['embedded_copy_data_change',r=>{const d=r.snapshot.dependencies.find(d=>d.rows?.length&&d.table_name==='vault_item_instances');assert.ok(d);d.rows[0].notes='changed';}],['changed_historical_row',r=>r.delta.results[0].historicalSha256='e'.repeat(64)],['removed_history',r=>r.delta.removedRows=1],['wrong_added_count',r=>r.delta.results[0].added=127],['missing_table_proof',r=>r.delta.results.pop()],['unverified_run',r=>r.delta.runs[0].state='failed'],['different_source_run',r=>r.delta.runs[0].source_sync_run_id='other'],['unbound_candidate_run',r=>r.delta.results.find(d=>d.table==='market_price_pipeline_candidates').pipelineRunIds=[]],['wrong_source_family',r=>r.delta.results[0].sourceFamilies=['other']],['future_history',r=>r.delta.results[0].maxCreatedAt=new Date(Date.parse(asOf)+10000).toISOString()],['old_manifest_fingerprint',r=>r.manifestFingerprint='c'.repeat(64)]
]){const copy=structuredClone(refresh);change(copy);assert.throws(()=>validate(manifest,artifacts,copy,{asOf}),name);checks.push(name);}
const broken=new Map(artifacts);broken.set('tcgdex:base2-1',Buffer.from('{}'));assert.throws(()=>validate(manifest,broken,refresh,{asOf}));checks.push('original_physical_source_bytes_still_required');

const plan=read(b+'/catalog-release-v2/rehearsal-1790963943338/plan.private.json');plan.target='production';plan.executionRefresh=refresh;plan.asOf=new Date().toISOString();plan.localGameId=refresh.snapshot.cards[0].game_id;
for(const row of plan.rows.card_prints)row.game_id=plan.localGameId;for(const row of plan.expected.card_prints)row.game_id=plan.localGameId;delete plan.fingerprint;plan.fingerprint=hash(plan);
assertJungleReleasePlan(plan,plan.fingerprint,manifest,artifacts);checks.push('production_plan_accepts_fresh_independent_reconciliation');
for(const [name,change]of [['missing_refresh',p=>p.executionRefresh=null],['expired_refresh',p=>p.executionRefresh.snapshot.at=new Date(Date.now()-3600001).toISOString()],['changed_proposed_identity',p=>p.rows.card_prints[0].image_url='https://invalid.invalid/image']]){const x=structuredClone(plan);change(x);delete x.fingerprint;x.fingerprint=hash(x);assert.throws(()=>assertJungleReleasePlan(x,x.fingerprint,manifest,artifacts),name);checks.push('production_plan_rejects_'+name);}
let calls=0;await assert.rejects(executeJungleRelease({client:{connectionParameters:{host:'127.0.0.1',port:65520,database:'postgres',user:'postgres'},query:async()=>{calls++;}},plan,expectedFingerprint:plan.fingerprint,manifest,artifacts,mode:'rollback'}));assert.equal(calls,0);checks.push('production_plan_cannot_use_local_target_before_SQL');

const receipt={at:new Date().toISOString(),status:'passed',checkCount:checks.length,checks,productionWrites:0,deterministicEvidenceAsOf:asOf,validatorSha256:createHash('sha256').update(fs.readFileSync('backend/catalog/jungle_edition_execution_refresh_v1.mjs')).digest('hex')};fs.writeFileSync(r+'/guard-tests-'+Date.now()+'.json',JSON.stringify(receipt,null,2),{flag:'wx'});console.log(JSON.stringify(receipt));
