// Actual anonymous/owner/service HTTP proof in the fixed retained V3 fixture.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {createClient} from '@supabase/supabase-js';
const base='C:/grookai_vault_operator_artifacts/jungle_edition_pricing_20261001';
const fixture=base+'/full-412-v4', project='jungle-edition-full-412-v4-20261001';
assert.equal(process.argv.length,2);
const hash=b=>createHash('sha256').update(b).digest('hex');
const freeze=JSON.parse(fs.readFileSync(fixture+'/freeze.json'));
assert.equal(freeze.project,project);
assert.equal(hash(fs.readFileSync('supabase/migrations/20261001050000_jungle_edition_foundation_v1.sql')),freeze.sourceHashes['20261001050000_jungle_edition_foundation_v1.sql']);
const docker=(...a)=>execFileSync('docker',a,{encoding:'utf8',windowsHide:true,stdio:['pipe','pipe','pipe']});
assert.equal(JSON.parse(docker('network','inspect',project))[0].Internal,true);
const successes=fs.readdirSync(base).filter(n=>n.startsWith('foundation-sql-v4-')&&fs.existsSync(base+'/'+n+'/receipt.json'));
assert.equal(successes.length,1);
const sqlProof=JSON.parse(fs.readFileSync(base+'/'+successes[0]+'/receipt.json'));
assert.equal(sqlProof.status,'passed');assert.equal(sqlProof.sourceSha256,freeze.sourceHashes['20261001050000_jungle_edition_foundation_v1.sql']);
const {ids}=JSON.parse(fs.readFileSync(base+'/'+successes[0]+'/fixture-intent.json'));
const out=base+'/consumer-http-v3';fs.mkdirSync(out);
fs.writeFileSync(out+'/intent.json',JSON.stringify({at:new Date().toISOString(),project,user:ids.user,consumed:true,productionWrites:0},null,2),{flag:'wx'});
const env={...process.env};for(const k of Object.keys(env))if(/SUPABASE|DATABASE_URL|POSTGRES_URL/.test(k))delete env[k];
const config=JSON.parse(execFileSync('supabase',['status','--output','json','--workdir',fixture,'--network-id',project],{encoding:'utf8',windowsHide:true,env,stdio:['ignore','pipe','pipe']}));
assert.equal(config.API_URL,'http://127.0.0.1:62041');
const options={auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}};
const anon=createClient(config.API_URL,config.ANON_KEY,options),admin=createClient(config.API_URL,config.SERVICE_ROLE_KEY,options);
const tests=[];
const rpc='get_jungle_edition_resolution_v1';
const publicResult=await anon.rpc(rpc,{p_card_print_id:ids.legacy});
assert.ifError(publicResult.error);assert.equal(publicResult.data.status,'selection_required');assert.equal(publicResult.data.options.length,2);tests.push('anonymous_exact_choices');
const denied=await anon.from('jungle_edition_identity_links_v1').select('*');assert.ok(denied.error);tests.push('anonymous_internal_table_denied');
const password=randomUUID()+'aA!8';
const email=randomUUID()+'@jungle-http.invalid';
const created=await admin.auth.admin.createUser({email,password,email_confirm:true});assert.ifError(created.error);
assert.ok(created.data.user?.id);assert.notEqual(created.data.user.id,ids.user);
const owner=createClient(config.API_URL,config.ANON_KEY,options);
const login=await owner.auth.signInWithPassword({email,password});assert.ifError(login.error);assert.equal(login.data.user.id,created.data.user.id);
const retained=await admin.from('vault_item_instances').select('id,card_print_id,card_printing_id,legacy_vault_item_id,archived_at').order('id');
assert.ifError(retained.error);assert.equal(retained.data.length,5);assert.ok(retained.data.every(x=>x.card_print_id===ids.legacy));tests.push('service_existing_copy_read');
const privateRows=await owner.from('vault_item_instances').select('id');assert.ifError(privateRows.error);assert.equal(privateRows.data.length,0);tests.push('authenticated_cross_owner_read_denied');
const held=await admin.rpc('vault_add_card_instance_service_v1',{p_actor_user_id:ids.user,p_card_print_id:ids.legacy,p_card_printing_id:ids.legacyChild});
assert.equal(held.error?.message,'JUNGLE_EDITION_REQUIRED');tests.push('actual_service_rpc_typed_rejection');
const after=await admin.from('vault_item_instances').select('id,card_print_id,card_printing_id,legacy_vault_item_id,archived_at').order('id');assert.ifError(after.error);assert.deepEqual(after.data,retained.data);tests.push('rejected_add_preserves_owned_copies');
const explicit=await owner.rpc(rpc,{p_card_print_id:ids.first});assert.ifError(explicit.error);assert.equal(explicit.data.status,'ready');tests.push('authenticated_exact_edition_read');
await owner.auth.signOut();
const receipt={at:new Date().toISOString(),status:'passed',tests,testCount:tests.length,project,sourceSha256:sqlProof.sourceSha256,scriptSha256:hash(fs.readFileSync(new URL(import.meta.url))),productionWrites:0,ownershipWrites:0};
fs.writeFileSync(out+'/receipt.json',JSON.stringify(receipt,null,2),{flag:'wx'});console.log(JSON.stringify(receipt));
