// One-use additive422->423 CLI upgrade of the populated full-source V30 lab.
// Preserves every existing public row and pricing result; no reset or reseed.
import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync,spawnSync} from 'node:child_process';import pg from 'pg';
import {snapshotSql} from './vendor_billing_schema_v1.mjs';import {inspectJungleFullSourceV30} from './inspect_jungle_full_source_v30.mjs';
const base='C:/grookai_vault_operator_artifacts/jungle_edition_pricing_20261001',fixture=base+'/full-422-v30',out=base+'/retained-receipt-upgrade-v31',migration='20261002220000_vendor_receipt_cloud_v1.sql';
const sha=b=>createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p));
assert.equal(process.argv.length,2);assert.equal(fs.realpathSync('.').replaceAll('\\','/').toLowerCase(),'c:/gv_jungle_edition_20261001');assert.ok(!fs.existsSync(out));
const baseline=read(base+'/jungle-receipt-baseline-415-latest.json'),freeze=read(fixture+'/freeze.json');assert.equal(baseline.status,'passed');assert.equal(baseline.migrations,415);assert.equal(baseline.candidateMigrations,423);assert.ok(Date.now()-Date.parse(baseline.at)<21600000);
for(const [n,h]of Object.entries(baseline.sourceHashes))assert.equal(sha(fs.readFileSync('supabase/migrations/'+n)),h,n);
for(const [n,h]of Object.entries(freeze.sourceHashes))assert.equal(sha(fs.readFileSync(fixture+'/supabase/migrations/'+n)),h,n);
assert.equal(sha(fs.readFileSync(fixture+'/supabase/config.toml')),freeze.configSha256);assert.ok(!fs.existsSync(fixture+'/supabase/.temp/project-ref'));assert.ok(!fs.existsSync(fixture+'/supabase/migrations/'+migration));assert.equal(baseline.sourceHashes[migration],'9ad5b30182f9d51678f018c5a2a2cb941796aeb828b6979a1e1775886eec09b2');
const runtime=inspectJungleFullSourceV30(),project=runtime.project,c=new pg.Client({host:'127.0.0.1',port:53400,user:'postgres',password:'postgres',database:'postgres',connectionTimeoutMillis:10000,statement_timeout:180000});await c.connect();fs.mkdirSync(out);const save=(n,v)=>fs.writeFileSync(out+'/'+n,JSON.stringify(v,null,2),{flag:'wx'});
const query=async(q,p)=>(await c.query(q,p)).rows,schema=async()=>(await c.query(snapshotSql)).find(r=>r.rows?.[0]?.receipt).rows[0].receipt;
const env={...process.env,DO_NOT_TRACK:'1'};for(const k of Object.keys(env))if(/SUPABASE|DATABASE_URL|POSTGRES_URL/.test(k))delete env[k];
function push(label){const fd=fs.openSync(out+'/'+label+'.private.log','wx');let r;try{r=spawnSync('supabase',['db','push','--local','--yes','--workdir',fixture,'--network-id',project],{cwd:fixture,env,windowsHide:true,timeout:180000,stdio:['ignore',fd,fd]});}finally{fs.closeSync(fd);}assert.ifError(r.error);assert.equal(r.status,0,label+' failed; retain the consumed intent');}
try{
 const target=(await query("select host(inet_server_addr()) address,current_setting('max_worker_processes') workers,(select count(*)::int from supabase_migrations.schema_migrations) migrations"))[0];assert.deepEqual(target,{address:runtime.address,workers:'0',migrations:422});
 const shadow=read(base+'/full-source-durable-v30/shadow-receipt.json');assert.equal(shadow.status,'passed');assert.equal((await query('select state from market_price_pipeline_runs where id=$1',[shadow.run]))[0].state,'shadow_verified');
 const copies=await query('select to_jsonb(t) value from vault_item_instances t order by id');assert.equal(copies.length,5);assert.equal((await query('select count(*)::int n from market_price_publication_snapshots'))[0].n,164804);assert.equal((await query('select count(*)::int n from market_price_current_publication'))[0].n,0);
 const tables=await query("select c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' order by c.relname");assert.equal(tables.length,330);for(const {relname}of tables)assert.match(relname,/^[a-z_][a-z0-9_]*$/);
 const fp=tables.map(({relname:n})=>`select '${n}' table_name,count(*)::int rows,md5(coalesce(string_agg(md5(to_jsonb(t)::text),'' order by md5(to_jsonb(t)::text)),'')) digest from public."${n}" t`).join(' union all ')+' order by table_name';
 const before=await query(fp);save('before-footprints.json',before);save('before-copies.private.json',copies);save('before-schema.private.json',await schema());save('runtime.json',runtime);
 save('intent.json',{at:new Date().toISOString(),project,from:422,to:423,migration,sha256:baseline.sourceHashes[migration],sourceSha256:sha(fs.readFileSync(new URL(import.meta.url))),consumed:true,reset:false,reseed:false,productionWrites:0});
 fs.copyFileSync('supabase/migrations/'+migration,fixture+'/supabase/migrations/'+migration,fs.constants.COPYFILE_EXCL);push('upgrade');push('push-noop');
 assert.deepEqual((await query('select version from supabase_migrations.schema_migrations order by version')).map(r=>r.version),Object.keys(baseline.sourceHashes).map(n=>n.split('_')[0]).sort());
 const after=await query(fp);assert.deepEqual(after,before);assert.deepEqual(await query('select to_jsonb(t) value from vault_item_instances t order by id'),copies);assert.equal((await query('select enabled from vendor_receipt_cloud_control'))[0].enabled,false);assert.equal((await query('select count(*)::int n from vendor_receipt_books'))[0].n,0);
 save('after-footprints.json',after);save('after-schema.private.json',await schema());const receipt={at:new Date().toISOString(),status:'passed',project,migrations:423,retainedCopies:5,retainedSnapshots:164804,protectedPublicTables:330,allExistingRowsUnchanged:true,cloudEnabled:false,noOpPush:true,resets:0,reseeds:0,productionWrites:0,sourceHashes:baseline.sourceHashes,migrationSha256:baseline.sourceHashes[migration]};save('receipt.json',receipt);console.log(JSON.stringify({status:'passed',retainedCopies:5,retainedSnapshots:164804,migrations:423,out}));
}catch(e){save('failure.json',{at:new Date().toISOString(),message:e.message,stack:e.stack});throw e;}finally{await c.end();}
