// Exact415-to423 read-only release gate. No reset, apply, activation or publication.
import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import pg from 'pg';
import {snapshotSql,compareSnapshots} from './vendor_billing_schema_v1.mjs';
import {inspectJungleFullSourceV30} from './inspect_jungle_full_source_v30.mjs';import {inspectJungleCatalogV32} from './inspect_jungle_catalog_v32.mjs';
const root='C:/gv_jungle_edition_20261001',base='C:/grookai_vault_operator_artifacts/jungle_edition_pricing_20261001',read=p=>JSON.parse(fs.readFileSync(p)),sha=b=>createHash('sha256').update(b).digest('hex'),git=(...a)=>execFileSync('git',a,{encoding:'utf8',windowsHide:true}).trim();
assert.equal(process.argv.length,3);const phase=process.argv[2];assert.ok(['AuditLinkedSchema','PrePush'].includes(phase));assert.equal(fs.realpathSync('.').replaceAll('\\','/').toLowerCase(),root.toLowerCase());
const sources=Object.fromEntries(fs.readdirSync('supabase/migrations').filter(n=>n.endsWith('.sql')).sort().map(n=>[n,sha(fs.readFileSync('supabase/migrations/'+n))]));assert.equal(Object.keys(sources).length,423);assert.equal(new Set(Object.keys(sources).map(n=>n.split('_')[0])).size,423);
const replay=read(base+'/full-423-v31/replay-result.json'),freeze=read(base+'/full-423-v31/freeze.json'),upgrade=read(base+'/retained-receipt-upgrade-v31/receipt.json');assert.deepEqual(sources,freeze.sourceHashes);assert.deepEqual(sources,upgrade.sourceHashes);assert.equal(replay.status,'passed');assert.ok(replay.fullReplay&&replay.noOpPush);assert.equal(replay.migrations,423);assert.equal(upgrade.status,'passed');assert.equal(upgrade.allExistingRowsUnchanged,true);assert.equal(upgrade.resets,0);assert.equal(upgrade.reseeds,0);
if(phase==='PrePush'){
 assert.equal(git('status','--porcelain'),'','Clean committed source required');git('merge-base','--is-ancestor','origin/main','HEAD');
 const hook=read(base+'/release-checks-v32/normal-hook-latest.json');assert.equal(hook.status,'passed');assert.equal(hook.normalHooks,true);assert.equal(hook.finalHead,git('rev-parse','HEAD'));assert.equal(hook.stagedTree,git('rev-parse','HEAD^{tree}'));assert.equal(hook.exitCode,0);assert.ok(Date.now()-Date.parse(hook.at)<2*3600000);assert.equal(sha(fs.readFileSync(hook.out+'/checks.private.log')),hook.logSha256);
 const qualification=read(base+'/catalog-release-v3/qualification-v32.json');assert.equal(qualification.status,'passed');for(const [p,h]of Object.entries(qualification.sourceHashes))assert.equal(sha(fs.readFileSync(p)),h,p);for(const p of qualification.proofs)assert.equal(sha(fs.readFileSync(base+'/'+p.path)),p.sha256,p.path);
 assert.equal(qualification.rollbackChecks,24);assert.equal(qualification.refreshChecks,42);assert.equal(qualification.actualConcurrentCommit,true);assert.equal(qualification.receiptBookPreserved,true);
 const prior=read(base+'/implementation-source-v30.json');for(const p of ['scripts/workers/tcgplayer_market_publication_worker_v1.mjs','backend/pricing/tcgplayer_market_publication_policy_v1.mjs'])assert.equal(sha(fs.readFileSync(p)),prior.files.find(f=>f.path===p).sha256,p);
}
// The fixed baseline rechecks all415 applied bodies and eight unchanged pending bodies.
execFileSync(process.execPath,['--use-system-ca','scripts/schema/audit_jungle_edition_baseline_v10.mjs'],{encoding:'utf8',windowsHide:true,timeout:180000});
const baseline=read(base+'/jungle-receipt-baseline-415-latest.json');assert.equal(baseline.status,'passed');assert.equal(baseline.migrations,415);assert.equal(baseline.candidateMigrations,423);assert.equal(baseline.pending.length,8);assert.deepEqual(baseline.sourceHashes,sources);
const out=base+'/release-gate-v32-'+phase+'-'+Date.now();fs.mkdirSync(out);const save=(n,v)=>fs.writeFileSync(out+'/'+n,JSON.stringify(v,null,2),{flag:'wx'});
if(phase==='PrePush')for(const [port,inspect]of [[53400,inspectJungleFullSourceV30],[53600,inspectJungleCatalogV32]]){
 const runtime=inspect(),c=new pg.Client({host:'127.0.0.1',port,user:'postgres',password:'postgres',database:'postgres',options:'-c default_transaction_read_only=on',connectionTimeoutMillis:5000});await c.connect();
 try{assert.equal((await c.query('select host(inet_server_addr()) a')).rows[0].a,runtime.address);assert.equal((await c.query('show max_worker_processes')).rows[0].max_worker_processes,'0');assert.equal((await c.query('select count(*)::int n from vault_item_instances')).rows[0].n,5);assert.equal((await c.query('select count(*)::int n from market_price_current_publication')).rows[0].n,0);assert.equal((await c.query('select enabled from vendor_receipt_cloud_control')).rows[0].enabled,false);
 const raw=await c.query(snapshotSql),current=raw.find(r=>r.rows?.[0]?.receipt)?.rows[0].receipt;assert.ok(current);assert.deepEqual(current.LEDGER,Object.keys(sources).map(n=>({version:n.split('_')[0]})));save(port+'-schema.private.json',current);await compareSnapshots(current,read(base+'/full-423-v31/replayed.private.json'),{output:out+'/'+port});
 if(port===53400)assert.equal((await c.query('select count(*)::int n from market_price_publication_snapshots')).rows[0].n,164804);
 else{const {executeJungleRelease}=await import('../../backend/catalog/jungle_edition_catalog_release_v3.mjs');const path=await import('node:path');const ar=base+'/catalog-authority-v2',manifest=read('docs/catalog/master_printing_authority_v1/jungle_editions/manifest.json'),artifacts=new Map(read(ar+'/artifact-map.portable.json').map(r=>[r.ref,fs.readFileSync(path.resolve(ar,r.path))]));const plan=read(base+'/catalog-release-v3/durable-v32/catalog-plan.private.json');const readback=await executeJungleRelease({client:c,manifest,artifacts,plan,expectedFingerprint:plan.fingerprint,mode:'readback'});assert.equal(readback.after,'exact');save('catalog-readback.json',readback);assert.deepEqual((await c.query('select to_jsonb(t) value from vendor_receipt_books t order by owner_id')).rows,read(base+'/catalog-release-v3/seed-v32/books.private.json'));}
 }finally{await c.end();}
}
const toolPaths=['scripts/migration_preflight_strict.ps1','scripts/schema/verify_jungle_release_v32.mjs','scripts/release/prepare_jungle_cli_v32.mjs'];
const result={at:new Date().toISOString(),status:'passed',phase,target:'ycdxbpibncqcchqiihfz',migrations:415,candidateMigrations:423,sourceHashes:sources,pending:baseline.pending.map(n=>n.split('_')[0]),sourceTree:git('write-tree'),commit:git('rev-parse','HEAD'),toolHashes:Object.fromEntries(toolPaths.map(p=>[p,sha(fs.readFileSync(p))])),baseline:baseline.output,baselineReceiptSha256:sha(fs.readFileSync(baseline.output+'/receipt.json')),productionWrites:0,applyAuthority:false,out};save('receipt.json',result);fs.writeFileSync(base+'/Release-v32-'+phase+'.json',JSON.stringify(result,null,2));console.log(JSON.stringify({status:'passed',phase,migrations:415,candidateMigrations:423,pending:8,productionWrites:0,out}));
