import fs from 'node:fs';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import path from 'node:path';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'test/fixtures/collectr_fca_names_v1.json')));
assert.equal(manifest.version,1);
assert.equal(manifest.setCode,'fca');
assert.deepEqual(manifest.rows.map(r=>r.number),Array.from({length:64},(_,i)=>String(i+1)));
for(const row of manifest.rows)for(const key of ['alternateName','canonicalName'])assert.ok(typeof row[key]==='string'&&row[key].trim()===row[key]&&row[key].length>0);
const header='// Generated by scripts/generate_collectr_fca_names_v1.mjs; do not edit.\n// Public publisher checklist, page 2: '+manifest.sourceUrl+'\n';
const ts=header+'export const collectrFcaNames: Readonly<Record<string, readonly [string, string]>> = {\n'+manifest.rows.map(r=>'  '+JSON.stringify(r.number)+': ['+JSON.stringify(r.alternateName)+', '+JSON.stringify(r.canonicalName)+'],').join('\n')+'\n};\n';
const dart=header+'const collectrFcaNames = <String, List<String>>{\n'+manifest.rows.map(r=>'  '+JSON.stringify(r.number)+': ['+JSON.stringify(r.alternateName)+', '+JSON.stringify(r.canonicalName)+'],').join('\n')+'\n};\n';
for(const [name,content]of [['supabase/functions/vault-import-collection-v2/fca_names.ts',ts],['lib/services/import/collectr_fca_names.dart',dart]]){
 const target=path.join(root,name);
 if(process.argv.includes('--check'))assert.equal(fs.readFileSync(target,'utf8').replaceAll('\r\n','\n'),content,name+' is stale');
 else fs.writeFileSync(target,content);
}
