param(
  [switch]$Force
)

$ErrorActionPreference = 'Stop'

function Ensure-Dir {
  param([string]$p)
  if (-not (Test-Path $p)) { New-Item -ItemType Directory -Force -Path $p | Out-Null }
}

$repoRoot = (Get-Location).Path
$gitHooks = Join-Path $repoRoot '.git/hooks'
Ensure-Dir $gitHooks

$hookPath = Join-Path $gitHooks 'pre-commit'

# Compose a bash hook that calls the PowerShell task summary, with rg fallback
$lines = @(
  '#!/usr/bin/env bash',
  '# Auto-generated by tools/install_hooks.ps1',
  'set -euo pipefail',
  '',
  '# Prefer PowerShell task summary (non-blocking)',
  'if command -v pwsh >/dev/null 2>&1; then',
  '  pwsh -NoProfile -ExecutionPolicy Bypass -File "tools/hooks/pre-commit-task-summary.ps1" || true',
  'elif command -v powershell >/dev/null 2>&1; then',
  '  powershell -NoProfile -ExecutionPolicy Bypass -File "tools/hooks/pre-commit-task-summary.ps1" || true',
  'else',
  '  # Fallback: rg over staged files',
  '  if command -v rg >/dev/null 2>&1; then',
  '    echo "[pre-commit] Task markers (staged):"',
  '    files=$(git diff --cached --name-only)',
  '    if [ -n "$files" ]; then',
  '      rg -n -S "(?i)\b(TODO|FIXME|HACK|TASK|NOTE)\b" -- $files || true',
  '    fi',
  '  fi',
  'fi',
  '',
  'exit 0'
)

[System.IO.File]::WriteAllLines($hookPath, $lines)

try { bash -lc "chmod +x '$hookPath'" } catch {}

Write-Host "Installed pre-commit hook at $hookPath" -ForegroundColor Green
Write-Host "It will print a TODO/FIXME/TASK summary for staged files." -ForegroundColor DarkGray
Write-Host "Re-run: powershell -NoProfile -ExecutionPolicy Bypass -File tools/install_hooks.ps1" -ForegroundColor DarkGray

