-- Grookai Vault Baseline - Post RLS Enable
-- Extracted so tables exist before enabling RLS.

ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.card_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.card_price_ticks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.card_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.card_prints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.market_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.set_sync_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unmatched_price_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vault_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlist_items ENABLE ROW LEVEL SECURITY;
