/**
 * One web-side authority for the locked Collaborative Binders V1 RPC surface.
 * Raw Binder tables are never queried or mutated by the client.
 */
export const BINDER_READ_RPC = {
  dashboard: "binder_dashboard_v1",
  invitationInbox: "binder_invitation_inbox_v1",
  suspendedBinders: "binder_suspended_binders_v1",
  detail: "binder_detail_v1",
  checklist: "binder_checklist_v1",
  pendingContributions: "binder_pending_contributions_v1",
  activity: "binder_activity_v1",
  members: "binder_members_v1",
  joinRequestsQueue: "binder_join_requests_queue_v1",
  eligibleCopies: "binder_eligible_copies_v1",
  invitationPreview: "binder_invitation_preview_v1",
  publicDetail: "binder_public_detail_v1",
  viewLinkDetail: "binder_view_link_detail_v1",
  publicChecklist: "binder_public_checklist_v1",
  viewLinkChecklist: "binder_view_link_checklist_v1",
  explore: "binder_explore_v1",
  templateDetail: "binder_template_detail_v1",
  templateChecklist: "binder_template_checklist_v1",
  templates: "binder_templates_v1",
  legacyCandidates: "binder_legacy_candidates_v1",
  bulkPreview: "binder_bulk_preview_v1",
} as const;

export const BINDER_MUTATION_RPC = {
  create: "binder_create_v1",
  updateMetadata: "binder_update_metadata_v1",
  updatePolicy: "binder_update_policy_v1",
  setLifecycle: "binder_set_lifecycle_v1",
  delete: "binder_delete_v1",
  ownerTransferOffer: "binder_owner_transfer_offer_v1",
  ownerTransferAccept: "binder_owner_transfer_accept_v1",
  ownerTransferRevoke: "binder_owner_transfer_revoke_v1",
  inviteCreate: "binder_invite_create_v1",
  inviteAccept: "binder_invite_accept_v1",
  inviteDecline: "binder_invite_decline_v1",
  inviteRespond: "binder_invite_respond_v1",
  inviteRevoke: "binder_invite_revoke_v1",
  viewLinkCreate: "binder_view_link_create_v1",
  viewLinkRotate: "binder_view_link_rotate_v1",
  viewLinkRevoke: "binder_view_link_revoke_v1",
  joinRequestCreate: "binder_join_request_create_v1",
  joinRequestDecide: "binder_join_request_decide_v1",
  joinRequestWithdraw: "binder_join_request_withdraw_v1",
  memberChangeRole: "binder_member_change_role_v1",
  memberSuspend: "binder_member_suspend_v1",
  memberReinstate: "binder_member_reinstate_v1",
  memberRemove: "binder_member_remove_v1",
  leave: "binder_leave_v1",
  memberPreferences: "binder_member_preferences_v1",
  contributionAdd: "binder_contribution_add_v1",
  contributionWithdraw: "binder_contribution_withdraw_v1",
  contributionDecide: "binder_contribution_decide_v1",
  contributionRemove: "binder_contribution_remove_v1",
  bulkAdd: "binder_bulk_add_v1",
  customRevisionPublish: "binder_custom_revision_publish_v1",
  templateSubmit: "binder_template_submit_v1",
  templateClone: "binder_template_clone_v1",
  legacyDecide: "binder_legacy_decide_v1",
  report: "binder_report_v1",
  invitationReport: "binder_invitation_report_v1",
  publicActionReport: "binder_public_action_report_v1",
  pulseMilestoneShare: "binder_pulse_milestone_share_v1",
  blockOwner: "binder_block_owner_v1",
  blockMember: "binder_block_member_v1",
  publicMemberBlock: "binder_public_member_block_v1",
} as const;

export type BinderReadRpcName = (typeof BINDER_READ_RPC)[keyof typeof BINDER_READ_RPC];
export type BinderMutationRpcName =
  (typeof BINDER_MUTATION_RPC)[keyof typeof BINDER_MUTATION_RPC];
