import fs from 'node:fs';import assert from 'node:assert/strict';
import pg from 'pg';
import {VERSION,buildDiscoveryIntakePlan,applyDiscoveryIntakeBatch,verifyDiscoveryIntakeBatch,persistDiscoveryIntakeRun} from '../../backend/catalog/pokemon_warehouse_discovery_intake_v1.mjs';
import {CYCLE_VERSION,persistCycleRun} from '../../backend/catalog/pokemon_warehouse_discovery_runtime_v1.mjs';
const [name,out]=process.argv.slice(2);assert.match(name??'',/^grookai_tcgcsv_discovery_[a-z0-9_]+$/);assert.ok(out);fs.mkdirSync(out);
const url=new URL(process.env.DISCOVERY_INTAKE_PROOF_URL);assert.ok(['127.0.0.1','localhost'].includes(url.hostname),'local_fixture_only');assert.equal(url.pathname,'/postgres');
const config={connectionString:url.toString(),ssl:false,connectionTimeoutMillis:5000};
const admin=new pg.Client(config);await admin.connect();assert.equal((await admin.query('select 1 from pg_database where datname=$1',[name])).rowCount,0,'preserve_existing_lab');await admin.query(`create database ${name}`);await admin.end();
const fixtureUrl=new URL(url);fixtureUrl.pathname='/'+name;
const fixtureConfig={...config,connectionString:fixtureUrl.toString()};
const db=new pg.Client(fixtureConfig);await db.connect();assert.equal((await db.query('select current_database() name')).rows[0].name,name);const checks=[];
const count=async()=>Number((await db.query('select count(*) n from raw_imports')).rows[0].n);
try{
await db.query(`create table ingestion_jobs(id bigserial primary key,job_type text,status text,attempts int,last_attempt_at timestamptz,payload jsonb);
 create table raw_imports(id bigserial primary key,source text not null,status text not null,notes text,payload jsonb not null);
 select setval('raw_imports_id_seq',9007199254740992);
 create table tcgcsv_source_products(product_id bigint primary key,category_id int,group_id int,name text,clean_name text,image_url text,source_url text,source_modified_on timestamptz,image_count int,presale_info jsonb,extended_data jsonb,raw_payload jsonb,payload_hash text,source_active boolean,catalog_metadata_status text);
 create table external_discovery_candidates(id uuid primary key,source text not null,raw_import_id bigint not null references raw_imports(id),upstream_id text not null,tcgplayer_id text,set_id text not null,name_raw text not null,number_raw text,normalized_name text not null,normalized_number_left text,normalized_number_plain text,normalized_printed_total text,has_slash_number boolean not null,has_alpha_suffix_number boolean not null,has_parenthetical_modifier boolean not null,match_status text not null check(match_status in ('UNMATCHED','AMBIGUOUS','RESOLVED')),candidate_bucket text not null check(candidate_bucket in ('CLEAN_CANON_CANDIDATE','PRINTED_IDENTITY_REVIEW')),classifier_version text not null,payload jsonb not null,resolved_set_code text,card_print_id uuid,unique(source,upstream_id,raw_import_id));
 create table canon_warehouse_candidates(tcgplayer_id text);
 create table external_mappings(active boolean,source text,external_id text);
 create table card_prints(tcgplayer_id text,external_ids jsonb);
 create table sealed_product_source_mappings(source_provider text,source_product_id bigint,source_category_id int,mapping_status text,promotion_authorized boolean);`);
for(let i=1;i<=5;i++)await db.query(`insert into tcgcsv_source_products(product_id,category_id,group_id,name,image_url,source_url,source_modified_on,extended_data,raw_payload,payload_hash,source_active) values($1,3,5,$2,'https://example.test/image','https://example.test/source','2026-10-01T00:00:00Z',$3,$4,$5,true)`,[i,`Pokemon${i}`,JSON.stringify([{name:'Number',value:`00${i}/100`}]),JSON.stringify({productId:i,untouched:{nested:'source'}}),'a'.repeat(64)]);
const products=(await db.query('select * from tcgcsv_source_products order by product_id')).rows;
const plan=JSON.parse(JSON.stringify(buildDiscoveryIntakePlan({products,parents:[],mappings:[],discovery:[],warehouse:[],sealed:[]},products,{observedAt:'2026-10-01T00:00:00Z'})));
const authorization={approved:true,plan_fingerprint:plan.fingerprint,operator:'synthetic SQL proof',request:'local fixture only'};
const tx=()=>db.query('begin isolation level serializable read write');
await tx();await applyDiscoveryIntakeBatch(db,plan,plan.entries.slice(0,2),{authorization});await db.query('rollback');assert.equal(await count(),0);checks.push('raw/discovery rollback leaves no rows');
await tx();let injected=false;await assert.rejects(()=>applyDiscoveryIntakeBatch({query:async(q,a)=>{if(q.startsWith('insert into public.external_discovery_candidates')){injected=true;throw new Error('injected_after_raw');}return db.query(q,a);}},plan,plan.entries.slice(0,2),{authorization}),/injected_after_raw/);assert.ok(injected);await db.query('rollback');assert.equal(await count(),0);checks.push('failure after raw insertion remains atomic');
await db.query("update tcgcsv_source_products set name='Drift' where product_id=1");await tx();await assert.rejects(()=>applyDiscoveryIntakeBatch(db,plan,[plan.entries[0]],{authorization}),/source_snapshot_drift/);await db.query('rollback');await db.query("update tcgcsv_source_products set name='Pokemon1' where product_id=1");checks.push('changed source rejected');
await db.query("insert into external_mappings values(true,'tcgplayer','1')");await tx();await assert.rejects(()=>applyDiscoveryIntakeBatch(db,plan,[plan.entries[0]],{authorization}),/new_relationship_requires_fresh_plan/);await db.query('rollback');await db.query('delete from external_mappings');checks.push('new canonical relationship rejected');
await tx();await assert.rejects(()=>applyDiscoveryIntakeBatch(db,plan,[plan.entries[0]],{authorization:{...authorization,approved:false}}));await db.query('rollback');checks.push('missing authorization rejected');
await tx();const inserted=await applyDiscoveryIntakeBatch(db,plan,plan.entries.slice(0,2),{authorization});await db.query('commit');assert.ok(inserted.every(r=>r.status==='inserted_review_only'));assert.equal(await count(),2);assert.ok(inserted.every(r=>BigInt(r.raw_import_id)>9007199254740992n));checks.push('bulk commit and exact bigint lineage readback');
await tx();const repeat=await applyDiscoveryIntakeBatch(db,plan,plan.entries.slice(0,2),{authorization});await db.query('commit');assert.ok(repeat.every(r=>r.status==='already_succeeded'));assert.equal(await count(),2);checks.push('repeat creates no rows');
await tx();const partial=await applyDiscoveryIntakeBatch(db,plan,plan.entries.slice(0,3),{authorization});await db.query('commit');assert.deepEqual(partial.map(r=>r.status),['already_succeeded','already_succeeded','inserted_review_only']);assert.equal(await count(),3);checks.push('partial prior success verified without duplication');
await db.query("update external_discovery_candidates set match_status='RESOLVED' where id=$1",[plan.entries[0].candidate_id]);await tx();await assert.rejects(()=>applyDiscoveryIntakeBatch(db,plan,[plan.entries[0]],{authorization}),/discovery_readback:match_status/);await db.query('rollback');await db.query("update external_discovery_candidates set match_status='AMBIGUOUS' where id=$1",[plan.entries[0].candidate_id]);checks.push('subsequently resolved candidate cannot be silently replayed');
const a=new pg.Client(fixtureConfig),b=new pg.Client(fixtureConfig);await a.connect();await b.connect();
try{const work=async c=>{await c.query('begin isolation level serializable read write');try{const result=await applyDiscoveryIntakeBatch(c,plan,plan.entries.slice(3),{authorization});await c.query('commit');return result;}catch(e){await c.query('rollback');throw e;}};const concurrent=await Promise.allSettled([work(a),work(b)]);assert.ok(concurrent.some(r=>r.status==='fulfilled'));for(const r of concurrent)if(r.status==='rejected')assert.ok(['23505','40001'].includes(r.reason.code),r.reason.stack);assert.equal(await count(),5);checks.push('concurrent requests cannot duplicate raw/discovery');}finally{await a.end();await b.end();}
await verifyDiscoveryIntakeBatch(db,plan,plan.entries);assert.equal((await db.query('select count(*)::int n from external_discovery_candidates')).rows[0].n,5);checks.push('all committed candidate and source payloads independently verified');
await tx();const run={version:VERSION,run_id:'synthetic-run',plan_fingerprint:plan.fingerprint};const jobId=await persistDiscoveryIntakeRun(db,{status:'running',payload:run});await db.query('commit');
await tx();await persistDiscoveryIntakeRun(db,{jobId,status:'succeeded',payload:{...run,verified:5}});await db.query('commit');assert.equal((await db.query('select status from ingestion_jobs where id=$1',[jobId])).rows[0].status,'succeeded');
await tx();const failedId=await persistDiscoveryIntakeRun(db,{status:'failed',payload:{...run,run_id:'synthetic-failure',error_code:'INJECTED',error_detail:'verified failure persistence'}});await db.query('commit');const failed=(await db.query('select * from ingestion_jobs where id=$1',[failedId])).rows[0];assert.equal(failed.status,'failed');assert.equal(failed.payload.error_code,'INJECTED');checks.push('success and failure persist in operational job ledger');
const cycle={version:CYCLE_VERSION,run_id:'cycle-fixture',producer_commit:'a'.repeat(40),stage:'plan'};
await tx();const cycleId=await persistCycleRun(db,{status:'running',payload:cycle});await db.query('commit');
await tx();await persistCycleRun(db,{jobId:cycleId,status:'failed',payload:{...cycle,stage:'apply',error_code:'UNKNOWN_COMMIT'}});await db.query('commit');
const cycleRow=(await db.query('select * from ingestion_jobs where id=$1',[cycleId])).rows[0];assert.equal(cycleRow.status,'failed');assert.equal(cycleRow.payload.error_code,'UNKNOWN_COMMIT');
await tx();await assert.rejects(()=>persistCycleRun(db,{jobId,status:'failed',payload:cycle}));await db.query('rollback');assert.equal((await db.query('select status from ingestion_jobs where id=$1',[jobId])).rows[0].status,'succeeded');checks.push('cycle failure durable; foreign job cannot be overwritten');
const contender=new pg.Client(fixtureConfig);await contender.connect();try{
 const lock="select pg_try_advisory_lock(hashtext('pokemon_discovery_cycle_v1')) locked";
 assert.equal((await db.query(lock)).rows[0].locked,true);assert.equal((await contender.query(lock)).rows[0].locked,false);
 await db.query("select pg_advisory_unlock(hashtext('pokemon_discovery_cycle_v1'))");assert.equal((await contender.query(lock)).rows[0].locked,true);checks.push('session lock excludes concurrent cycles and releases for next cycle');
}finally{await contender.end();}
const report={status:'passed',at:new Date().toISOString(),database:name,scope:'isolated synthetic schema; not full production schema replay',checks,raw_rows:await count()};fs.writeFileSync(out+'/proof.json',JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(report);
}catch(e){fs.writeFileSync(out+'/failure.json',JSON.stringify({status:'failed',checks,error:e.stack},null,2)+'\n',{flag:'wx'});throw e;}finally{await db.end();}
